// KL research spots (51)
// Auto-generated by batch-research.ts — enrich via /review UI

export const spots = [

  // ============================================
  // BREAKFAST
  // ============================================
  {
    name: "Urban Daybreak",
    city: "Kuala Lumpur",
    area: "Bangsar",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "MTR 1924",
    city: "Kuala Lumpur",
    area: "Brickfields",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "Antipodean Cafe",
    city: "Kuala Lumpur",
    area: "Bukit Bintang",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "Yooi Kee",
    city: "Kuala Lumpur",
    area: "Chinatown",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "Yut Kee Restaurant",
    city: "Kuala Lumpur",
    area: "Chow Kit",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "Croisserie Artisan Bakery",
    city: "Kuala Lumpur",
    area: "Damansara Heights",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "Kak Som",
    city: "Kuala Lumpur",
    area: "Kampung Baru",
    categories: ["breakfast"],
    source: "llm_research",
  },
  {
    name: "VCR Stacks",
    city: "Kuala Lumpur",
    area: "Mont Kiara",
    categories: ["breakfast"],
    source: "llm_research",
  },

  // ============================================
  // LUNCH
  // ============================================
  {
    name: "Torigen Ramen",
    city: "Kuala Lumpur",
    area: "Bukit Bintang",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Aria Restaurant & Bar",
    city: "Kuala Lumpur",
    area: "Damansara Heights",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Ramen Seirock-ya",
    city: "Kuala Lumpur",
    area: "Damansara Uptown",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Don's Warong",
    city: "Kuala Lumpur",
    area: "Hartamas",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Rembayung",
    city: "Kuala Lumpur",
    area: "Kampung Baru",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Serai",
    city: "Kuala Lumpur",
    area: "KLCC",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Feng Yun Ke Zhan",
    city: "Kuala Lumpur",
    area: "Mont Kiara",
    categories: ["lunch"],
    source: "llm_research",
  },
  {
    name: "Zok Noodle House",
    city: "Kuala Lumpur",
    area: "Pavilion",
    categories: ["lunch"],
    source: "llm_research",
  },

  // ============================================
  // DINNER
  // ============================================
  {
    name: "Anak Baba",
    city: "Kuala Lumpur",
    area: "Brickfields",
    categories: ["dinner"],
    source: "llm_research",
  },
  {
    name: "Restoran Char Siew Yoong",
    city: "Kuala Lumpur",
    area: "Cheras",
    categories: ["dinner"],
    source: "llm_research",
  },
  {
    name: "Tang City Food Court",
    city: "Kuala Lumpur",
    area: "Chinatown",
    categories: ["dinner"],
    source: "llm_research",
  },
  {
    name: "Tapestry",
    city: "Kuala Lumpur",
    area: "Chow Kit",
    categories: ["dinner"],
    source: "llm_research",
  },
  {
    name: "Ramen Seirock-ya",
    city: "Kuala Lumpur",
    area: "Damansara Uptown",
    categories: ["dinner"],
    source: "llm_research",
  },
  {
    name: "Fatt Kee Roast Duck & Chicken Restaurant",
    city: "Kuala Lumpur",
    area: "Pudu",
    categories: ["dinner"],
    source: "llm_research",
  },

  // ============================================
  // CAFE
  // ============================================
  {
    name: "Solace Cafe & Restaurant",
    city: "Kuala Lumpur",
    area: "Bukit Bintang",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "Poppy Kat",
    city: "Kuala Lumpur",
    area: "Cheras",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "Niko Neko Matcha 2.0",
    city: "Kuala Lumpur",
    area: "Chinatown",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "103 Coffee",
    city: "Kuala Lumpur",
    area: "Chow Kit",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "Ground Coffee Uptown",
    city: "Kuala Lumpur",
    area: "Damansara Uptown",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "RaRa Coffee",
    city: "Kuala Lumpur",
    area: "Hartamas",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "Eight Ounce Coffee Co.",
    city: "Kuala Lumpur",
    area: "KLCC",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "illy Caffè",
    city: "Kuala Lumpur",
    area: "Pavilion",
    categories: ["cafe"],
    source: "llm_research",
  },
  {
    name: "Cafe 5",
    city: "Kuala Lumpur",
    area: "Pudu",
    categories: ["cafe"],
    source: "llm_research",
  },

  // ============================================
  // ACTIVITY
  // ============================================
  {
    name: "Tangram",
    city: "Kuala Lumpur",
    area: "Bangsar",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Anak Baba",
    city: "Kuala Lumpur",
    area: "Brickfields",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Damascus (Shawarma Damascus)",
    city: "Kuala Lumpur",
    area: "Bukit Bintang",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Yulek Wan Tan Mee",
    city: "Kuala Lumpur",
    area: "Cheras",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Aliyaa",
    city: "Kuala Lumpur",
    area: "Damansara Heights",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "The Good Batch",
    city: "Kuala Lumpur",
    area: "Damansara Uptown",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Slow Wood Coffee",
    city: "Kuala Lumpur",
    area: "Mont Kiara",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Zok Noodle House",
    city: "Kuala Lumpur",
    area: "Pavilion",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Kei Suk Wantan Mee",
    city: "Kuala Lumpur",
    area: "Pudu",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Pad Boy",
    city: "Kuala Lumpur",
    area: "Taman Paramount",
    categories: ["activity"],
    source: "llm_research",
  },
  {
    name: "Peko Peko",
    city: "Kuala Lumpur",
    area: "TTDI",
    categories: ["activity"],
    source: "llm_research",
  },

  // ============================================
  // NIGHTLIFE
  // ============================================
  {
    name: "Save Our Souls",
    city: "Kuala Lumpur",
    area: "Bangsar",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Barfly C180",
    city: "Kuala Lumpur",
    area: "Cheras",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Mankar",
    city: "Kuala Lumpur",
    area: "Chow Kit",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Tap Tap",
    city: "Kuala Lumpur",
    area: "Hartamas",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Suraya Seafood",
    city: "Kuala Lumpur",
    area: "Kampung Baru",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Viva Havana (Cafe Havana)",
    city: "Kuala Lumpur",
    area: "Mont Kiara",
    categories: ["nightlife"],
    source: "llm_research",
  },
  {
    name: "Remedy Cocktail Bar",
    city: "Kuala Lumpur",
    area: "Taman Paramount",
    categories: ["nightlife"],
    source: "llm_research",
  },

  // ============================================
  // MARKET
  // ============================================
  {
    name: "Gerai Makanan Sai Kee",
    city: "Kuala Lumpur",
    area: "Chinatown",
    categories: ["market"],
    source: "llm_research",
  },
  {
    name: "Food Republic at Pavilion KL",
    city: "Kuala Lumpur",
    area: "KLCC",
    categories: ["market"],
    source: "llm_research",
  },
];
