// Kuala Lumpur spots (49)

export const spots = [
  {
    name: "Nasi Lemak Tanglin",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Tanglin",
    categories: ["breakfast"],
    address: "Jalan Tanglin, opposite Tanglin Tennis Centre",
    latitude: 3.1456,
    longitude: 101.6862,
    price_range: "$",
    what_to_order: ["Nasi lemak biasa with extra sambal", "Add fried chicken (ayam goreng)"],
    pro_tips: [
      "Cash only — no exceptions",
      "This is a roadside stall, not a restaurant. That's the charm.",
      "Opens at 5:30am, sells out by 10am on weekends",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "5:30am-11am" },
  },
  {
    name: "Yut Kee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Dang Wangi",
    categories: ["breakfast"],
    address: "1, Jalan Kamunting",
    latitude: 3.1535,
    longitude: 101.6968,
    price_range: "$",
    what_to_order: ["Roti babi (pork bread)", "Hainanese chicken chop", "Kaya toast"],
    what_to_skip: ["Anything too adventurous — stick to the classics"],
    pro_tips: [
      "Heritage kopitiam since 1928 — the real deal",
      "Cash only, no card",
      "Go early on weekends, fills up by 9:30am",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "7:30am-4:30pm", closed: "Monday" },
  },

  // ============================================
  // LUNCH
  // ============================================
  {
    name: "Soong Kee Beef Noodles",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["lunch"],
    address: "86, Jalan Tun H.S. Lee",
    latitude: 3.1441,
    longitude: 101.6960,
    price_range: "$",
    what_to_order: ["Dry beef noodles (kon lo)", "Add tendon and tripe"],
    pro_tips: [
      "Absolutely legendary — been here for decades",
      "Cash only. RM10-15 per bowl.",
      "Lunch only — arrive by 11:30am, sells out by 1pm",
      "No AC, just fans. Part of the experience.",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "8:30am-1:30pm" },
  },
  {
    name: "Restoran Rebung Chef Ismail",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "6, Jalan Bangkung, Bangsar",
    latitude: 3.1295,
    longitude: 101.6721,
    price_range: "$$",
    what_to_order: ["Buffet — try everything, especially rendang, ulam, and kuih"],
    pro_tips: [
      "Best Malay buffet in KL — run by celebrity chef Ismail",
      "Go for lunch, not dinner",
      "Dress modestly — it's near a mosque",
      "About RM50-60 per person for the buffet",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11:30am-3pm, 6:30pm-10pm" },
  },
  {
    name: "Samy's Curry House",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Brickfields",
    categories: ["lunch"],
    address: "25, Jalan Dewan Sultan Sulaiman",
    latitude: 3.1335,
    longitude: 101.6873,
    price_range: "$",
    what_to_order: ["Fish head curry", "Banana leaf rice", "Mutton varuval"],
    pro_tips: [
      "Eating on banana leaf is the move — mix everything with your hands",
      "Ask for extra rasam (the soup) — it's free refills",
      "Near KL Sentral, easy to get to",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-10pm" },
  },

  // ============================================
  // DINNER
  // ============================================
  {
    name: "Wong Ah Wah",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["dinner"],
    address: "1-9, Jalan Alor, Bukit Bintang",
    latitude: 3.1459,
    longitude: 101.7082,
    price_range: "$",
    what_to_order: ["Chicken wings (legendary)", "Satay", "Kangkung belacan"],
    what_to_skip: ["Don't eat at the first stall that calls out to you on Jalan Alor"],
    pro_tips: [
      "Jalan Alor is touristy BUT Wong Ah Wah is the one locals actually go to",
      "Cash only",
      "Go after 7pm for the full atmosphere",
      "Sit outside for the street food vibe",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "5pm-4am" },
  },
  {
    name: "Bijan Bar & Restaurant",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Ceylon",
    categories: ["dinner"],
    address: "3, Jalan Ceylon, Bukit Ceylon",
    latitude: 3.1495,
    longitude: 101.7108,
    price_range: "$$$",
    what_to_order: ["Satay", "Rendang", "Nasi kerabu", "Any curry"],
    pro_tips: [
      "Fine dining Malay food — if you want to splurge on one nice dinner, this is it",
      "Make a reservation, especially weekends",
      "The garden terrace is beautiful",
      "About RM150-200 per person with drinks",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { daily: "6pm-11pm" },
  },
  {
    name: "Mansion Tea Stall",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Masjid India",
    categories: ["dinner"],
    address: "Selangor Mansion, Jalan Masjid India",
    latitude: 3.1610,
    longitude: 101.7020,
    price_range: "$",
    what_to_order: ["Nasi campur", "Ayam percik", "Teh tarik"],
    pro_tips: [
      "THE spot to experience Kampung Baru at night",
      "Cash only, super cheap — RM10-15 fills you up",
      "Walk through the kampung after — it's magical at night",
      "The area is safe but bring minimal valuables",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "6pm-midnight" },
  },

  // ============================================
  // CAFES
  // ============================================
  {
    name: "VCR",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["cafe"],
    address: "2, Jalan Galloway, off Jalan Pudu",
    latitude: 3.1419,
    longitude: 101.7071,
    price_range: "$$",
    what_to_order: ["Flat white", "Avocado toast", "Any pastry"],
    pro_tips: [
      "KL's OG specialty coffee spot — been around since the third wave started here",
      "Great for a quiet afternoon work session",
      "The brunch menu is solid but comes at cafe prices",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "8am-6pm" },
  },
  {
    name: "Merchant's Lane",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["cafe"],
    address: "150, Jalan Petaling (above a traditional Chinese medicine shop)",
    latitude: 3.1441,
    longitude: 101.6972,
    price_range: "$$",
    what_to_order: ["Pandan waffle", "Nasi lemak burger", "Any coffee"],
    pro_tips: [
      "The entrance is through a narrow staircase above a Chinese medicine shop — that's the charm",
      "Beautiful interior in a restored pre-war building",
      "Great for Instagram but also genuinely good food",
      "Combine with a Chinatown walk",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "wed-mon": "11am-8pm", closed: "Tuesday" },
  },
  {
    name: "PPP Coffee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["cafe"],
    address: "19, Lorong Panggung, Chinatown",
    latitude: 3.1453,
    longitude: 101.6964,
    price_range: "$$",
    what_to_order: ["Filter coffee (ask what's on rotation)", "Flat white"],
    pro_tips: [
      "Serious specialty coffee in a beautifully restored shophouse",
      "They roast their own beans — ask about single origins",
      "Great combo with Merchant's Lane and Chinatown exploring",
      "Small space, limited seating — go off-peak",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "9am-6pm", closed: "Monday" },
  },
  {
    name: "Feeka Coffee Roasters",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["cafe"],
    address: "19, Jalan Mesui, Bukit Bintang",
    latitude: 3.1490,
    longitude: 101.7060,
    price_range: "$$",
    what_to_order: ["Latte", "Big breakfast", "Banana bread"],
    pro_tips: [
      "Tucked in a quiet lane off the Bukit Bintang chaos — a nice escape",
      "Good brunch spot, decent portions for cafe food",
      "Popular on weekends — get there before 11am for a table",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "8am-10pm" },
  },
  {
    name: "Kenny Hills Bakers",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["cafe"],
    address: "Lot G-2, The Greens Terrace, Jalan Wan Kadir 3, TTDI",
    latitude: 3.1359,
    longitude: 101.6302,
    price_range: "$$",
    what_to_order: ["Sourdough loaf (best in KL)", "Croissant", "Any pastry with coffee"],
    pro_tips: [
      "The sourdough bread is genuinely world-class — locals queue for it",
      "Arrive early on weekends — the good stuff sells out by noon",
      "Also has a spot in Bukit Tunku if TTDI is too far",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { daily: "7:30am-6pm" },
  },

  // ============================================
  // MAMAK (Late Night)
  // ============================================
  {
    name: "Nasi Kandar Pelita",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["dinner"],
    address: "149, Jalan Ampang",
    latitude: 3.1577,
    longitude: 101.7175,
    price_range: "$",
    what_to_order: ["Nasi kandar", "Roti canai", "Teh tarik"],
    pro_tips: [
      "Open 24 hours — THE late-night mamak spot",
      "Point at the curries you want — they'll pile them on rice",
      "The roti canai at 2am hits different",
      "Always packed but turnover is fast",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "Mamak Mansion",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kampung Baru",
    categories: ["dinner"],
    address: "1, Jalan Raja Muda Abdul Aziz, Kampung Baru",
    latitude: 3.1620,
    longitude: 101.7001,
    price_range: "$",
    what_to_order: ["Mee goreng mamak", "Roti cheese", "Maggi goreng"],
    pro_tips: [
      "A slightly more polished mamak experience — still authentic flavors",
      "The maggi goreng is addictive and only RM8",
      "Good late-night option near Kampung Baru",
      "Air-conditioned section available if you want to escape the heat",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "Ali Muthu Ah Hock",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["dinner"],
    address: "10, Jalan Telawi 2, Bangsar",
    latitude: 3.1297,
    longitude: 101.6708,
    price_range: "$",
    what_to_order: ["Roti canai", "Nasi lemak", "Teh tarik"],
    pro_tips: [
      "Named after Malaysia's three main ethnicities — the perfect late-night mamak",
      "Right in the heart of Bangsar nightlife strip",
      "Great pit stop between bars or after a night out",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "24 hours" },
  },

  // ============================================
  // MARKETS
  // ============================================
  {
    name: "Chow Kit Wet Market",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chow Kit",
    categories: ["market"],
    address: "Jalan TAR, Chow Kit",
    latitude: 3.1660,
    longitude: 101.6987,
    price_range: "$",
    what_to_order: ["Browse and snack — fresh tropical fruits, kuih, fried snacks"],
    pro_tips: [
      "Go before 10am for the full experience — it's a REAL wet market, not tourist market",
      "Wear shoes you don't mind getting wet",
      "The fruit section is incredible — ask uncle to pick you a ripe mangosteen",
      "Combine with breakfast at one of the stalls inside",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { daily: "6am-2pm" },
  },
  {
    name: "Pasar Seni (Central Market)",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["market"],
    address: "Jalan Hang Kasturi",
    latitude: 3.1456,
    longitude: 101.6953,
    price_range: "$",
    what_to_order: ["Batik souvenirs", "Local handicrafts"],
    what_to_skip: ["Overpriced 'antiques'", "Don't buy the first price — negotiate"],
    pro_tips: [
      "Tourist-oriented but a decent one-stop for souvenirs",
      "The food court upstairs (Annexe) has decent options",
      "Not the most authentic market — Chow Kit or Pudu are realer",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-9:30pm" },
  },

  // ============================================
  // ACTIVITIES
  // ============================================
  {
    name: "Batu Caves",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Batu Caves",
    categories: ["activity"],
    address: "Sri Subramaniar Swamy Temple, Batu Caves",
    latitude: 3.2379,
    longitude: 101.6840,
    price_range: "$",
    what_to_order: ["Free entry to main cave", "Dark Cave tour RM35 (worth it)"],
    pro_tips: [
      "Go at 7am to beat the crowds and heat — 272 steps in KL humidity is no joke",
      "Watch your belongings — the monkeys WILL steal your water bottle",
      "Wear covered shoulders and knees (temple)",
      "Take KTM train from KL Sentral — cheaper and easier than Grab",
      "The Dark Cave tour is genuinely fascinating if you're into nature",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "6am-9pm" },
  },
  {
    name: "Islamic Arts Museum",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Lake Gardens",
    categories: ["activity"],
    address: "Jalan Lembah Perdana",
    latitude: 3.1424,
    longitude: 101.6878,
    price_range: "$",
    what_to_order: ["Entry RM14 (worth it)", "The Architecture Gallery is the highlight"],
    pro_tips: [
      "Underrated gem — most tourists skip this for Petronas. Their loss.",
      "Beautiful building, world-class collection",
      "Great rainy day activity — fully indoor, AC",
      "The gift shop has genuinely nice souvenirs (calligraphy, tiles)",
      "Combine with a walk through the Lake Gardens next door",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-6pm" },
  },
  {
    name: "Petronas Twin Towers + KLCC Park",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["activity"],
    address: "KLCC, Kuala Lumpur City Centre",
    latitude: 3.1578,
    longitude: 101.7117,
    price_range: "$$",
    what_to_order: ["Skybridge tickets RM80 (book online 2 days ahead)", "KLCC Park is free"],
    what_to_skip: ["Don't eat at Suria KLCC food court — overpriced tourist food"],
    pro_tips: [
      "The park at the base is honestly better than going up the towers",
      "Free water fountain show every night at 8pm, 9pm, 10pm",
      "Book Skybridge tickets online — same-day walk-ins sell out by 9am",
      "Best photo spot: across the road at Trader's Hotel rooftop",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { "tue-sun": "9am-9pm", closed: "Monday" },
  },
  {
    name: "Thean Hou Temple",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Robson Heights",
    categories: ["activity"],
    address: "65, Persiaran Endah, Taman Persiaran Desa",
    latitude: 3.1183,
    longitude: 101.6862,
    price_range: "$",
    what_to_order: ["Free entry", "Light incense (donation-based)"],
    pro_tips: [
      "Most beautiful Chinese temple in KL — and way less crowded than you'd expect",
      "Go at sunset for incredible views of the KL skyline",
      "Free entry, just donate what you feel",
      "Grab there, it's on a hill with no public transport nearby",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "8am-10pm" },
  },
  {
    name: "Merdeka Square",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Dataran Merdeka",
    categories: ["activity"],
    address: "Jalan Raja, Dataran Merdeka",
    latitude: 3.1488,
    longitude: 101.6935,
    price_range: "$",
    what_to_order: ["Free to visit", "Photo with the flagpole and Sultan Abdul Samad Building"],
    pro_tips: [
      "Where Malaysian independence was declared in 1957 — historically significant",
      "The Sultan Abdul Samad Building (Moorish architecture) is gorgeous at golden hour",
      "Combine with Chinatown walk, it's a 10-minute stroll south",
      "Visit early morning or evening to avoid the heat — it's an open field",
      "KL City Gallery is right here if you want AC and a quick history lesson",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "KL Tower (Menara KL)",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Nanas",
    categories: ["activity"],
    address: "2, Jalan Puncak, Off Jalan P. Ramlee",
    latitude: 3.1528,
    longitude: 101.7038,
    price_range: "$$",
    what_to_order: ["Observation deck RM52", "Sky Deck (open air) RM105 for the real thrill"],
    what_to_skip: ["The XD Theatre — skip it, not worth the extra"],
    pro_tips: [
      "Better panoramic views than Petronas — you can actually see Petronas from here",
      "The Sky Deck (open-air glass floor) is genuinely thrilling",
      "Way less crowded than Petronas, no need to book days ahead",
      "Walk through Bukit Nanas Forest Reserve on the way — oldest protected jungle in Malaysia, right in the city",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "9am-10pm" },
  },
  {
    name: "Aquaria KLCC",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["activity"],
    address: "Kuala Lumpur Convention Centre, KLCC",
    latitude: 3.1534,
    longitude: 101.7132,
    price_range: "$$",
    what_to_order: ["Entry RM69 (online cheaper)", "90m underwater tunnel is the highlight"],
    pro_tips: [
      "Good rainy day activity, especially if traveling with kids",
      "The underwater tunnel with sharks and rays overhead is legit impressive",
      "Book online for 10-15% discount",
      "Combine with KLCC Park — it's in the convention centre basement",
      "Takes about 1-1.5 hours to walk through",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-8pm" },
  },
  {
    name: "Kampung Baru Walking Tour",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kampung Baru",
    categories: ["activity"],
    address: "Start at Masjid Jamek LRT station, walk north",
    latitude: 3.1590,
    longitude: 101.6998,
    price_range: "$",
    what_to_order: ["Self-guided walk is free", "Snack on kuih and keropok from street vendors"],
    pro_tips: [
      "The last traditional Malay village in central KL — wooden stilt houses next to skyscrapers",
      "Go late afternoon for golden hour light + less heat",
      "The Saturday night market (Pasar Malam) is incredible — food stalls everywhere",
      "Very safe area, locals are friendly — just be respectful and dress modestly",
      "End at Mansion Tea Stall for dinner — perfect bookend",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "anytime (market: Saturday evening)" },
  },

  // ============================================
  // NIGHTLIFE
  // ============================================
  {
    name: "PS150",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["nightlife"],
    address: "150, Jalan Petaling (hidden entrance in Chinatown)",
    latitude: 3.1441,
    longitude: 101.6970,
    price_range: "$$$",
    what_to_order: ["Ask the bartender for their recommendation based on your taste", "Any cocktail with local ingredients"],
    pro_tips: [
      "Best cocktail bar in KL — consistently on Asia's 50 Best Bars",
      "Hidden entrance: look for the red door on Petaling Street",
      "No reservations needed on weekdays, book weekends",
      "Cocktails RM45-65 — not cheap but worth it",
      "Try something with local Malaysian ingredients",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Heli Lounge Bar",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["nightlife"],
    address: "Menara KH, Jalan Sultan Ismail",
    latitude: 3.1505,
    longitude: 101.7018,
    price_range: "$$",
    what_to_order: ["Any beer or basic cocktail — you're here for the view"],
    what_to_skip: ["Food — eat before you come"],
    pro_tips: [
      "It's literally a helipad on top of a building. You drink ON the helipad.",
      "Best view of KL skyline, especially at sunset",
      "Drinks are surprisingly affordable (RM25-40)",
      "Go before 7pm to grab a spot for sunset",
      "Dress code: no slippers (flip flops)",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Coley Cocktail Bar",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["nightlife"],
    address: "6-G, Jalan Abdullah, Bangsar",
    latitude: 3.1292,
    longitude: 101.6696,
    price_range: "$$$",
    what_to_order: ["The seasonal cocktail menu", "Ask CK (the owner-bartender) what he recommends"],
    pro_tips: [
      "One of Asia's best bars — CK the bartender is a legend, a true craftsman",
      "Small space, only 20-ish seats — go early (before 9pm) or prepare to wait",
      "Cocktails RM42-58 — they use local Malaysian ingredients beautifully",
      "The vibe is intimate and personal — like drinking at a friend's place",
      "No loud music, no pretension — just exceptional cocktails",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sat": "5pm-midnight", closed: "Sunday, Monday" },
  },
  {
    name: "JungleBird",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Damansara Heights",
    categories: ["nightlife"],
    address: "61M, Jalan Medan Setia 1, Bukit Damansara",
    latitude: 3.1503,
    longitude: 101.6535,
    price_range: "$$",
    what_to_order: ["The JungleBird cocktail (named after the bar)", "Any tiki cocktail"],
    pro_tips: [
      "Tiki bar vibes in a tropical city — makes total sense",
      "Named after the classic Malaysian cocktail — order the namesake, it's their signature",
      "More relaxed than PS150, good for groups",
      "Happy hour 5-7pm is solid value",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Changkat Bukit Bintang",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["nightlife"],
    address: "Changkat Bukit Bintang (whole street)",
    latitude: 3.1472,
    longitude: 101.7090,
    price_range: "$$",
    what_to_order: ["Bar hop — try Pisco Bar, Whisky Bar, or El Cerdo"],
    what_to_skip: ["Avoid the aggressive club promoters"],
    pro_tips: [
      "KL's main nightlife strip — wall-to-wall bars and clubs",
      "Touristy but fun for a night out, especially if you want variety",
      "Pisco Bar for cocktails, El Cerdo for roast pork + wine",
      "Gets loud and rowdy after 11pm — that's the point",
      "Grab home — don't try to drive or find parking here",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "5pm-3am" },
  },

  // ============================================
  // MORE FOOD SPOTS
  // ============================================
  {
    name: "ICC Pudu",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Pudu",
    categories: ["lunch"],
    address: "Jalan 1/77C, Imbi",
    latitude: 3.1388,
    longitude: 101.7097,
    price_range: "$",
    what_to_order: ["Hokkien mee", "Curry mee", "Chee cheong fun", "Roast duck"],
    pro_tips: [
      "This is where KL locals actually eat — a massive hawker complex",
      "Every stall specializes in one thing. Pick 3-4 stalls and share.",
      "Cash only everywhere. ATM outside.",
      "Go for lunch, arrive by 11:30am — some stalls sell out by 1pm",
      "The hokkien mee stall (dark soy version) is legendary",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "7am-3pm" },
  },
  {
    name: "Lot 10 Hutong",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["lunch"],
    address: "Lot 10 Shopping Centre, Basement, 50, Jalan Bukit Bintang",
    latitude: 3.1483,
    longitude: 101.7109,
    price_range: "$",
    what_to_order: ["Ho Weng Kee wonton mee", "Kim Lian Kee hokkien mee", "Soong Kee beef noodles"],
    pro_tips: [
      "Best hawker stalls gathered under one AC roof — great if you can't handle the heat",
      "More expensive than the actual stalls but much more comfortable",
      "Good first-day introduction to Malaysian hawker food",
      "Air conditioned — perfect rainy day option",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-10pm" },
  },
  {
    name: "Jalan Alor Hawker Street",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["dinner"],
    address: "Jalan Alor, off Jalan Bukit Bintang",
    latitude: 3.1457,
    longitude: 101.7083,
    price_range: "$",
    what_to_order: ["Grilled chicken wings", "Satay", "Fried carrot cake"],
    what_to_skip: ["Restaurants that aggressively try to seat you — find your own spot"],
    pro_tips: [
      "Yes it's touristy. But it's still an experience worth having once.",
      "Wong Ah Wah (at the end) is the best stall on the whole street",
      "Go after 7pm when all stalls are open and the atmosphere is alive",
      "Cash only at most stalls",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "5pm-3am" },
  },
  {
    name: "Aunty Christina's Sarawak Laksa",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["lunch"],
    address: "TTDI Market, Lorong Datuk Sulaiman 1",
    latitude: 3.1336,
    longitude: 101.6296,
    price_range: "$",
    what_to_order: ["Sarawak laksa (the ONLY thing on the menu)"],
    pro_tips: [
      "She serves one thing and one thing only — Sarawak laksa. And it's incredible.",
      "Cash only, RM12 per bowl",
      "Inside TTDI wet market — go in the morning, she sells out by noon",
      "Combine with exploring TTDI market for breakfast",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "7am-12pm", closed: "Monday" },
  },
  {
    name: "Dewakan",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["dinner"],
    address: "Level 48, Naza Tower, Platinum Park, Persiaran KLCC",
    latitude: 3.1553,
    longitude: 101.7137,
    price_range: "$$$",
    what_to_order: ["The tasting menu (there's only one option)", "Wine pairing if you drink"],
    pro_tips: [
      "Only restaurant in Malaysia on Asia's 50 Best — legit world-class",
      "Book 2-3 weeks in advance minimum",
      "Tasting menu RM550 per person, wine pairing RM350",
      "Located on Level 48 of Naza Tower in KLCC — stunning city views",
      "Worth the trip if food is your thing and you want to splurge once",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "wed-sat": "6pm-11pm" },
  },
  {
    name: "Devi's Corner",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["dinner"],
    address: "Jalan Telawi 3, Bangsar",
    latitude: 3.1301,
    longitude: 101.6713,
    price_range: "$",
    what_to_order: ["Tandoori chicken", "Roti canai", "Banana leaf rice"],
    pro_tips: [
      "Bangsar institution — been here forever, open late",
      "The tandoori chicken is the star — crispy, smoky, perfect",
      "Great late-night option after Bangsar bar hopping",
      "Outdoor seating on the street — buzzy atmosphere at night",
    ],
    vibe: "local",
    best_time_of_day: "late-night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { daily: "7am-2am" },
  },
  {
    name: "Marini's on 57",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["nightlife"],
    address: "Level 57, Menara 3 Petronas, KLCC",
    latitude: 3.1577,
    longitude: 101.7137,
    price_range: "$$$",
    what_to_order: ["Any cocktail — you're paying for the view", "The sunset aperitivo"],
    what_to_skip: ["Full dinner menu — overpriced for what you get"],
    pro_tips: [
      "Level 57 with floor-to-ceiling windows — jaw-dropping view of the Twin Towers",
      "Smart casual dress code (no shorts/slippers)",
      "Go at sunset for the best experience",
      "Cocktails RM55-80 — expensive but this is THE view",
      "Book a window table in advance for special occasions",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "4pm-1am" },
  },

  // ============================================
  // ADDED VIA /add-spot (web-researched, Feb 2026)
  // ============================================
  {
    name: "Nasi Kandar Line Clear",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kampung Baru",
    categories: ["dinner"],
    address: "113, Jalan Raja Abdullah, Kampung Baru, 50300 Kuala Lumpur",
    latitude: 3.162,
    longitude: 101.6985,
    opening_hours: { daily: "7am-midnight" },
    price_range: "$",
    what_to_order: [
      "Nasi kandar with kuah campur — point at the curries you want, they pile them on rice",
      "Ayam goreng berempah (fried spiced chicken)",
      "Sambal sotong (spicy squid) — the crowd favourite",
      "Roti canai with dhal",
      "Friday special: nasi kandaq with chicken + veg for RM7.50 (9am-10pm)",
    ],
    what_to_skip: ["Avoid peak lunch hour (12-1pm) unless you enjoy queueing"],
    pro_tips: [
      "Air-conditioned — rare for a nasi kandar spot, great escape from KL heat",
      "Originally from Penang — this is the KL branch, same legendary recipes",
      "Point-and-choose system: pick your curries and they build your plate",
      "Gets packed at peak hours but turnover is fast — queue moves quickly",
      "Late dinner (after 9pm) is the sweet spot — shorter queue, full menu still available",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Imbi Market",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Imbi",
    categories: ["breakfast"],
    address: "Jalan Kijang, Pudu, 55100 Kuala Lumpur (inside ICC Pudu)",
    latitude: 3.1395,
    longitude: 101.711,
    opening_hours: { daily: "6am-1pm" },
    price_range: "$",
    what_to_order: [
      "Sisters' Crispy Popiah — pandan crepes with jicama, cucumber, peanuts",
      "Bunn Choon mini egg tarts — flaky crust, wobbly custard filling",
      "Hainanese assam laksa — tamarind fish soup with mackerel and pineapple",
      "Nasi lemak from the morning stalls",
      "Mee halia (ginger wine noodles) — unique to this market",
    ],
    what_to_skip: ["Don't come after noon — best stalls sell out by 11am"],
    pro_tips: [
      "Relocated from the original Jalan Imbi site to ICC Pudu in 2016",
      "Arrive between 8-9am for freshest food and to beat the crowds",
      "Cash only everywhere — no card, no e-wallet at the stalls",
      "Combine with ICC Pudu food court which is in the same building",
      "This is where KL locals do their morning market run — very authentic",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Baba Low's",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "11, Lorong Kurau, Taman Bukit Pantai, 59100 Kuala Lumpur",
    latitude: 3.1275,
    longitude: 101.6705,
    opening_hours: { daily: "7am-10pm" },
    price_range: "$",
    what_to_order: [
      "Nyonya laksa — rich coconut curry broth, among the best in KL",
      "Crispy pai tee — thin pastry cups filled with jicama, omelette, cucumber",
      "Nyonya cendol — coconut milk, gula melaka, shaved ice, green jelly",
      "Mee siam (RM7.80) — tangy rice vermicelli",
      "Ikan goreng sambal — fried fish with spicy sambal",
    ],
    pro_tips: [
      "Simple, no-frills Nyonya home cooking — don't expect fancy decor",
      "Fast service and very affordable — great value for authentic Peranakan food",
      "Lunch crowd is locals from the Bangsar area — good sign",
      "In Bangsar, not Chinatown — easy to combine with Bangsar bar hopping later",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Chocha Foodstore",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["dinner"],
    address: "156, Jalan Petaling, City Centre, 50000 Kuala Lumpur",
    latitude: 3.1441,
    longitude: 101.6968,
    opening_hours: { "tue-sun": "11am-11pm", closed: "Monday" },
    price_range: "$$",
    what_to_order: [
      "Slow-cooked and grilled goat rack — Borneo-inspired, tender and flavourful",
      "Heirloom red rice bowl — earthy, nutty, uniquely Malaysian",
      "Slow-cooked eggplant and grilled beans — simple but beautifully done",
      "Natural wine pairing — they have a curated selection",
      "Any seasonal special — menu changes with local ingredient availability",
    ],
    what_to_skip: ["Skip if you want quick hawker food — this is a sit-down experience"],
    pro_tips: [
      "Hidden inside the old Mah Lian Hotel on Petaling Street — look for the entrance",
      "Modern Malaysian cuisine with Borneo influences — not your typical Chinatown fare",
      "Locally sourced, sustainability-focused — every dish respects the ingredients",
      "Beautiful restored heritage building — Instagram-worthy interior",
      "Combine with Petaling Street exploration and PS150 cocktail bar nearby",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Limapulo: Baba Can Cook",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chow Kit",
    categories: ["lunch"],
    address: "50, Jalan Doraisamy, Chow Kit, 50300 Kuala Lumpur",
    latitude: 3.1548,
    longitude: 101.6952,
    opening_hours: { "mon-wed": "11:30am-3pm", "thu-sat": "11:30am-3pm, 5:30pm-9pm", closed: "Sunday" },
    price_range: "$",
    what_to_order: [
      "Nyonya laksa — won Best Curry Laksa award, only served Mon/Wed/Fri",
      "Nyonya pie tee (RM10 for 4) — crispy pastry cups with jicama filling",
      "Ayam berempah (RM17) — chicken in aromatic Nyonya spices",
      "Pineapple prawns curry — sweet, tangy, rich coconut gravy",
      "Satay with homemade star fruit and pineapple sauce — unique to Limapulo",
    ],
    what_to_skip: ["Don't come Sunday — closed"],
    pro_tips: [
      "Michelin Guide recommended (2023-2025) — legit world-class Nyonya food",
      "Uncle John (Chef Tan Kim Chye) runs the kitchen with his mother's secret recipes",
      "The laksa is ONLY available Mon/Wed/Fri — plan your visit accordingly",
      "Small intimate space with home-kitchen feel — feels like eating at someone's house",
      "Located at The Row on Jalan Doraisamy — combine with exploring the heritage shophouses",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Ramly Burger",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["dinner"],
    address: "Street stalls across KL — try near Jalan Alor or any pasar malam",
    latitude: 3.146,
    longitude: 101.708,
    opening_hours: { daily: "6pm-2am" },
    price_range: "$",
    what_to_order: [
      "Master Burger — double patty with egg wrap, cheese, and all the sauces",
      "Burger kahwin — one chicken + one beef patty combined in one burger",
      "Chicken burger special — with egg, cheese, lettuce, and Maggi seasoning",
      "Add extra egg wrap and cheese — the egg-wrapped patty is the signature move",
    ],
    what_to_skip: ["Skip the fish burger — chicken and beef are the stars"],
    pro_tips: [
      "Malaysia's iconic street burger — patty wrapped in egg omelette is the defining feature",
      "Cash only, RM5-10 per burger — genuinely cheap late-night food",
      "Best stalls: Brader John Burger, Om Burger (Ampang, since 1986), Zam Burger",
      "Best eaten late night after a night out — this is Malaysia's version of 2am pizza",
      "Every pasar malam (night market) has at least one Ramly stall — just follow the smoke",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
  },
  {
    name: "Bean Brothers",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Mont Kiara",
    categories: ["cafe"],
    address: "Shoplot 7, Vista Kiara, Jalan Kiara 3, Mont Kiara, 50480 Kuala Lumpur",
    latitude: 3.1701,
    longitude: 101.654,
    opening_hours: { daily: "8:30am-8pm" },
    price_range: "$$",
    what_to_order: [
      "Any single-origin pour over — they roast their own beans",
      "Flat white — their signature, well-balanced and smooth",
      "Kitchen brunch items (served until 5pm) — solid cafe food",
      "Cold brew on a hot KL afternoon",
    ],
    pro_tips: [
      "Serious specialty coffee with industrial-rustic vibes — bare ceilings, bulbs, wood, steel, and plants",
      "Good for a quiet work session — laptop-friendly with Wi-Fi",
      "Mont Kiara location is the neighbourhood cafe vibe — expat-friendly area",
      "Also has a branch at The Linc on Jalan Tun Razak if Mont Kiara is too far",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Breakfast Thieves",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["cafe"],
    address: "Lot M, 29-5 Jalan Riong, Bangsar, 59100 Kuala Lumpur",
    latitude: 3.128,
    longitude: 101.672,
    opening_hours: { "tue-sun": "9am-5pm (kitchen closes 4pm)", closed: "Monday" },
    price_range: "$$",
    what_to_order: [
      "Mr. Terry Benedict (RM29) — 24hr slow-braised beef cheeks, poached eggs, yuzu hollandaise on toast",
      "Kampung Eggs Your Way (RM14) — poached, fried, or scrambled on sourdough",
      "My French Lady French Toast (RM26) — their take on the classic",
      "Gypsy King Polenta Bars (RM29)",
      "Any coffee — they take it seriously",
    ],
    what_to_skip: ["Don't come after 4pm — kitchen closes, only drinks left"],
    pro_tips: [
      "Modern Australian brunch with Asian influences — KL's best brunch spot",
      "Always packed on weekends — go before 10am or prepare to wait",
      "Located in APW Bangsar creative complex — artsy neighbourhood vibe",
      "Simple menu but every dish is well-executed in taste and presentation",
      "Closed Mondays — plan accordingly",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "The Row",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chow Kit",
    categories: ["activity"],
    address: "Jalan Doraisamy, 50300 Kuala Lumpur",
    latitude: 3.1548,
    longitude: 101.6945,
    opening_hours: { daily: "10am-10pm (varies by outlet)" },
    price_range: "$$",
    what_to_order: [
      "Explore the 22 restored 1940s heritage shophouses — cafes, restaurants, galleries",
      "Heritage Pizza — wood-fired pizzas in a heritage setting",
      "Common Grind cafe — English cottage vibes, good for an afternoon hangout",
      "Kwong Cheung Loong — kopitiam by day, oriental bar by night",
      "Check what's on at Slate events space — art exhibitions, music gigs, talks",
    ],
    what_to_skip: ["Skip MOJO if you're on a budget — it's pricier for what you get"],
    pro_tips: [
      "22 restored 1940s shophouses — KL's most charming heritage strip",
      "5-min walk from Dang Wangi LRT or Medan Tuanku Monorail",
      "Home to Limapulo (Nyonya food) and Restaurant Dominic (French) — serious dining options",
      "Go late afternoon for golden hour light on the heritage facades",
      "The Slate events space hosts regular art exhibitions, gigs, and talks — check their Instagram",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
  },
  {
    name: "Bukit Tabur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Taman Melawati",
    categories: ["activity"],
    address: "Taman Melawati, 53100 Kuala Lumpur (near Klang Gates Dam)",
    latitude: 3.238,
    longitude: 101.753,
    opening_hours: { "thu,sat,sun,public holidays": "8:30am-5pm" },
    price_range: "$",
    what_to_order: [
      "West trail for first-timers — better scenery, slightly easier",
      "East trail for experienced hikers — more challenging with steeper rock scrambles",
      "Sunrise hike (start 5am) — the views over KL at dawn are spectacular",
      "Bring 1.5L water minimum — no shops on the trail",
    ],
    what_to_skip: ["Do NOT hike after rain — quartz rock gets extremely slippery and dangerous"],
    pro_tips: [
      "World's longest quartz ridge (14km) — genuinely dramatic, Instagram-worthy scenery",
      "PERMIT REQUIRED — get it from Forestry Department in Cheras (weekdays only, plan ahead)",
      "Only open Thu/Sat/Sun/public holidays — no hiking other days",
      "Wear good shoes and bring gloves — involves actual rock scrambling",
      "3-4 hour hike to about 500m elevation — moderate to challenging difficulty",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
  },
  {
    name: "REXKL",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["activity"],
    address: "80, Jalan Sultan, City Centre, 50000 Kuala Lumpur",
    latitude: 3.1445,
    longitude: 101.6975,
    opening_hours: { "mon-thu": "8:30am-10pm", "fri-sun": "8:30am-12am" },
    price_range: "$",
    what_to_order: [
      "Browse the BookXcess labyrinth bookstore — towering maze-like bookshelves, great for photos",
      "Food Fiction food hall — emerging KL food entrepreneurs under one roof",
      "Stellar Coffee — solid specialty coffee in the complex",
      "Check the events calendar — documentary screenings, art exhibitions, live music",
      "Digital art gallery (RM40 locals, RM60 tourists) — immersive experience",
    ],
    what_to_skip: ["Skip the digital gallery if you're short on time — the free areas are the real draw"],
    pro_tips: [
      "Repurposed 1947 cinema — one of Malaysia's first theatres, now a cultural hub",
      "The BookXcess bookstore alone is worth the visit — labyrinthine shelves, great prices",
      "Free to enter (gallery is extra) — perfect rainy day activity in Chinatown",
      "Open late on weekends (until midnight) — good evening hangout option",
      "Combine with Petaling Street, Chocha Foodstore, and PS150 — all walking distance",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },

  // ============================================
  // NEW BATCH — STREET FOOD & HAWKER
  // ============================================
  {
    name: "Imbi Pork Noodles",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Imbi",
    categories: ["breakfast"],
    address: "183, Jalan Imbi, 55100 Kuala Lumpur",
    latitude: 3.1458,
    longitude: 101.7116,
    price_range: "$",
    what_to_order: ["Pork ball noodles with extra sausage", "Sam kan chong dry noodles"],
    what_to_skip: ["Don't order rice dishes — this is a noodle stall"],
    pro_tips: [
      "55-year-old stall inside Restoran Win Heng Seng kopitiam",
      "Opens 6am, sells out by early afternoon",
      "Choose between kuey teow, lou shi fun, mee hun, or mee",
      "Cash only — no exceptions",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "6am-3pm" },
  },
  {
    name: "Heun Kee Claypot Chicken Rice",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Pudu",
    categories: ["lunch"],
    address: "59 Jalan Yew, Pudu, 55100 Kuala Lumpur",
    latitude: 3.1368,
    longitude: 101.7088,
    price_range: "$",
    what_to_order: ["Claypot chicken rice (medium for 2)", "Add salted fish and Chinese sausage"],
    pro_tips: [
      "Michelin Bib Gourmand — charcoal-fired claypot is the real deal",
      "Each pot takes 30-45 minutes — order and be patient",
      "The crispy burnt rice at the bottom (guo ba) is the best part",
      "Closed Thursdays",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-wed,fri-sun": "11am-9pm", closed: "Thursday" },
  },
  {
    name: "Hon Kee Porridge",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Petaling Street",
    categories: ["breakfast"],
    address: "93, Jalan Hang Lekir, 50000 Kuala Lumpur",
    latitude: 3.1447,
    longitude: 101.6968,
    price_range: "$",
    what_to_order: ["Raw fish porridge", "Century egg porridge", "Mixed porridge"],
    pro_tips: [
      "Since 1949, now third generation — a Chinatown institution",
      "Opens at 4am — serious early birds only",
      "The raw fish porridge is silky smooth, fish cooked by the hot congee",
      "Cash only",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "4am-2:30pm" },
  },
  {
    name: "Koon Kee Wan Tan Mee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Petaling Street",
    categories: ["lunch"],
    address: "95, Jalan Hang Lekir, 50000 Kuala Lumpur",
    latitude: 3.1446,
    longitude: 101.6967,
    price_range: "$",
    what_to_order: ["Dry wantan mee with char siu", "Wonton soup on the side"],
    pro_tips: [
      "Springy handmade noodles — the benchmark for KL-style wantan mee",
      "Opens till 2:30am — perfect supper spot",
      "Right next to Hon Kee Porridge — do a Chinatown combo",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-2:30am" },
  },
  {
    name: "Wong Mei Kee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Pudu",
    categories: ["lunch"],
    address: "30 Jalan Nyonya, Pudu, Kuala Lumpur",
    latitude: 3.1352,
    longitude: 101.7089,
    price_range: "$",
    what_to_order: ["Siu yuk (roast pork belly)", "Char siu rice", "Three-combination rice"],
    pro_tips: [
      "Michelin Bib Gourmand — charcoal-roasted pork with impossibly crispy skin",
      "Only open 12pm-3pm, sells out fast — arrive before noon",
      "The siu yuk is the star — skin cracks like glass",
      "Cash only, no frills, legendary",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "12pm-3pm", closed: "Monday" },
  },
  {
    name: "Under the Bridge Chicken Rice",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kepong",
    categories: ["lunch"],
    address: "1175, Jalan Kanan, Desa Jaya Kepong, 52100 Kuala Lumpur",
    latitude: 3.2105,
    longitude: 101.6365,
    price_range: "$",
    what_to_order: ["Hainan chicken rice", "Roast chicken rice"],
    pro_tips: [
      "Hidden under the highway bridge — locals-only vibe",
      "Tender chicken with ginger-garlic-scallion sauce",
      "Cash only, sells out by early afternoon",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { daily: "10am-3pm" },
  },
  {
    name: "Hai Kah Lang",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Cheras",
    categories: ["lunch"],
    address: "44 Jalan Kaskas 2, Taman Cheras, 56100 Kuala Lumpur",
    latitude: 3.1065,
    longitude: 101.7421,
    price_range: "$$",
    what_to_order: ["Seafood noodle soup", "Fish head noodle", "Mixed seafood platter"],
    pro_tips: [
      "Michelin-approved — the Taman Cheras OG branch is the one to visit",
      "Always packed — go slightly off-peak or queue",
      "The seafood noodle broth is incredibly rich and fresh",
      "Multiple branches now but Cheras original has the most character",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "8am-2am" },
  },
  {
    name: "Yulek Wan Tan Mee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Cheras",
    categories: ["breakfast"],
    address: "19, Lorong Durian, Taman Cheras, 56100 Kuala Lumpur",
    latitude: 3.1055,
    longitude: 101.7445,
    price_range: "$",
    what_to_order: ["Dry wantan mee with char siu", "Extra char siu portion"],
    pro_tips: [
      "The char siu here is legendary — caramelized, sweet, juicy",
      "Opens 7:30am, closed Wednesdays",
      "Cash only, no frills, been around for decades",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "wed-mon": "7:30am-4pm", closed: "Tuesday" },
  },
  {
    name: "Zheng Kee Chicken Rice",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Segambut",
    categories: ["lunch"],
    address: "No 19, Jalan 17/42, Taman Kok Doh, 51200 Kuala Lumpur",
    latitude: 3.1928,
    longitude: 101.6672,
    price_range: "$",
    what_to_order: ["Hainan chicken rice", "White chicken (half)"],
    pro_tips: [
      "40+ years in business — one of KL's best kept chicken rice secrets",
      "Closed Friday — plan accordingly",
      "Hidden in Taman Kok Doh hawker area between Segambut and Jinjang",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { "sat-thu": "10am-3pm", closed: "Friday" },
  },
  {
    name: "Uncle Keong Noodle Stall",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Old Klang Road",
    categories: ["breakfast"],
    address: "Lorong Jurga, Old Klang Road, 58100 Kuala Lumpur",
    latitude: 3.1092,
    longitude: 101.6741,
    price_range: "$",
    what_to_order: ["Curry mee (Mon/Thu/Fri only)", "Prawn mee", "Wan tan mee", "Fried wonton"],
    pro_tips: [
      "40+ years old, roadside stall surrounded by trees — a hidden gem",
      "Curry laksa mee only available Monday, Thursday, Friday",
      "Closed Tuesday — don't make the trip for nothing",
      "Feel like eating in the jungle — nature vibes in the city",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { "mon,wed-sun": "7:30am-2:30pm", closed: "Tuesday" },
  },
  {
    name: "Song Lim Restaurant",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Pudu",
    categories: ["dinner"],
    address: "No 3, Persiaran Jubilee, Off Jalan Loke Yew, 55200 Kuala Lumpur",
    latitude: 3.1322,
    longitude: 101.7112,
    price_range: "$",
    what_to_order: ["Butter lou shi fun", "Dark beer sauce chicken", "Hainan noodle"],
    pro_tips: [
      "Classic dai chow (Chinese cook-to-order) — the butter lou shi fun is legendary",
      "Closed Tuesday",
      "Parking is tough on weekdays — arrive early",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon,wed-sun": "11am-10pm", closed: "Tuesday" },
  },
  {
    name: "Da Cheng Lok Lok",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Petaling",
    categories: ["dinner"],
    address: "Jalan Radin Bagus 3, Bandar Baru Sri Petaling, 57000 Kuala Lumpur",
    latitude: 3.0697,
    longitude: 101.6929,
    price_range: "$",
    what_to_order: ["Satay sticks", "Seafood skewers", "Lok lok combo platter"],
    pro_tips: [
      "Sri Petaling's go-to for late-night lok lok (pick-your-own skewer hotpot)",
      "Open 6:30pm-1:30am — perfect supper spot",
      "Dip everything in their signature satay peanut sauce",
      "Closed Mondays and Fridays",
    ],
    vibe: "chaotic",
    best_time_of_day: "night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { "sun,tue-thu": "6:30pm-1:30am", closed: "Monday, Friday" },
  },
  {
    name: "Little Jungle Coffee House",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kuchai Lama",
    categories: ["breakfast"],
    address: "79, Jalan Rukun 4, Taman Gembira, 58200 Kuala Lumpur",
    latitude: 3.0981,
    longitude: 101.6835,
    price_range: "$",
    what_to_order: ["Curry mee", "Pork noodles", "Kopi"],
    pro_tips: [
      "Kopitiam tucked in a green residential area — feels like a secret garden",
      "The curry mee is tasty with rich coconut broth",
      "Closed Thursdays",
      "Opens 8am-3pm, coffee-shop vibe",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { "fri-wed": "8am-3pm", closed: "Thursday" },
  },
  {
    name: "Annuar's Fish Head Curry",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "Lorong Ara Kiri 3, Lucky Garden, Bangsar, 59100 Kuala Lumpur",
    latitude: 3.1262,
    longitude: 101.6718,
    price_range: "$",
    what_to_order: ["Fish head curry", "Apam balik"],
    pro_tips: [
      "A Bangsar institution — now operates from a food truck near Lucky Garden",
      "Rich, spicy fish head curry with okra and eggplant",
      "Cash only, closes when sold out, closed Sundays",
      "The nearby Indian apam stall is worth a combo visit",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    opening_hours: { "mon-sat": "9:30am-5pm", closed: "Sunday" },
  },

  // ============================================
  // NEW BATCH — RESTAURANTS
  // ============================================
  {
    name: "Nero Nero",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Damansara Heights",
    categories: ["dinner"],
    address: "L3-02, DC Mall, Damansara City, 6 Jalan Damanlela, 50490 Kuala Lumpur",
    latitude: 3.1475,
    longitude: 101.6598,
    price_range: "$$$",
    what_to_order: ["Handmade pasta (any)", "Wood-fired Napoli pizza", "Burrata"],
    pro_tips: [
      "Southern Italian (Puglia influence) — KL institution since 2017",
      "Pasta is handmade and cooked-to-order, expect a short wait",
      "Book ahead on weekends — always full",
      "Sunday is brunch + dinner only (12-3pm, 6-10pm)",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-sat": "12pm-10:30pm", sunday: "12pm-3pm, 6pm-10pm" },
  },
  {
    name: "Village Roast Duck",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "1, Jalan Telawi 1, Bangsar Baru, 59100 Kuala Lumpur",
    latitude: 3.1306,
    longitude: 101.6710,
    price_range: "$$",
    what_to_order: ["Roast duck", "Siu yuk (roast pork)", "Char siu", "Three-combo rice"],
    pro_tips: [
      "Best roast duck in KL — crispy skin, juicy meat",
      "Bangsar branch is the OG, also at Pavilion",
      "Go early for lunch — roast duck sells out",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-10pm" },
  },
  {
    name: "Ganga Cafe",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "19 Lorong Kurau, Bangsar, 59100 Kuala Lumpur",
    latitude: 3.1287,
    longitude: 101.6727,
    price_range: "$$",
    what_to_order: ["Dosa", "Gujarati thali", "Masala chai"],
    pro_tips: [
      "Pure vegetarian Gujarati cuisine — no MSG, no artificial colouring",
      "Vegan, Jain, and Buddhist options available",
      "Closed Tuesdays",
      "Beautiful garden-like setting in Bangsar",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { "mon,wed-fri": "10:30am-10pm", "sat-sun": "9am-10pm", closed: "Tuesday" },
  },
  {
    name: "Olivia Deli",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["dinner"],
    address: "29, Jalan Riong, Lot B03, APW Bangsar, 59100 Kuala Lumpur",
    latitude: 3.1222,
    longitude: 101.6721,
    price_range: "$$",
    what_to_order: ["Suckling pig empanada", "Gazpacho", "Bife a Portuguesa", "Truffle mushroom risotto"],
    pro_tips: [
      "Southern European deli at APW Bangsar — Spanish/Portuguese vibes",
      "Great for tapas and wine evening",
      "Shelves stocked with Mediterranean products you can buy",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "11am-12am", closed: "Monday" },
  },
  {
    name: "Alta Pizza",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["dinner"],
    address: "38, Jalan Kemuja, Bukit Bangsar, 59000 Kuala Lumpur",
    latitude: 3.1278,
    longitude: 101.6739,
    price_range: "$$",
    what_to_order: ["Margherita pizza", "Truffle pizza", "Handmade pasta"],
    pro_tips: [
      "Pork-free Italian-ish pizzeria in the heart of Bangsar",
      "Great for a casual dinner with friends",
      "Closed Monday",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "12pm-11pm", closed: "Monday" },
  },
  {
    name: "Wurst",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["dinner"],
    address: "15-G, Persiaran Ara Kiri, Bangsar, 59100 Kuala Lumpur",
    latitude: 3.1265,
    longitude: 101.6718,
    price_range: "$$",
    what_to_order: ["Homemade bratwurst", "Artisanal sausage platter", "Hanger steak"],
    pro_tips: [
      "Homemade sausages — nitrate-free, gluten-free, no preservatives",
      "European deli vibes in Lucky Garden, Bangsar",
      "Great craft beer selection to pair with sausages",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-11pm" },
  },
  {
    name: "Boys Don't Fry",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["lunch"],
    address: "17, Lorong Kurau, Bangsar, 59100 Kuala Lumpur",
    latitude: 3.1287,
    longitude: 101.6726,
    price_range: "$$",
    what_to_order: ["Fish and chips (the perch)", "Breakfast butty"],
    pro_tips: [
      "British Kopitiam concept — best fish and chips in KL",
      "Pork-free, halal-friendly",
      "Also has a branch at Wisma Cosway",
      "Small spot, gets busy at lunch",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-sat": "9am-5pm", closed: "Sunday" },
  },
  {
    name: "Asylum Coffeehouse",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar",
    categories: ["cafe"],
    address: "28, Jalan Kemuja, Bangsar, 59000 Kuala Lumpur",
    latitude: 3.1278,
    longitude: 101.6738,
    price_range: "$$",
    what_to_order: ["Filter coffee", "Flat white", "Pastries"],
    pro_tips: [
      "Singapore's famous Asylum Coffeehouse — first Malaysian outpost",
      "Specialty coffee focus, great beans",
      "Opens 8am-4:30pm daily",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "8am-4:30pm" },
  },
  {
    name: "Hanam BBQ",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bamboo Hills",
    categories: ["dinner"],
    address: "P1-2, Bamboo Hills, Off Lebuhraya Duta-Ulu Kelang, Taman Bamboo, Kuala Lumpur",
    latitude: 3.1778,
    longitude: 101.6892,
    price_range: "$$",
    what_to_order: ["Samgyeopsal (pork belly)", "Galmealgiksal (skirt meat)", "Set menu for value"],
    what_to_skip: ["Skip ala carte if budget-conscious — sets are much better value"],
    pro_tips: [
      "Non-halal Korean BBQ with proper cuts and banchan",
      "The wild garlic leaves (san-man nuel) wrap is a must",
      "Book ahead — always packed on weekends",
      "Multiple locations but Bamboo Hills is the flagship",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11:30am-3:30pm, 5:30pm-10:30pm" },
  },
  {
    name: "Po Cha Korean Restaurant",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Ampang",
    categories: ["dinner"],
    address: "15, Jalan Sulaiman 3, Taman Putra Sulaiman, Ampang",
    latitude: 3.1512,
    longitude: 101.7612,
    price_range: "$$",
    what_to_order: ["Seafood pajeon", "Army stew", "Stewed mackerel soup", "Soju"],
    pro_tips: [
      "Run by an old Korean couple — proper homestyle Korean cooking",
      "Opens 6pm-4am — peak Korean night-out hours",
      "Advance reservation highly recommended",
      "Handwritten menu, authentic vibe",
    ],
    vibe: "local",
    best_time_of_day: "night",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "6pm-4am" },
  },
  {
    name: "Yoshinari",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Hartamas",
    categories: ["dinner"],
    address: "A-00-11, Plaza Damas 3, 63, Jalan Sri Hartamas 1, 50480 Kuala Lumpur",
    latitude: 3.1625,
    longitude: 101.6578,
    price_range: "$$",
    what_to_order: ["Omakase Sushi Course (RM150++)", "Dashi Course (RM80++)"],
    pro_tips: [
      "Best value omakase in KL — 9 pieces of sushi, sashimi, seasonal dishes for RM150",
      "Only 8 counter seats — intimate, personal experience",
      "Dashi Course changes monthly — seasonal Japanese vegetables and fish",
      "Book well in advance",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "12pm-2:30pm, 6pm-10pm" },
  },
  {
    name: "Lee Ga Korean Noodles",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Hartamas",
    categories: ["lunch"],
    address: "34G, Jalan 27/70a, Desa Sri Hartamas, 50480 Kuala Lumpur",
    latitude: 3.1621,
    longitude: 101.6571,
    price_range: "$$",
    what_to_order: ["Naengmyeon (cold noodles)", "Sundae gukbap (blood sausage soup)", "Suyuk (boiled pork)"],
    pro_tips: [
      "Specialises in North Korean-style cold noodles — rare in KL",
      "Naengmyeon is refreshing and perfect for KL's heat",
      "Closed Tuesdays",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon,wed-sun": "9:30am-3pm, 5pm-9pm", closed: "Tuesday" },
  },
  {
    name: "Busan ZIP",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Hartamas",
    categories: ["dinner"],
    address: "23-G, Jalan 26/70a, Desa Sri Hartamas, 50480 Kuala Lumpur",
    latitude: 3.1618,
    longitude: 101.6568,
    price_range: "$$",
    what_to_order: ["Jjukkumi (webfoot octopus)", "Haemul tang (seafood stew)"],
    pro_tips: [
      "Busan-style Korean seafood — layered with perilla leaf, radish, dried seaweed",
      "Pork-free",
      "Closed Tuesdays",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon,wed-sun": "11am-3pm, 5pm-11pm", closed: "Tuesday" },
  },
  {
    name: "Bistro Léa",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Hartamas",
    categories: ["dinner"],
    address: "1, Jalan Sri Hartamas 7, Taman Sri Hartamas, 50480 Kuala Lumpur",
    latitude: 3.1635,
    longitude: 101.6565,
    price_range: "$$$",
    what_to_order: ["Boeuf bourguignon", "Soupe à l'oignon", "Ratatouille", "Weekday lunch set (RM69-89)"],
    pro_tips: [
      "Casual French bistro by chef KaHong Lau (of Atelier Binchotan)",
      "Pork-free menu — Parisian bistro classics done right",
      "Weekday lunch course is excellent value at RM69/2-course",
      "Closed Mondays",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-fri": "12pm-3pm, 6pm-11pm", "sat-sun": "9am-11pm", closed: "Monday" },
  },
  {
    name: "Burnin' Pit",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Hartamas",
    categories: ["dinner"],
    address: "24, Jalan 24/70a, Desa Sri Hartamas, 50480 Kuala Lumpur",
    latitude: 3.1619,
    longitude: 101.6562,
    price_range: "$$",
    what_to_order: ["Smoked brisket", "Pulled pork", "Beef ribs", "Mac and cheese"],
    pro_tips: [
      "Low-and-slow American BBQ — proper smoker, not just a grill",
      "Open late on weekends (till 2am Fri-Sat)",
      "Good craft beer selection",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "sun-thu": "12pm-1am", "fri-sat": "12pm-2am" },
  },
  {
    name: "Limapulo",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chow Kit",
    categories: ["lunch"],
    address: "50, Jalan Doraisamy, Chow Kit, 50300 Kuala Lumpur",
    latitude: 3.1555,
    longitude: 101.6972,
    price_range: "$$",
    what_to_order: ["Nyonya laksa lemak", "Pai tee (top hat appetiser)", "Nyonya satay"],
    pro_tips: [
      "Michelin-listed Peranakan restaurant — voted best curry laksa in Klang Valley",
      "The laksa lemak is rich, creamy, deeply flavorful",
      "Also has a second location at Tong Shin Terrace",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-9pm" },
  },
  {
    name: "Five Guys",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["lunch"],
    address: "Lot C3.06.01, Level 3, Pavilion KL, 168, Jalan Bukit Bintang, 55100 Kuala Lumpur",
    latitude: 3.1488,
    longitude: 101.7134,
    price_range: "$$",
    what_to_order: ["Cheeseburger (all the way)", "Cajun fries", "Milkshake"],
    pro_tips: [
      "The American burger chain — same quality as the US originals",
      "Fries are generous, share a regular",
      "Also at Pavilion Damansara Heights and Genting",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-10pm" },
  },
  {
    name: "Raijin Ramen",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["lunch"],
    address: "80, Jalan Sultan, City Centre, 50000 Kuala Lumpur",
    latitude: 3.1438,
    longitude: 101.6976,
    price_range: "$$",
    what_to_order: ["Kuro ramen (black garlic)", "Shoyu ramen", "Gyoza"],
    pro_tips: [
      "Hidden inside REXKL — the converted cinema cultural hub",
      "Rich, flavourful tonkotsu broth",
      "Combine with BookXcess browsing upstairs",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-9pm" },
  },
  {
    name: "Takeen Omakase",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Old Klang Road",
    categories: ["dinner"],
    address: "Lot 5-G, Lorong 4/137C, Batu 5, Off Jalan Klang Lama, 58000 Kuala Lumpur",
    latitude: 3.1058,
    longitude: 101.6694,
    price_range: "$$$",
    what_to_order: ["Kappo dinner course (from RM488)", "Lunch course (from RM238)", "Wagyu course (RM688)"],
    pro_tips: [
      "Award-winning Japanese Kappo omakase hidden on Old Klang Road",
      "More cooked dishes than typical omakase — kappo style",
      "5 private rooms available for groups",
      "Reservations required",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "12pm-2:30pm, 6pm-10:30pm" },
  },
  {
    name: "Kimi-Ya Japanese Restaurant",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Old Klang Road",
    categories: ["dinner"],
    address: "G-2, Avantas Residences, 162, Jalan Klang Lama, 58000 Kuala Lumpur",
    latitude: 3.1062,
    longitude: 101.6712,
    price_range: "$$",
    what_to_order: ["Sashimi platter", "Grilled items", "Ramen"],
    pro_tips: [
      "Modern Japanese dining on OKR — consistent quality",
      "Good lunch sets for value",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-thu": "12pm-3pm, 6pm-10:30pm", "fri-sun": "11:30am-3pm, 6pm-11pm" },
  },
  {
    name: "Yamatatsu",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Old Klang Road",
    categories: ["dinner"],
    address: "30, Jalan 2/131A, Project Jaya Industrial Estate, Batu 6, Old Klang Road",
    latitude: 3.0985,
    longitude: 101.6595,
    price_range: "$",
    what_to_order: ["Taiwanese mee suah (RM10)", "Saba mackerel rice bowl (RM23)", "House pickles"],
    pro_tips: [
      "Japanese-Taiwanese fusion izakaya in an old industrial estate",
      "Started as a pop-up at KongsiKL — intimate, quirky setting",
      "Closed Thursdays",
      "Try the Witchy Wine — pickled tomato with umeshu plum wine",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-wed,fri-sun": "12pm-3pm, 6pm-10pm", closed: "Thursday" },
  },
  {
    name: "Teppan Sakaba",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Taman Desa",
    categories: ["dinner"],
    address: "Lot G13, Faber Towers, Jalan Desa Bahagia, Taman Desa, 58100 Kuala Lumpur",
    latitude: 3.1065,
    longitude: 101.6782,
    price_range: "$$",
    what_to_order: ["Teppanyaki items", "Yakitori skewers", "Japanese curry rice"],
    pro_tips: [
      "Affordable Japanese izakaya with live teppanyaki cooking",
      "Part of the Izakaya Group — reliable quality",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "12pm-3pm, 6pm-11pm" },
  },
  {
    name: "Talk Crab",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Kepong",
    categories: ["dinner"],
    address: "11, Jalan 15, Taman Desa Jaya, Kepong, 52100 Kuala Lumpur",
    latitude: 3.2045,
    longitude: 101.6365,
    price_range: "$$$",
    what_to_order: ["Roe-filled crabs", "Butter crab", "Salted egg crab"],
    pro_tips: [
      "Crab specialist — they source roe-filled crustaceans",
      "Closed Mondays",
      "Book ahead, especially on weekends",
      "Also has branches in other locations",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "12pm-3pm, 5pm-10pm", closed: "Monday" },
  },
  {
    name: "Haruki Japanese Restaurant",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sri Petaling",
    categories: ["dinner"],
    address: "10-G, Jalan 14/149l, Bandar Baru Sri Petaling, 57000 Kuala Lumpur",
    latitude: 3.0695,
    longitude: 101.6925,
    price_range: "$$",
    what_to_order: ["Sashimi", "Grilled fish", "Ramen"],
    pro_tips: [
      "Neighbourhood Japanese restaurant in Sri Petaling",
      "Solid quality without the city-centre price tag",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },

  // ============================================
  // NEW BATCH — CAFES & SPECIALTY
  // ============================================
  {
    name: "Curio Coffee Roaster & Cafe",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sentul",
    categories: ["cafe"],
    address: "Lot 468, G26-A, Block G, Rivercity Roof Top, Jalan Sultan Azlan Shah, 51200 Kuala Lumpur",
    latitude: 3.1822,
    longitude: 101.6895,
    price_range: "$$",
    what_to_order: ["Pour-over coffee", "House blend espresso", "Pastries"],
    pro_tips: [
      "In-house roasting room — beans roasted on-site",
      "Small, cozy spot with natural light — Japanese aesthetics",
      "Closed Mondays",
      "They also do yoga sessions — check their schedule",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "9am-6:30pm", closed: "Monday" },
  },
  {
    name: "Dough by Meg",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Ceylon",
    categories: ["cafe"],
    address: "9C, Jalan Ceylon, Bukit Ceylon, 50200 Kuala Lumpur",
    latitude: 3.1508,
    longitude: 101.7128,
    price_range: "$$",
    what_to_order: ["Bomboloni (Italian doughnuts)", "Cruffin", "Coffee"],
    pro_tips: [
      "One of the best bomboloni in KL — freshly fried, cream-filled",
      "Small space, limited seating — grab and go if busy",
      "Also at Society Mont Kiara now",
    ],
    vibe: "casual",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Monograph Cafe & Dining",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["cafe"],
    address: "181-A (1st Floor), Jalan Tun H S Lee, City Centre, 50000 Kuala Lumpur",
    latitude: 3.1445,
    longitude: 101.6972,
    price_range: "$$",
    what_to_order: ["Matcha latte", "Fusion brunch plates", "Coffee"],
    pro_tips: [
      "By the founders of Niko Neko Matcha — expect excellent matcha",
      "Minimalist, beautiful interior near Pasar Seni",
      "Contemporary fusion menu for brunch",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Ebony & Ivory Coffee",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Cheras",
    categories: ["cafe"],
    address: "No. 4A, Jalan Kaskas 4, Taman Cheras, 56100 Kuala Lumpur",
    latitude: 3.1068,
    longitude: 101.7425,
    price_range: "$$",
    what_to_order: ["Pour-over coffee", "Cake of the day", "Brunch plate"],
    pro_tips: [
      "Cozy Cheras neighbourhood cafe — good specialty coffee",
      "Opens 10am-6pm only",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "10am-6pm" },
  },
  {
    name: "IF ONLY",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "U-Thant",
    categories: ["cafe"],
    address: "Ground Floor, Regal House, 1, Jalan U Thant, 55000 Kuala Lumpur",
    latitude: 3.1595,
    longitude: 101.7215,
    price_range: "$$",
    what_to_order: ["Breakfast plate", "Coffee", "Brunch dishes"],
    pro_tips: [
      "Sustainability-committed modern Australian cafe — beautiful space",
      "Opens 7am — great early morning option",
      "Closed Mondays, Sunday till 6pm only",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { "tue-sat": "7am-11pm", sunday: "7am-6pm", closed: "Monday" },
  },
  {
    name: "Licky Chan & The Poke Guy",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chow Kit",
    categories: ["cafe"],
    address: "24, Jalan Yap Ah Shak, Chow Kit, 50300 Kuala Lumpur",
    latitude: 3.1568,
    longitude: 101.6975,
    price_range: "$$",
    what_to_order: ["Boozy ice cream", "Poke bowl", "Espresso"],
    pro_tips: [
      "Ice cream shop meets tattoo parlour — quirky combo",
      "Alcohol-infused ice cream is the signature",
      "Open till midnight — good late-night sweet fix",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "12pm-12am" },
  },
  {
    name: "Bartolo Lisboa Bakehouse",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Chinatown",
    categories: ["cafe"],
    address: "Mezzanine Floor, Central Market Annexe, Jalan Hang Kasturi, 50050 Kuala Lumpur",
    latitude: 3.1452,
    longitude: 101.6956,
    price_range: "$$",
    what_to_order: ["Pastel de nata (Portuguese egg tart)", "Coffee", "Portuguese baked goods"],
    pro_tips: [
      "Portuguese bakehouse in the Central Market Annexe",
      "Bright, airy space above the river",
      "Great pastries — the pastel de nata rivals Lisbon's",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "La Spiga D'Oro",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bangsar South",
    categories: ["cafe"],
    address: "1-G-5, Pantai Panorama Condo, Jalan 112H, Off Jalan Kerinchi, 59200 Kuala Lumpur",
    latitude: 3.1128,
    longitude: 101.6672,
    price_range: "$$",
    what_to_order: ["Italian sandwich (any)", "Focaccia", "Espresso"],
    pro_tips: [
      "Hidden inside a condo — legit Italian sandwiches, no signage",
      "Closes when sold out — arrive before noon",
      "Tiny space, most people take away",
      "Closed Sunday and Monday",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sat": "10:30am-1pm (or sold out)", closed: "Sunday, Monday" },
  },

  // ============================================
  // NEW BATCH — NIGHTLIFE & BARS
  // ============================================
  {
    name: "Cathy's Place",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["nightlife"],
    address: "G.04, Wisma Cosway, 88, Jalan Raja Chulan, 50200 Kuala Lumpur",
    latitude: 3.1502,
    longitude: 101.7112,
    price_range: "$$",
    what_to_order: ["Draft beer", "Bar snacks"],
    pro_tips: [
      "Old-school pub tucked in Wisma Cosway — proper dive bar vibes",
      "Regulars are friendly, good place to meet locals",
      "In the same building as the famous Wagon Bar",
    ],
    vibe: "local",
    best_time_of_day: "night",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "After One",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["cafe"],
    address: "1, Persiaran Lidcol, Jalan Yap Kwan Seng, 50450 Kuala Lumpur",
    latitude: 3.1572,
    longitude: 101.7195,
    price_range: "$$",
    what_to_order: ["Mediterranean brunch plates", "Coffee", "Cocktails at Alta Societe (upstairs bar)"],
    pro_tips: [
      "Mediterranean cafe by day, intimate bar (Alta Societe) upstairs by night",
      "Beautiful space — great for working or brunch",
      "Opens from 9am — rare for this area",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    opening_hours: { monday: "9am-6pm", "tue-sun": "9am-10pm" },
  },
  {
    name: "Bar.Kar",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "KLCC",
    categories: ["dinner"],
    address: "Suites G-06, Ground Floor, G Tower, 199, Jalan Tun Razak, Kuala Lumpur",
    latitude: 3.1568,
    longitude: 101.7212,
    price_range: "$$$",
    what_to_order: ["Open-flame grilled dishes", "Cocktails", "Chef's specials"],
    pro_tips: [
      "Michelin-listed — by the Eat and Cook team",
      "Open-flame dining concept — everything cooked over fire",
      "Book ahead, intimate space",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "12pm-3pm, 6pm-11pm", monday: "6pm-11pm" },
  },

  // ============================================
  // NEW BATCH — TTDI / MONT KIARA
  // ============================================
  {
    name: "Leen's Middle East Kitchen",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["dinner"],
    address: "136, Jalan Burhanuddin Helmi, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    latitude: 3.1372,
    longitude: 101.6298,
    price_range: "$$",
    what_to_order: ["Smoked hummus", "Crispy Syrian rice", "Kebab khashkhash", "Falafel"],
    pro_tips: [
      "Syrian chef Ameer's crowd-pleasing Middle Eastern kitchen in TTDI",
      "Dinner only on weekdays (6pm-11pm), lunch available weekends",
      "Closed Tuesdays",
      "Sister restaurant SAJ Bistronomy is next door",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon,wed-fri": "6pm-11pm", "sat-sun": "12pm-3pm, 6pm-11pm", closed: "Tuesday" },
  },
  {
    name: "Ember Modern Bistro",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["dinner"],
    address: "20, Jalan Wan Kadir 1, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    latitude: 3.1368,
    longitude: 101.6302,
    price_range: "$$",
    what_to_order: ["Modern Asian tasting menu", "Cocktails"],
    pro_tips: [
      "Modern Asian bistro in the TTDI neighbourhood",
      "Dinner only (5:30pm-11:45pm), closed Monday and Sunday",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sat": "5:30pm-11:45pm", closed: "Sunday, Monday" },
  },
  {
    name: "Bella Pasta & Wine",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["dinner"],
    address: "20A, Lorong Rahim Kajai 14, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    latitude: 3.1365,
    longitude: 101.6282,
    price_range: "$$",
    what_to_order: ["Handmade pasta (any)", "Free-flow wine on Sundays", "Tiramisu"],
    pro_tips: [
      "Fresh handmade pasta spot — romantic date night vibes",
      "Sunday free-flow wine deal is popular — book ahead",
      "Closed Monday",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "12pm-3pm, 6pm-12am", closed: "Monday" },
  },
  {
    name: "Don Omakase",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "TTDI",
    categories: ["lunch"],
    address: "123, Jalan Aminuddin Baki, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    latitude: 3.1375,
    longitude: 101.6288,
    price_range: "$$",
    what_to_order: ["Donburi omakase set", "Chirashi don", "Sashimi don"],
    pro_tips: [
      "Luxe donburi meets omakase — Japanese rice bowls done elevated",
      "Multiple locations (TTDI, Imbi, Mont Kiara, Uptown)",
      "Open for lunch only at most branches (11am-3:30pm)",
      "Closed Mondays",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "tue-sun": "11am-3:30pm", closed: "Monday" },
  },
  {
    name: "Sushi Mew Omakase",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Bintang",
    categories: ["dinner"],
    address: "The Westin KL, 199, Jalan Bukit Bintang, 55100 Kuala Lumpur",
    latitude: 3.1478,
    longitude: 101.7132,
    price_range: "$$$",
    what_to_order: ["YU omakase set (RM488)", "Nigiri course", "Seasonal specials"],
    pro_tips: [
      "Premium omakase at The Westin — artistry meets flavour",
      "Side entrance next to Ferria KL",
      "Reservation essential",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },

  // ============================================
  // NEW BATCH — MISC KL
  // ============================================
  {
    name: "Moknab Nasi Kerabu",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Pantai Dalam",
    categories: ["lunch"],
    address: "Jalan 1/132, Gasing Indah, Off Jalan Pantai Dalam, 59200 Kuala Lumpur",
    latitude: 3.1135,
    longitude: 101.6658,
    price_range: "$",
    what_to_order: ["Nasi kerabu lemak bakar", "Ayam percik", "Nasi kerabu biasa"],
    pro_tips: [
      "Best nasi kerabu in KL — blue rice, fresh herbs, rich flavour",
      "Halal, Muslim-operated",
      "Closed Fridays",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "sat-thu": "7:30am-11:30pm", closed: "Friday" },
  },
  {
    name: "The Coco Deli",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "OUG",
    categories: ["cafe"],
    address: "Taman Overseas Union, Kuala Lumpur",
    latitude: 3.0885,
    longitude: 101.6812,
    price_range: "$$",
    what_to_order: ["Mediterranean sharing plates", "Focaccia", "Seasonal specials"],
    pro_tips: [
      "Mediterranean-inspired restaurant by a former Ottolenghi chef from London",
      "Produce-driven menu that changes seasonally",
      "Hidden gem in OUG — worth the trip",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Third Serving",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Kiara",
    categories: ["dinner"],
    address: "Lot 3F-03, KLGCC Mall, 1, Jalan Bukit Kiara 1, Kuala Lumpur",
    latitude: 3.1575,
    longitude: 101.6398,
    price_range: "$$",
    what_to_order: ["Claypot loh shi fun", "Pig trotters in black vinegar", "Asam fish", "Kangkung belacan"],
    pro_tips: [
      "The revival of the beloved Oriental Cravings (1 Utama) — same chef, same flavours",
      "The claypot loh shi fun is legendary — silky rat noodles in rich gravy",
      "At the new KLGCC Mall — good parking, MRT accessible",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Nasi Lemak Wild Boar",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Puchong",
    categories: ["dinner"],
    address: "Block A, No. L1-12, Jalan TK 1/11g, Taman Kinrara, 47100 Puchong",
    latitude: 3.0647,
    longitude: 101.6482,
    price_range: "$",
    what_to_order: ["Nasi lemak with wild boar curry", "Claypot wild boar nasi lemak"],
    pro_tips: [
      "Non-halal nasi lemak with actual wild boar curry — nowhere else does this",
      "Multiple locations (Puchong, Kuchai Lama, Subang)",
      "Evening only (5pm-10pm), closed Sundays",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "mon-sat": "5pm-10pm", closed: "Sunday" },
  },
  {
    name: "Thai Moment",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Setapak",
    categories: ["dinner"],
    address: "No 21, Jalan 1/27B, Desa Setapak, 53300 Kuala Lumpur",
    latitude: 3.1835,
    longitude: 101.7175,
    price_range: "$$",
    what_to_order: ["Tom yum", "Green curry", "Mango sticky rice", "Thai milk tea"],
    pro_tips: [
      "Authentic Thai food — halal, no pork no alcohol",
      "Multiple branches across KL, PJ, Subang",
      "The Setapak original is the OG",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },
  {
    name: "Scrappy Dough",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Sungai Besi",
    categories: ["cafe"],
    address: "139, Jalan Sungai Besi, 57100 Kuala Lumpur",
    latitude: 3.0912,
    longitude: 101.6945,
    price_range: "$$",
    what_to_order: ["Sourdough bagels", "Focaccia sandwiches", "Coffee"],
    pro_tips: [
      "No signage — look for bagels hanging from the balcony and orange cones",
      "In an old industrial building — raw, cool vibes",
      "Pork-free",
      "Sells out fast, go early",
      "Closed Wednesday",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { "thu-tue": "8am-4pm", closed: "Wednesday" },
  },
  {
    name: "One Dish One Taste Hotpot",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Jalil",
    categories: ["dinner"],
    address: "Lot 3.120.00, Level 3, Pavilion Bukit Jalil, 2, Persiaran Bukit Jalil 8, 57000 Kuala Lumpur",
    latitude: 3.0542,
    longitude: 101.6728,
    price_range: "$$",
    what_to_order: ["Chongqing mala hotpot", "Sliced beef", "Handmade noodles"],
    pro_tips: [
      "Chongqing-style hotpot — proper mala broth",
      "Open till 2am — late-night hotpot option",
      "Also at Gurney Plaza Penang",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { daily: "11am-2am" },
  },
  {
    name: "Base Pasta Bar & Bistro",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Bukit Jalil",
    categories: ["dinner"],
    address: "B-1-13A, Aurora Place, No. 1, Persiaran Jalil 1, Bukit Jalil, 57000 Kuala Lumpur",
    latitude: 3.0548,
    longitude: 101.6735,
    price_range: "$$",
    what_to_order: ["Handmade pasta (any)", "Truffle fries", "Tiramisu"],
    pro_tips: [
      "By Chef Jay (formerly Back Alley Pasta) — handmade pasta specialist",
      "Every pasta is made fresh daily",
      "Cozy bistro setting in Bukit Jalil",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
  },

  // ============================================
  // NEW BATCH — CHERAS
  // ============================================
  {
    name: "Little Giraffe Story House",
    city: "Kuala Lumpur",
    country: "Malaysia",
    area: "Cheras",
    categories: ["cafe"],
    address: "114, Jalan 15, Batu 11 Cheras, 43200 Selangor",
    latitude: 3.0543,
    longitude: 101.7698,
    price_range: "$",
    what_to_order: ["Rojak (family recipe)", "Tauhu bakar", "Asam laksa", "Mee Jawa"],
    pro_tips: [
      "Book cafe meets community space in Cheras new village — charming and quirky",
      "Rojak and tauhu bakar are best-sellers — made from family recipe",
      "Also a library and event space — story-telling sessions, workshops",
      "Closed Mon-Tue, opens noon Wed-Sun",
      "Worth the trip to Batu 11 Cheras for the vibe alone",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    opening_hours: { wednesday_to_saturday: "noon-10pm", sunday: "noon-7pm", closed: "Monday, Tuesday" },
  },
];
