// Penang spots (87)

export const spots = [

  // ============================================
  // ============================================
  // PENANG — Georgetown & Island
  // ============================================
  // ============================================

  // ============================================
  // PENANG — BREAKFAST
  // ============================================
  {
    name: "Transfer Road Roti Canai",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 1,
    address: "110, Jalan Transfer, 10050 George Town, Pulau Pinang",
    latitude: 5.4209,
    longitude: 100.3307,
    price_range: "$",
    what_to_order: [
      "Roti canai with chicken curry (the classic)",
      "Roti telur (egg roti)",
      "Teh tarik",
    ],
    what_to_skip: ["Don't come after 11am — the good stuff is gone"],
    pro_tips: [
      "THE benchmark roti canai in Penang — crispy outside, fluffy inside",
      "Cash only, no exceptions",
      "Arrive before 9am on weekends or queue for ages",
      "The curry dipping sauces are the secret weapon — chicken curry is legendary",
      "It's a roadside stall, not a restaurant. Stand and eat like a local.",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { "mon-sat": "7am-12pm", sunday: "7:30am-12pm" },
  },
  {
    name: "Toh Soon Cafe",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 1,
    address: "184, Lebuh Campbell, 10450 George Town, Pulau Pinang",
    latitude: 5.4148,
    longitude: 100.3367,
    price_range: "$",
    what_to_order: [
      "Charcoal-grilled kaya toast — the signature",
      "Half-boiled eggs with soy sauce and white pepper",
      "Hainanese coffee (kopi-o)",
    ],
    pro_tips: [
      "Hidden down an alley off Campbell Street — look for the smoke and the queue",
      "Operating since 1950 — a Georgetown institution",
      "The toast is grilled over charcoal, giving it a smoky flavour you can't replicate",
      "Cash only, super cheap — RM5-8 for a full breakfast",
      "Go before 9am to avoid the tourist rush",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { "mon-sat": "8am-5pm", closed: "Sunday" },
  },
  {
    name: "Roti Canai Gemas Road",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 2,
    address: "51, Jalan Gemas, Taman Kampar, 10460 George Town, Pulau Pinang",
    latitude: 5.4088,
    longitude: 100.3185,
    price_range: "$",
    what_to_order: [
      "Roti canai biasa — perfectly crispy and flaky",
      "Roti telur bawang (egg and onion)",
      "Mee goreng mamak",
    ],
    pro_tips: [
      "Run by a family of siblings since 1994 — super authentic",
      "Locals rate this above Transfer Road for the roti itself",
      "Cash only — bring small bills",
      "Morning sessions are best, but they also open some evenings for dinner",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { "tue-sat": "7am-12:30pm" },
  },
  {
    name: "Joo Hooi Cafe",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 2,
    address: "475, Jalan Penang, 10450 George Town, Pulau Pinang",
    latitude: 5.4163,
    longitude: 100.3337,
    price_range: "$",
    what_to_order: [
      "Char kuey teow — the Jin Kor stall inside has Michelin Bib Gourmand",
      "Curry mee",
      "Popiah (spring rolls)",
      "Rojak",
    ],
    pro_tips: [
      "Multi-stall kopitiam — every stall specialises in one thing",
      "The char kuey teow stall (Jin Kor) inside is Michelin Bib Gourmand",
      "One-stop shop for trying multiple Penang hawker classics",
      "Cash only at all stalls",
      "Go before noon — popular stalls sell out",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "9:30am-5:30pm" },
  },

  // ============================================
  // PENANG — LUNCH
  // ============================================
  {
    name: "Siam Road Charcoal Char Kuey Teow",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 1,
    address: "82, Jalan Siam, 10400 George Town, Pulau Pinang",
    latitude: 5.4100,
    longitude: 100.3240,
    price_range: "$",
    what_to_order: [
      "Char kuey teow with duck egg — the only thing on the menu",
      "Add extra prawns if available",
    ],
    pro_tips: [
      "Michelin Bib Gourmand — arguably the best char kuey teow in Penang",
      "Charcoal-fired wok gives insane wok hei (smoky breath of the wok)",
      "Queue can be 1-2 hours on weekends — go on a weekday",
      "Pioneer of charcoal-fueled CKT — been doing this for decades",
      "Cash only, RM7-12 per plate",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "tue-sat": "12pm-6pm", closed: "Sunday, Monday" },
  },
  {
    name: "Sister's Char Koay Teow",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "185, Jalan Macalister, 10400 George Town, Pulau Pinang",
    latitude: 5.4125,
    longitude: 100.3255,
    price_range: "$",
    what_to_order: [
      "Char koay teow — the original style, lighter than Siam Road",
      "Add cockles and prawns",
    ],
    pro_tips: [
      "Run by two sisters — hence the name",
      "Located inside Lam Heng Cafe on Macalister Road",
      "Lighter, less oily CKT compared to Siam Road — different style, both legit",
      "Cash only, arrives fast once you order",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "tue-sun": "8:30am-4pm", closed: "Monday" },
  },
  {
    name: "Hameediyah Restaurant",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 1,
    address: "164, Lebuh Campbell, 10100 George Town, Pulau Pinang",
    latitude: 5.4148,
    longitude: 100.3368,
    price_range: "$",
    what_to_order: [
      "Nasi kandar — point at the curries, they pile them on rice",
      "Murtabak (stuffed roti) — their famous specialty since 1907",
      "Ayam goreng (fried chicken)",
    ],
    pro_tips: [
      "Oldest nasi kandar restaurant in Malaysia — operating since 1907",
      "Listed in the Malaysia Book of Records",
      "The murtabak here is legendary — crispy, stuffed with minced meat",
      "Gets packed at lunch — go at 11am or after 2pm",
      "Friday has modified hours for prayers — check before going",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "sun-thu": "10am-10pm", friday: "10am-12:30pm, 3pm-10pm" },
  },
  {
    name: "Tek Sen Restaurant",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 1,
    address: "18, Lebuh Carnarvon, 10100 George Town, Pulau Pinang",
    latitude: 5.4155,
    longitude: 100.3385,
    price_range: "$$",
    what_to_order: [
      "Double-roasted pork — their signature, crispy skin, tender inside",
      "Claypot yam rice",
      "Mango kerabu (salad)",
      "Any wok-fried dish — everything has serious wok hei",
    ],
    pro_tips: [
      "Michelin Bib Gourmand — home-style Chinese cooking elevated to art",
      "Established 1965 — family recipes passed down generations",
      "Book ahead or arrive right at noon for lunch — fills up fast",
      "Closed Tuesdays — plan accordingly",
      "The double-roasted pork alone is worth the trip",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "mon,wed-sun": "12pm-2:30pm, 6pm-9pm", closed: "Tuesday" },
  },
  {
    name: "Penang Road Famous Teochew Chendul",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 1,
    address: "27-29, Lebuh Keng Kwee, 10100 George Town, Pulau Pinang",
    latitude: 5.4168,
    longitude: 100.3332,
    price_range: "$",
    what_to_order: [
      "Chendul (cendol) — shaved ice, green pandan jelly, gula melaka, coconut milk",
      "Chendul pulut (with glutinous rice) for extra filling",
    ],
    pro_tips: [
      "THE original cendol stall — been here for decades, there's a reason for the queue",
      "No seating — stand by the roadside and eat like everyone else",
      "Cash only, RM3.50 per bowl — the best value dessert in Penang",
      "Go between 11am-2pm when it's hot — the shaved ice hits hardest",
      "Don't confuse with the rival stall across the road — this is the original green signboard",
    ],
    vibe: "chaotic",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "10am-5pm" },
  },
  {
    name: "Ah Leng Char Koay Teow",
    city: "Penang",
    area: "Dato Keramat",
    category: "lunch",
    tier: 2,
    address: "343, Jalan Dato Keramat, 10150 George Town, Pulau Pinang",
    latitude: 5.4190,
    longitude: 100.3210,
    price_range: "$",
    what_to_order: [
      "Char koay teow with prawns — the signature",
      "Add extra cockles for the full experience",
    ],
    pro_tips: [
      "Operating since 1979 — a serious CKT contender",
      "Inside Restoran Tong Hooi — easy to miss",
      "Closed Wed and Thu — plan your visit",
      "Slightly off the tourist trail, so shorter queues than Siam Road",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "mon-tue,fri-sun": "10:30am-4pm", closed: "Wednesday, Thursday" },
  },
  {
    name: "Lebuh Presgrave 888 Hokkien Mee",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "67-A, Lebuh Presgrave, 10300 George Town, Pulau Pinang",
    latitude: 5.4110,
    longitude: 100.3340,
    price_range: "$",
    what_to_order: [
      "Hokkien prawn mee — rich, dark prawn broth with thick noodles",
      "Add pork ribs and pork belly for the full experience",
      "Loh mee (thick gravy noodles) — also excellent",
    ],
    pro_tips: [
      "One of Penang's most famous Hokkien mee stalls",
      "The prawn broth is boiled for hours — intensely flavourful",
      "Cash only, RM6-10 per bowl",
      "Closed Monday and Thursday — check before heading over",
      "Try the fried oyster (oh chien) stall next door while waiting",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "tue-wed,fri-sun": "5pm-8pm", closed: "Monday, Thursday" },
  },
  {
    name: "Air Itam Laksa",
    city: "Penang",
    area: "Air Itam",
    category: "lunch",
    tier: 1,
    address: "1, Jalan Pasar, Paya Terubong, 11500 Air Itam, Pulau Pinang",
    latitude: 5.4014,
    longitude: 100.2774,
    price_range: "$",
    what_to_order: [
      "Asam laksa — tamarind-mackerel broth, thick rice noodles, torch ginger flower",
    ],
    what_to_skip: ["Check if the stall is currently operating — it has had intermittent closures"],
    pro_tips: [
      "Perhaps the most famous asam laksa in the world",
      "Inside Air Itam market — combine with a visit to Kek Lok Si nearby",
      "Cash only, around RM5-6 per bowl",
      "Only opens weekends, and only 3 weekends per month — check ahead",
      "The sour-spicy-fishy flavour profile is intense — not for the faint-hearted",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { "sat-sun": "10:30am-7pm (3 weekends/month)" },
  },
  {
    name: "Kimberley Street Duck Koay Chap",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "137, Lebuh Kimberley, 10100 George Town, Pulau Pinang",
    latitude: 5.4170,
    longitude: 100.3378,
    price_range: "$",
    what_to_order: [
      "Duck koay chap — braised duck with flat rice noodle rolls in herbal broth",
      "Add braised egg and tofu puffs",
    ],
    pro_tips: [
      "Kimberley Street is a legendary food street — this is the anchor stall",
      "Teochew-style braised duck — rich, herbal, deeply savoury",
      "Evening stall — starts around 6:30pm",
      "The queue gets long fast — go early or be patient",
      "Cash only, RM8-10 per bowl",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { "fri-wed": "6:30pm-11:30pm", closed: "Thursday" },
  },

  // ============================================
  // PENANG — DINNER
  // ============================================
  {
    name: "New Lane Hawker Centre",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 1,
    address: "Lorong Baru, off Jalan Macalister, 10400 George Town, Pulau Pinang",
    latitude: 5.4130,
    longitude: 100.3258,
    price_range: "$",
    what_to_order: [
      "Char kuey teow (charcoal-fried, the star attraction)",
      "Fried oyster omelette (oh chien)",
      "Wan tan mee",
      "Curry mee",
      "Pasembur (Indian-style rojak)",
    ],
    what_to_skip: ["The first stall that waves you in — walk the whole street first"],
    pro_tips: [
      "The road closes to traffic at 4pm and transforms into a massive open-air food court",
      "This is where Georgetown locals actually eat dinner — THE essential hawker experience",
      "Go between 6:30-8pm for peak atmosphere and all stalls open",
      "Cash only at all stalls — bring small bills",
      "Try at least 3-4 stalls — that's how you do it",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "6pm-10pm" },
  },
  {
    name: "Chulia Street Night Hawkers",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 2,
    address: "Lebuh Chulia, 10200 George Town, Pulau Pinang",
    latitude: 5.4195,
    longitude: 100.3405,
    price_range: "$",
    what_to_order: [
      "Wantan mee — the Mother & Son stall is legendary (nearly 50 years old)",
      "Char kuey teow",
      "Curry mee",
      "Fried carrot cake (chai tow kway)",
    ],
    pro_tips: [
      "Another classic Georgetown night hawker street — more backpacker-friendly than New Lane",
      "The wantan mee stall here is one of the best in Penang",
      "Stalls have been here for decades — this is the real deal",
      "Cash only everywhere",
      "Combines well with a Love Lane bar crawl after eating",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "6pm-11pm" },
  },
  {
    name: "Nasi Kandar Line Clear",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 1,
    address: "177, Jalan Penang, 10000 George Town, Pulau Pinang",
    latitude: 5.4165,
    longitude: 100.3350,
    price_range: "$",
    what_to_order: [
      "Nasi kandar — point at the curries, they pile them on",
      "Ayam goreng berempah (fried spiced chicken)",
      "Sambal sotong (spicy squid)",
      "Roti canai with dhal",
    ],
    pro_tips: [
      "The ORIGINAL Line Clear — this is where it all started, in an alley off Jalan Penang",
      "Open 24 hours — the 2am nasi kandar hits different",
      "Easy to miss the alley entrance — look for the crowd",
      "Queue moves fast despite looking long",
      "This is the Penang original, not the KL branch",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "Gurney Drive Hawker Centre",
    city: "Penang",
    area: "Gurney Drive",
    category: "dinner",
    tier: 2,
    address: "172, Solok Gurney 1, 10250 George Town, Pulau Pinang",
    latitude: 5.4375,
    longitude: 100.3130,
    price_range: "$",
    what_to_order: [
      "Char kuey teow",
      "Hokkien mee (prawn noodle soup)",
      "Pasembur (Indian rojak)",
      "Satay",
      "Lok lok (pick your skewers, they cook them)",
    ],
    pro_tips: [
      "One of Penang's biggest and most famous hawker centres — by the sea",
      "Best time is 7-9pm when all stalls are firing",
      "More touristy than New Lane but still legit food",
      "Cash only at all stalls",
      "The sea breeze makes outdoor eating pleasant — grab a seaside table",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "6pm-midnight" },
  },
  {
    name: "Red Garden Food Paradise",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 3,
    address: "20, Lebuh Leith, 10200 George Town, Pulau Pinang",
    latitude: 5.4210,
    longitude: 100.3375,
    price_range: "$",
    what_to_order: [
      "Sample multiple stalls — this is a one-stop hawker food court",
      "Char kuey teow, satay, grilled seafood",
      "Thai food stalls are surprisingly good here",
    ],
    pro_tips: [
      "Open-air food court with live music some nights — good vibe",
      "More tourist-friendly and organised than street hawkers",
      "Good rainy-weather alternative to street hawkers — partially covered",
      "Central location near Chulia Street — easy to combine with a walk",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "6pm-midnight" },
  },
  {
    name: "Long Beach Cafe",
    city: "Penang",
    area: "Batu Ferringhi",
    category: "dinner",
    tier: 2,
    address: "Batu Ferringhi Beach, 11100 Batu Ferringhi, Pulau Pinang",
    latitude: 5.4700,
    longitude: 100.2480,
    price_range: "$$",
    what_to_order: [
      "Grilled seafood — prawns, fish, squid",
      "Butter prawns (Penang style with curry leaves and egg floss)",
      "Fried rice",
    ],
    pro_tips: [
      "Beach-side seafood dining in Batu Ferringhi — touristy but the seafood is fresh",
      "Pick your seafood from the display — they cook it how you want",
      "Go at sunset for the best atmosphere",
      "Prices are higher than Georgetown hawkers but portions are generous",
      "Combine with the Batu Ferringhi Night Market nearby",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "5pm-midnight" },
  },
  {
    name: "Hai Boey Seafood",
    city: "Penang",
    area: "Tanjung Bungah",
    category: "dinner",
    tier: 2,
    address: "43, Jalan Tanjung Bungah, 11200 Tanjung Bungah, Pulau Pinang",
    latitude: 5.4560,
    longitude: 100.2820,
    price_range: "$$",
    what_to_order: [
      "Butter prawns — the signature dish",
      "Salted egg crab",
      "Steamed fish in soy sauce",
      "Kam heong clams (aromatic stir-fry)",
    ],
    pro_tips: [
      "Local favourite for fresh seafood — less touristy than Batu Ferringhi",
      "Reasonable prices for the quality and freshness",
      "Book ahead on weekends — it fills up",
      "The butter prawns with curry leaves are addictive",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-10:30pm" },
  },
  {
    name: "Tiger Char Koay Teow",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 2,
    address: "262-264, Lebuh Carnarvon, 10100 George Town, Pulau Pinang",
    latitude: 5.4158,
    longitude: 100.3382,
    price_range: "$",
    what_to_order: [
      "Char koay teow — Mr Yeow (aka Tiger/Ah Hor) is the wok master",
      "Add extra prawns and cockles",
    ],
    pro_tips: [
      "Mr Yeow got his nickname 'Tiger' from his fierce wok skills",
      "Inside OO White Coffee Cafe on Carnarvon Street",
      "Morning-afternoon stall — different from the night hawker scene",
      "Closed Wednesdays — plan accordingly",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "thu-tue": "6am-4:30pm", closed: "Wednesday" },
  },

  // ============================================
  // PENANG — CAFES
  // ============================================
  {
    name: "ChinaHouse",
    city: "Penang",
    area: "Georgetown",
    category: "cafe",
    tier: 1,
    address: "153, Lebuh Pantai (Beach Street), 10300 George Town, Pulau Pinang",
    latitude: 5.4155,
    longitude: 100.3432,
    price_range: "$$",
    what_to_order: [
      "Any cake — they have 30+ varieties daily, all baked in-house",
      "Coffee or tea to go with the cake",
      "The tiramisu and cheesecake are standouts",
    ],
    pro_tips: [
      "Three heritage buildings connected by courtyards — 400 feet long, one of Asia's longest cafes",
      "Part cafe, part bar, part art gallery, part performance space",
      "Perfect rainy day activity — you can spend hours exploring the different spaces",
      "The evening transforms it into a cocktail bar — completely different vibe",
      "Live music and comedy shows some nights — check their schedule",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { daily: "9:30am-1am" },
  },
  {
    name: "Macallum Connoisseurs Coffee Co.",
    city: "Penang",
    area: "Georgetown",
    category: "cafe",
    tier: 2,
    address: "1, Gat Lebuh Macallum, 10300 George Town, Pulau Pinang",
    latitude: 5.4060,
    longitude: 100.3390,
    price_range: "$$",
    what_to_order: [
      "Pour over single origin — they roast their own beans",
      "Flat white — well-balanced",
      "Any brunch item",
    ],
    pro_tips: [
      "8,000 sq ft space — roastery, cafe, restaurant, and coffee academy under one roof",
      "Serious specialty coffee — one of Penang's best",
      "Great for a work session with laptop — Wi-Fi and power outlets",
      "The coffee flights are a fun way to try different beans",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "9am-10pm" },
  },
  {
    name: "Mugshot Cafe",
    city: "Penang",
    area: "Georgetown",
    category: "cafe",
    tier: 2,
    address: "302, Lebuh Chulia, 10200 George Town, Pulau Pinang",
    latitude: 5.4200,
    longitude: 100.3395,
    price_range: "$$",
    what_to_order: [
      "Bagels — some of the best in Penang",
      "Flat white or any espresso-based coffee",
      "Big breakfast",
    ],
    pro_tips: [
      "On Chulia Street near Love Lane — backpacker central",
      "Known for their excellent bagels",
      "Good brunch spot — arrives fast, generous portions",
      "Open late on weekends — good for a post-bar coffee",
      "Adjacent to Rainforest Bakery for extra baked goods",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "mon-fri": "8am-10pm", "sat-sun": "8am-12am" },
  },
  {
    name: "Wheeler's Coffee",
    city: "Penang",
    area: "Georgetown",
    category: "cafe",
    tier: 3,
    address: "67, Lorong Love, 10200 George Town, Pulau Pinang",
    latitude: 5.4200,
    longitude: 100.3380,
    price_range: "$$",
    what_to_order: [
      "Espresso chicken — their quirky signature",
      "Any coffee — well-made",
      "Panini sandwiches",
    ],
    pro_tips: [
      "Bicycle-themed cafe on Love Lane — quirky decor",
      "Doubles as a bar in the evening with cocktails and draft beer",
      "Good location for exploring Love Lane's backpacker scene",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { "mon-sat": "8am-12am" },
  },
  {
    name: "Ome by Spacebar",
    city: "Penang",
    area: "Georgetown",
    category: "cafe",
    tier: 2,
    address: "21, Lebuh Gereja (Church Street), 10200 George Town, Pulau Pinang",
    latitude: 5.4175,
    longitude: 100.3420,
    price_range: "$$",
    what_to_order: [
      "Pour over or filter coffee — they take single origin seriously",
      "Matcha latte",
      "Light bites and pastries",
    ],
    pro_tips: [
      "Minimalist, photogenic space in a restored Georgetown shophouse",
      "One of the newer wave specialty coffee spots — quality beans",
      "Quiet, focused vibe — good for reading or a conversation",
      "Near Pinang Peranakan Mansion — combine visits",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { "wed-mon": "10am-6pm", closed: "Tuesday" },
  },

  // ============================================
  // PENANG — NIGHTLIFE
  // ============================================
  {
    name: "Narrow Marrow",
    city: "Penang",
    area: "Georgetown",
    category: "nightlife",
    tier: 2,
    address: "312, Lebuh Pantai (Beach Street), 10300 George Town, Pulau Pinang",
    latitude: 5.4135,
    longitude: 100.3430,
    price_range: "$$",
    what_to_order: [
      "Tiramisu — their famous signature dessert",
      "Creative cocktails",
      "Hot toddy",
    ],
    pro_tips: [
      "Cafe by day, bohemian bar by night — the transformation is wild",
      "Penang's creative community hub — art exhibitions, live music, poetry readings",
      "The tiramisu is genuinely one of the best in the country",
      "Colourful, eclectic interiors — great for photos",
      "Closed Tue-Wed — plan accordingly",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "thu-mon": "3pm-11pm", closed: "Tuesday, Wednesday" },
  },
  {
    name: "Love Lane Bars",
    city: "Penang",
    area: "Georgetown",
    category: "nightlife",
    tier: 2,
    address: "Lorong Love, 10200 George Town, Pulau Pinang",
    latitude: 5.4198,
    longitude: 100.3378,
    price_range: "$$",
    what_to_order: [
      "Bar hop — try different spots along the lane",
      "Local craft beers at any of the pubs",
      "Cocktails at the smaller bars",
    ],
    pro_tips: [
      "Georgetown's main backpacker nightlife strip — wall-to-wall bars and hostels",
      "More relaxed and less clubby than KL nightlife — chill pub vibes",
      "Cheapest drinks in Georgetown here",
      "Safe area, well-lit, walk-friendly",
      "Combine with Chulia Street hawker food before or after drinking",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-2am" },
  },
  {
    name: "Hin Bus Depot",
    city: "Penang",
    area: "Georgetown",
    category: "nightlife",
    tier: 2,
    address: "31A, Jalan Gurdwara, 10300 George Town, Pulau Pinang",
    latitude: 5.4125,
    longitude: 100.3395,
    price_range: "$$",
    what_to_order: [
      "Drinks at Good Friends Club — kopitiam-vibes bar, open till late",
      "Coffee at Bricklin Cafe during the day",
      "Browse the weekend Hin Market (70+ stalls)",
    ],
    pro_tips: [
      "Converted bus depot turned creative arts hub — street art, galleries, events",
      "Weekend market is excellent — local makers, food, crafts",
      "Free admission to the space — galleries rotate regularly",
      "Good Friends Club bar stays open till 1-2am on weekends",
      "Check their Instagram for events — live music, art openings",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "10am-10pm (bar/events later)" },
  },
  {
    name: "Garage Music & Bar",
    city: "Penang",
    area: "Georgetown",
    category: "nightlife",
    tier: 3,
    address: "316, Lebuh Pantai (Beach Street), 10300 George Town, Pulau Pinang",
    latitude: 5.4133,
    longitude: 100.3432,
    price_range: "$$",
    what_to_order: [
      "Beer or basic cocktails — the vibe is the main course",
      "Check if there's live music tonight",
    ],
    pro_tips: [
      "Graffiti-covered, neon-lit industrial bar on Beach Street",
      "Live band performances some nights — local and touring acts",
      "More of a party vibe than the chill cafes — gets loud",
      "Near Narrow Marrow — easy to bar-hop between the two",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "6pm-1am" },
  },

  // ============================================
  // PENANG — MARKETS
  // ============================================
  {
    name: "Chowrasta Market",
    city: "Penang",
    area: "Georgetown",
    category: "market",
    tier: 1,
    address: "Lebuh Tamil, 10100 George Town, Pulau Pinang",
    latitude: 5.4160,
    longitude: 100.3340,
    price_range: "$",
    what_to_order: [
      "Browse fresh fruits — look for durian in season (June-Aug)",
      "Nutmeg juice and products — a Penang specialty",
      "Dried spices and preserved fruits upstairs",
      "Snack on kuih from the stalls",
    ],
    pro_tips: [
      "One of two operational wet markets in the heart of Georgetown",
      "Ground floor: wet market (meat, fish, veg). Upstairs: dry goods, books, clothes",
      "Go before 10am for the full experience — it winds down by afternoon",
      "Near Penang Road Chendul — combine visits",
      "The nutmeg products make great souvenirs — unique to Penang",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "6:30am-6pm" },
  },
  {
    name: "Cecil Street Market",
    city: "Penang",
    area: "Georgetown",
    category: "market",
    tier: 2,
    address: "24, Lebuh Cecil, 10300 George Town, Pulau Pinang",
    latitude: 5.4110,
    longitude: 100.3345,
    price_range: "$",
    what_to_order: [
      "Duck kuey teow th'ng — the famous stall here",
      "Wan tan mee",
      "Curry mee",
      "Nyonya kueh (colourful rice cakes)",
    ],
    pro_tips: [
      "Local wet market + hawker centre combo — very authentic",
      "The duck kuey teow, barefoot CKT, and wan tan mee stalls always have queues",
      "Morning is best for the wet market, lunch for the food stalls",
      "Cash only everywhere",
      "Off the main tourist trail — you'll be eating with locals",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "7am-5:30pm" },
  },
  {
    name: "Pulau Tikus Market",
    city: "Penang",
    area: "Pulau Tikus",
    category: "market",
    tier: 3,
    address: "Jalan Pasar, Pulau Tikus, 10350 George Town, Pulau Pinang",
    latitude: 5.4310,
    longitude: 100.3130,
    price_range: "$",
    what_to_order: [
      "Nasi lemak from the morning stalls",
      "Popiah — the Peranakan-style here is excellent",
      "Fresh tropical fruits",
    ],
    pro_tips: [
      "Upscale neighbourhood market — Pulau Tikus is Georgetown's residential suburb",
      "Less touristy than Chowrasta — genuine local morning market experience",
      "The popiah stall is worth seeking out",
      "Go early — market closes by early afternoon",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "6am-1pm" },
  },
  {
    name: "Batu Ferringhi Night Market",
    city: "Penang",
    area: "Batu Ferringhi",
    category: "market",
    tier: 2,
    address: "Jalan Batu Ferringhi, 11100 Batu Ferringhi, Pulau Pinang",
    latitude: 5.4695,
    longitude: 100.2510,
    price_range: "$",
    what_to_order: [
      "Browse souvenirs, t-shirts, local crafts",
      "Street food stalls — char kuey teow, satay, ais kacang",
      "Negotiate on prices — first quote is always high",
    ],
    pro_tips: [
      "Penang's most popular night market — takes over the main road every evening",
      "More touristy than Georgetown markets, but fun atmosphere",
      "Combine with a beach sunset + Long Beach seafood dinner",
      "Free to browse — just bring cash for purchases",
      "Bus 101 from Georgetown goes directly here",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "7pm-11pm" },
  },

  // ============================================
  // PENANG — ACTIVITIES
  // ============================================
  {
    name: "Georgetown Street Art Walk",
    city: "Penang",
    area: "Georgetown",
    category: "activity",
    tier: 1,
    address: "Start at Lebuh Armenian, 10200 George Town, Pulau Pinang",
    latitude: 5.4175,
    longitude: 100.3400,
    price_range: "$",
    what_to_order: [
      "Free self-guided walking tour — pick up a map from the tourist office on Beach Street",
      "Must-see murals: Kids on a Bicycle, Boy on a Motorbike, Brother and Sister on Swing",
    ],
    pro_tips: [
      "Created by Lithuanian artist Ernest Zacharevic in 2012 — interactive murals with real props",
      "Start at Armenian Street and work your way through Chulia, Muntri, and Cannon streets",
      "Go at 7am to avoid crowds and heat — the murals look best in morning light",
      "Some murals have faded over the years — the steel-rod wire art sculptures are permanent",
      "Combine with hawker food stops between murals — Georgetown is compact and walkable",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "24 hours (best early morning)" },
  },
  {
    name: "Kek Lok Si Temple",
    city: "Penang",
    area: "Air Itam",
    category: "activity",
    tier: 1,
    address: "1, Tokong Kek Lok Si, 11500 Air Itam, Pulau Pinang",
    latitude: 5.4002,
    longitude: 100.2730,
    price_range: "$",
    what_to_order: [
      "Free entry to main temple complex",
      "Pagoda tower: RM2",
      "Sky Lift to Kuan Yin statue: RM6",
    ],
    pro_tips: [
      "Largest Buddhist temple in Malaysia — spectacular architecture on a hillside",
      "The Pagoda of Ten Thousand Buddhas combines Chinese, Thai, and Burmese styles",
      "Go in the morning to avoid the midday heat — lots of stairs",
      "During Chinese New Year (Jan/Feb), the temple is lit with thousands of lanterns — magical",
      "Combine with Air Itam Laksa in the market below",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "8:30am-5:30pm" },
  },
  {
    name: "Penang Hill",
    city: "Penang",
    area: "Air Itam",
    category: "activity",
    tier: 1,
    address: "Penang Hill Lower Station, 11500 Bukit Bendera, Pulau Pinang",
    latitude: 5.4245,
    longitude: 100.2700,
    price_range: "$$",
    what_to_order: [
      "Funicular train: RM16 adult (Malaysian), higher for tourists",
      "Fast Lane: RM40 (skip the queue)",
      "The Habitat canopy walk at the top: RM50",
    ],
    pro_tips: [
      "833m above sea level — noticeably cooler than Georgetown below",
      "The funicular ride itself is part of the experience — steep and scenic",
      "Go for sunset — the view of Georgetown lighting up at dusk is spectacular",
      "Last train down at 11pm — plenty of time for sunset",
      "The Habitat at the top has a treetop walk and is worth the extra fee",
      "Queue can be 1+ hour on weekends — use Fast Lane or go on weekdays",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "6:30am-11pm" },
  },
  {
    name: "Clan Jetties",
    city: "Penang",
    area: "Georgetown",
    category: "activity",
    tier: 1,
    address: "Pengkalan Weld, 10300 George Town, Pulau Pinang",
    latitude: 5.4138,
    longitude: 100.3430,
    price_range: "$",
    what_to_order: [
      "Free entry (donations welcome)",
      "Chew Jetty is the largest and most visited",
      "Walk to the end of the jetty for harbour views",
    ],
    pro_tips: [
      "Chinese clan houses built on stilts over the water — UNESCO heritage",
      "Each jetty was historically home to a single Chinese clan (Chew, Tan, Lee, etc.)",
      "Chew Jetty has small shops and a temple at the end — the most photogenic",
      "These are living communities — be respectful, don't enter private homes",
      "Visit hours: 9am-9pm — respect the residents' privacy",
      "Best light for photos in late afternoon",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "9am-9pm" },
  },
  {
    name: "Khoo Kongsi",
    city: "Penang",
    area: "Georgetown",
    category: "activity",
    tier: 2,
    address: "18, Cannon Square, 10200 George Town, Pulau Pinang",
    latitude: 5.4155,
    longitude: 100.3410,
    price_range: "$",
    what_to_order: [
      "Entry: RM15 adults (foreigners), RM10 (Malaysians), RM1 children",
    ],
    pro_tips: [
      "Most ornate Chinese clan house in Malaysia — jaw-dropping detail in the carvings",
      "The Khoo clan was one of Georgetown's wealthiest — this was their community hall",
      "Allow about 1 hour for the visit",
      "Entrance through a narrow lane off Cannon Street — look for the security guard",
      "Combine with Clan Jetties and street art — all within walking distance",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "9am-5pm" },
  },
  {
    name: "Fort Cornwallis",
    city: "Penang",
    area: "Georgetown",
    category: "activity",
    tier: 2,
    address: "Jalan Tun Syed Sheh Barakbah, 10200 George Town, Pulau Pinang",
    latitude: 5.4215,
    longitude: 100.3450,
    price_range: "$",
    what_to_order: [
      "Entry: RM20 (foreigners), RM10 (Malaysians) — card only, no cash",
    ],
    pro_tips: [
      "Where Captain Francis Light first landed in 1786 — the birthplace of British Penang",
      "Star-shaped fort with old cannons, including the famous Seri Rambai cannon",
      "Entry fee is card-only — no cash accepted",
      "Nice waterfront location — good sunset views from the ramparts",
      "Takes about 30-45 minutes to walk around",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "8am-8pm" },
  },
  {
    name: "Pinang Peranakan Mansion",
    city: "Penang",
    area: "Georgetown",
    category: "activity",
    tier: 2,
    address: "29, Lebuh Gereja (Church Street), 10200 George Town, Pulau Pinang",
    latitude: 5.4175,
    longitude: 100.3425,
    price_range: "$",
    what_to_order: [
      "Entry: RM20 adults, free for children under 6",
    ],
    pro_tips: [
      "Beautiful 19th century Peranakan mansion — showcases the wealthy Straits Chinese lifestyle",
      "Built by Kapitan Cina Chung Keng Kwee — a mining tycoon",
      "Over 1,000 antiques on display — furniture, jewellery, costumes",
      "Great indoor activity for a hot or rainy afternoon",
      "Allow about 1-1.5 hours for a thorough visit",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "9:30am-5pm" },
  },
  {
    name: "Tropical Spice Garden",
    city: "Penang",
    area: "Teluk Bahang",
    category: "activity",
    tier: 2,
    address: "Lot 595, Mukim 2, Jalan Teluk Bahang, 11100 Pulau Pinang",
    latitude: 5.4510,
    longitude: 100.2140,
    price_range: "$$",
    what_to_order: [
      "Self-guided garden walk",
      "Guided spice tour (weekends 9am, 11am, 1:30pm)",
      "Cooking class (book ahead)",
    ],
    pro_tips: [
      "8 acres of tropical plants, herbs, and spices — over 500 species",
      "Guided tours are excellent — you'll learn about spices used in Penang cuisine",
      "The cooking classes are highly rated — learn to make laksa, curry, etc.",
      "Good escape from Georgetown's heat — shaded jungle paths",
      "Near Teluk Bahang — combine with Entopia or Penang National Park",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { "fri-sun": "9am-6pm", "mon-thu": "9am-4:30pm" },
  },
  {
    name: "Entopia by Penang Butterfly Farm",
    city: "Penang",
    area: "Teluk Bahang",
    category: "activity",
    tier: 2,
    address: "830, Jalan Teluk Bahang, 11050 Teluk Bahang, Pulau Pinang",
    latitude: 5.4460,
    longitude: 100.2190,
    price_range: "$$",
    what_to_order: [
      "Entry: ~RM50-65 depending on nationality",
      "Combo tickets with other attractions available online",
    ],
    pro_tips: [
      "Massive butterfly sanctuary — free-flying butterflies in a lush glasshouse",
      "Great for families with kids — the indoor Cocoon discovery centre is interactive",
      "Closed Wednesdays — check before making the trip",
      "Book tickets online for 10-15% discount",
      "Allow 1.5-2 hours for the full experience",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "thu-tue": "9am-6pm", closed: "Wednesday" },
  },
  {
    name: "Penang National Park",
    city: "Penang",
    area: "Teluk Bahang",
    category: "activity",
    tier: 2,
    address: "Jalan Hassan Abas, 11050 Teluk Bahang, Pulau Pinang",
    latitude: 5.4530,
    longitude: 100.2075,
    price_range: "$",
    what_to_order: [
      "Entry: RM50 adults (foreigners), RM10 children",
      "Hike to Monkey Beach (3.5km, ~2 hours)",
      "Boat to Monkey Beach: RM100 return, RM70 one-way",
    ],
    pro_tips: [
      "The world's smallest national park — but packed with nature",
      "Monkey Beach is the highlight — swim, relax, spot macaques",
      "Register at the office before entering — bring passport/IC",
      "Bring 1.5L+ water and snacks — no shops on the trail",
      "Wear proper shoes (not sandals) — trail can be muddy",
      "Start early (8-9am) to beat the heat on the trail",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { "sat-thu": "8am-4:30pm" },
  },
  {
    name: "ESCAPE Theme Park Penang",
    city: "Penang",
    area: "Teluk Bahang",
    category: "activity",
    tier: 2,
    address: "828, Jalan Teluk Bahang, 11050 Teluk Bahang, Pulau Pinang",
    latitude: 5.4465,
    longitude: 100.2185,
    price_range: "$$",
    what_to_order: [
      "Day pass (Adventureplay + Waterplay): ~RM100-140",
      "The 1.1km zip line — longest in Asia",
    ],
    pro_tips: [
      "Not a typical theme park — built into the jungle, nature-focused",
      "The zip line is 1.1km long and genuinely thrilling",
      "Great for families, couples, and adventure seekers",
      "Book online for better prices",
      "Wear swimwear under clothes — the water park section is great",
      "Allow a full day — there's a lot to do",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { "tue-sun": "10am-6pm", closed: "Monday" },
  },

  // ============================================
  // PENANG — MORE FOOD (Street Food Deep Cuts)
  // ============================================
  {
    name: "Bridge Street Prawn Noodle",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 1,
    address: "533, Lebuh Pantai (Beach Street), 10300 George Town, Pulau Pinang",
    latitude: 5.4130,
    longitude: 100.3435,
    price_range: "$",
    what_to_order: [
      "Hokkien prawn mee — the signature, rich dark prawn broth",
      "Lor mee (thick gravy noodles) — or ask for the combo (mixed)",
      "Choose yellow noodles, rice noodles, or both",
    ],
    pro_tips: [
      "Michelin Bib Gourmand — 3rd generation, operating since the 1950s",
      "One of the OG hokkien mee stalls in Penang",
      "Morning stall — closes by 2:30pm, come early for peak freshness",
      "Cash only, RM6-10 per bowl",
      "Closed Mondays — plan around it",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { "tue-sun": "7am-2:30pm", closed: "Monday" },
  },
  {
    name: "Lorong Seratus Tahun Curry Mee",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 2,
    address: "58-C, Jalan Rangoon, 10400 George Town, Pulau Pinang",
    latitude: 5.4120,
    longitude: 100.3215,
    price_range: "$",
    what_to_order: [
      "Curry mee — coconut curry broth with beehoon and yellow noodles",
      "Add cockles, cuttlefish, and pig's blood curd (the authentic combo)",
    ],
    pro_tips: [
      "Family-run stall at Khuan Pin coffee shop — nearly 50 years old",
      "One item only: curry mee. That focus shows in the quality.",
      "Opens 7:30am, sells out by noon — go early",
      "The pig's blood curd is traditional — skip it if that's not your thing, still amazing without",
      "Cash only, around RM5-7 per bowl",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "7:30am-12pm" },
  },
  {
    name: "Padang Kota Lama Pasembur",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "Medan Renong, Padang Kota Lama, Jalan Tun Syed Sheh Barakbah, 10200 George Town",
    latitude: 5.4218,
    longitude: 100.3445,
    price_range: "$",
    what_to_order: [
      "Pasembur — Indian-style rojak with fried fritters, tofu, prawn, cucumber, sweet spicy sauce",
      "Add extra prawn fritters and hard-boiled egg",
    ],
    pro_tips: [
      "Hussain Pasembur King and Gani Famous Pasembur are the two main rivals here — try both",
      "The sweet-spicy peanut sauce is the star — every stall guards their recipe",
      "Right by the Esplanade waterfront — great sunset eating spot",
      "Queue can be long — worth the wait",
      "Cash only, RM5-10 depending on toppings",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "10am-7pm" },
  },
  {
    name: "Padang Brown Food Court",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "Jalan Perak, 10050 George Town, Pulau Pinang",
    latitude: 5.4105,
    longitude: 100.3225,
    price_range: "$",
    what_to_order: [
      "Crab meat popiah — the famous stall has been here 60+ years",
      "Pasembur",
      "Bubur chacha (coconut dessert soup)",
      "Beef and mutton soup",
    ],
    pro_tips: [
      "One of Georgetown's oldest hawker centres — opened in 1966",
      "The crab meat popiah stall is legendary — the only stall to use real crab",
      "Mix of Malay, Chinese, and Indian stalls — diverse selection",
      "Less touristy than Gurney Drive — mostly locals",
      "Best at lunchtime when all stalls are open",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "mon-sat": "8am-5pm", closed: "Sunday" },
  },
  {
    name: "Green House Prawn Mee",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "210, Jalan Burma, 10050 George Town, Pulau Pinang",
    latitude: 5.4215,
    longitude: 100.3265,
    price_range: "$",
    what_to_order: [
      "Prawn mee + lor mee combo (mixed) — the best of both worlds",
      "Hokkien prawn mee if you want just the soup version",
    ],
    pro_tips: [
      "Michelin Bib Gourmand — the combo of prawn mee and lor mee gravy is their signature",
      "Burma Road is a legendary food street in Penang",
      "Morning stall — arrives early, sells out by early afternoon",
      "Cash only, around RM7-10",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "thu-tue": "7:30am-1:30pm", closed: "Wednesday" },
  },
  {
    name: "Lebuh Acheh Wantan Mee",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "Lebuh Acheh, 10200 George Town, Pulau Pinang",
    latitude: 5.4175,
    longitude: 100.3395,
    price_range: "$",
    what_to_order: [
      "Wantan mee dry — springy egg noodles tossed in dark soy and lard, with char siew and wantan dumplings",
      "Add extra char siew (roast pork)",
      "Wantan soup on the side",
    ],
    pro_tips: [
      "One of the best wantan mee stalls in Georgetown — proper old-school style",
      "The dry version is the Penang standard — different from KL's sweeter style",
      "Penang wantan mee uses thinner, springier noodles than KL",
      "Cash only, RM5-8 per plate",
      "Goes fast — arrive before noon",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "7:30am-2pm" },
  },
  {
    name: "Lorong Selamat Char Koay Teow",
    city: "Penang",
    area: "Georgetown",
    category: "lunch",
    tier: 2,
    address: "Lorong Selamat, 10400 George Town, Pulau Pinang",
    latitude: 5.4115,
    longitude: 100.3250,
    price_range: "$",
    what_to_order: [
      "Char koay teow — fried with duck egg for extra richness",
    ],
    what_to_skip: ["Don't come just for this if you have limited time — Siam Road CKT is more consistent"],
    pro_tips: [
      "The famous aunty who made this stall legendary has retired — now run by successors",
      "Still a solid CKT but opinions differ on whether it's maintained the original standard",
      "Less queue than the famous days — easier to get a plate now",
      "Cash only, RM8-12 per plate",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    opening_hours: { daily: "12pm-6pm" },
  },
  {
    name: "Nasi Lemak Antarabangsa",
    city: "Penang",
    area: "Georgetown",
    category: "breakfast",
    tier: 2,
    address: "88, Lorong Abu Siti, 10400 George Town, Pulau Pinang",
    latitude: 5.4135,
    longitude: 100.3230,
    price_range: "$",
    what_to_order: [
      "Nasi lemak with fried chicken — the classic combo",
      "Add sambal sotong (spicy squid)",
      "Nasi lemak campur — rice with multiple toppings",
    ],
    pro_tips: [
      "One of Georgetown's most popular nasi lemak spots — fragrant coconut rice",
      "Morning stall — arrive before 10am for best selection",
      "The sambal is fiery and addictive",
      "Cash only, RM5-10 depending on add-ons",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "7am-1pm" },
  },
  {
    name: "Wan Tan Mee @ Lebuh Cintra",
    city: "Penang",
    area: "Georgetown",
    category: "dinner",
    tier: 2,
    address: "Lebuh Cintra, 10100 George Town, Pulau Pinang",
    latitude: 5.4165,
    longitude: 100.3375,
    price_range: "$",
    what_to_order: [
      "Wan tan mee dry — the Penang-style with thinner noodles and darker sauce",
      "Wan tan soup — plump pork and prawn dumplings",
      "Char siew (roast pork) — extra if you're hungry",
    ],
    pro_tips: [
      "Evening stall on Cintra Street — part of the Georgetown night hawker scene",
      "Penang wantan mee is drier and less sweet than the KL version — more savoury",
      "The stall has been around for decades — consistency is the hallmark",
      "Combine with Kimberley Street duck koay chap nearby",
      "Cash only, RM5-8 per plate",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "6pm-11pm" },
  },

  // ============================================
  // PENANG — Mainland (Butterworth / Seberang Perai)
  // ============================================
  {
    name: "Chai Leng Park Hawker Centre",
    city: "Penang",
    area: "Butterworth",
    category: "dinner",
    tier: 2,
    address: "Chai Leng Park, 13700 Butterworth, Pulau Pinang",
    latitude: 5.3880,
    longitude: 100.3950,
    price_range: "$",
    what_to_order: [
      "Char kuey teow — mainland style",
      "Lok lok (skewer hotpot)",
      "Fried oyster omelette",
      "Grilled seafood stalls",
    ],
    pro_tips: [
      "Butterworth's answer to Georgetown hawker streets — lively open-air food court",
      "The mainland's most popular Wai Sek Kai (food street)",
      "Significantly cheaper than Georgetown stalls",
      "Comes alive at night — go after 6pm",
      "Zero tourists, all locals — genuine mainland experience",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "5pm-11pm" },
  },
  {
    name: "Luan Fong Kopitiam",
    city: "Penang",
    area: "Butterworth",
    category: "breakfast",
    tier: 3,
    address: "Lorong Bagan Luar 3, 12000 Butterworth, Pulau Pinang",
    latitude: 5.3990,
    longitude: 100.3655,
    price_range: "$",
    what_to_order: [
      "Kaya toast with butter — old-school charcoal-grilled",
      "Kopi (local coffee) — traditional sock-filter brewed",
      "Half-boiled eggs",
    ],
    pro_tips: [
      "Heritage kopitiam with old-world charm — mainland Penang's breakfast institution",
      "The kaya toast is grilled over charcoal, like Toh Soon Cafe but without the tourist crowd",
      "Cash only, very cheap — RM5-8 for a full breakfast",
      "Near Butterworth ferry terminal — easy stop before crossing to the island",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "6:30am-1pm" },
  },
  {
    name: "Meng Chai Kopitiam",
    city: "Penang",
    area: "Butterworth",
    category: "breakfast",
    tier: 3,
    address: "Jalan Bagan Luar, 12000 Butterworth, Pulau Pinang",
    latitude: 5.3988,
    longitude: 100.3662,
    price_range: "$",
    what_to_order: [
      "Ah Hoe Beef Noodles — heritage in a bowl, tender beef slices in rich homemade broth",
      "Kaya toast",
      "Hainanese coffee",
    ],
    pro_tips: [
      "One of the oldest kopitiam in Butterworth",
      "The beef noodle stall inside is the main draw — generations old",
      "Pure local experience — no English menu, just point and order",
      "Cash only",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "7am-2pm" },
  },
  {
    name: "Raja Uda Night Market",
    city: "Penang",
    area: "Butterworth",
    category: "market",
    tier: 3,
    address: "Jalan Raja Uda, 12300 Butterworth, Pulau Pinang",
    latitude: 5.3910,
    longitude: 100.3785,
    price_range: "$",
    what_to_order: [
      "Satay skewers — grilled fresh on charcoal",
      "Ramly burgers",
      "Kuih and local snacks",
      "Fresh fruit juices",
    ],
    pro_tips: [
      "One of the biggest night markets on the mainland — massive during festive periods",
      "Mouthwatering street food at rock-bottom prices",
      "Genuinely local experience — tourist-free zone",
      "Cash only, bring small bills",
      "The CNY night market here is legendary — the biggest in Penang",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    opening_hours: { daily: "6pm-11pm" },
  },
  {
    name: "Mainland Seafood at Teluk Kumbar",
    city: "Penang",
    area: "Teluk Kumbar",
    category: "dinner",
    tier: 3,
    address: "Jalan Teluk Kumbar, 11920 Bayan Lepas, Pulau Pinang",
    latitude: 5.2950,
    longitude: 100.2310,
    price_range: "$$",
    what_to_order: [
      "Butter prawns — Penang-style with curry leaves and egg floss",
      "Salt and pepper squid",
      "Steamed fish with soy sauce",
      "Stir-fried clams with chili",
    ],
    pro_tips: [
      "Fishing village on Penang's south coast — the seafood here is as fresh as it gets",
      "Multiple seafood restaurants along the waterfront — pick one that's busy",
      "Less touristy than Batu Ferringhi — locals' spot for weekend seafood dinners",
      "Prices are reasonable for the freshness and portion sizes",
      "30-min drive from Georgetown — worth it for a seafood splurge",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "5pm-10:30pm" },
  },
  {
    name: "Snake Temple",
    city: "Penang",
    area: "Bayan Lepas",
    category: "activity",
    tier: 3,
    address: "Jalan Tokong Ular, 11900 Bayan Lepas, Pulau Pinang",
    latitude: 5.3170,
    longitude: 100.2650,
    price_range: "$",
    what_to_order: [
      "Entry: RM5 (Malaysians), RM10 (foreigners)",
      "Photo with a python: RM5-10 (optional — managed by handlers)",
    ],
    pro_tips: [
      "The only temple in the world with real pit vipers living on the altar — surreal",
      "The snakes are believed to be disciples of the deity — they're real and alive",
      "Safe to visit — the vipers are naturally docile from the incense smoke",
      "Near Penang Airport — good stop if you have time before/after a flight",
      "Takes about 20-30 minutes to see everything",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "6am-7pm" },
  },
  {
    name: "Balik Pulau Laksa",
    city: "Penang",
    area: "Balik Pulau",
    category: "lunch",
    tier: 2,
    address: "Pekan Balik Pulau, 11000 Balik Pulau, Pulau Pinang",
    latitude: 5.3535,
    longitude: 100.2205,
    price_range: "$",
    what_to_order: [
      "Balik Pulau laksa — a local variant of asam laksa, slightly different from the Georgetown version",
      "Nutmeg juice — Balik Pulau is nutmeg country",
    ],
    pro_tips: [
      "Balik Pulau is the rural 'back of the island' — durian orchards, paddy fields, fishing villages",
      "The laksa here has its own character — locals argue it's better than Air Itam",
      "Several stalls in the small town centre — just pick the busiest one",
      "During durian season (June-Aug), this is THE place to eat durian straight from the farms",
      "30-min drive from Georgetown — combine with a scenic drive around the island",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "8am-4pm" },
  },
  {
    name: "Nasi Kandar Deen Maju",
    city: "Penang",
    area: "Butterworth",
    category: "lunch",
    tier: 2,
    address: "Jalan Bagan Luar, 12000 Butterworth, Pulau Pinang",
    latitude: 5.3985,
    longitude: 100.3660,
    price_range: "$",
    what_to_order: [
      "Nasi kandar with mixed curries",
      "Fried chicken (ayam goreng)",
      "Roti canai",
    ],
    pro_tips: [
      "Mainland Penang's popular nasi kandar joint",
      "Less touristy than Georgetown — purely local crowd",
      "Cash only, cheap and filling",
      "Accessible from Butterworth ferry terminal",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "7am-10pm" },
  },
  {
    name: "Penang Bird Park",
    city: "Penang",
    area: "Seberang Jaya",
    category: "activity",
    tier: 2,
    address: "Jalan Todak, 13700 Seberang Jaya, Pulau Pinang",
    latitude: 5.3870,
    longitude: 100.4020,
    price_range: "$$",
    what_to_order: [
      "Entry: RM38 adults, RM20 children (MyKad discounts available)",
      "Bird feeding sessions",
      "Bird shows: 11:30am and 3:30pm daily",
    ],
    pro_tips: [
      "Malaysia's first and largest bird park — 300+ species, 3,000+ birds",
      "On the mainland in Seberang Jaya — easy drive from Butterworth ferry",
      "Great for families — the interactive bird shows are fun",
      "Allow 2-3 hours for the full experience",
      "Shaded walkways — manageable even in the heat",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "9am-6pm" },
  },
  {
    name: "Bukit Mertajam Recreational Forest",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "activity",
    tier: 3,
    address: "Jalan Kolam, 14000 Bukit Mertajam, Pulau Pinang",
    latitude: 5.3630,
    longitude: 100.4530,
    price_range: "$",
    what_to_order: [
      "Cherok Tokun hiking trail — 3.5 miles, 2-3 hours",
      "Free entry and free parking",
    ],
    pro_tips: [
      "Mainland Penang's best hiking — the tallest point at 545m with panoramic views",
      "Less crowded than Penang Hill — more of a real jungle hike",
      "Challenging trail with proper elevation — wear good shoes",
      "Good for birding — diverse wildlife in the rainforest",
      "Free parking, toilets, and a tea house at the trailhead",
      "Start early (7-8am) to beat the heat",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "7am-6pm" },
  },
  {
    name: "Seberang Perai Morning Market",
    city: "Penang",
    area: "Butterworth",
    category: "market",
    tier: 3,
    address: "Jalan Telaga Air, 13000 Butterworth, Pulau Pinang",
    latitude: 5.4000,
    longitude: 100.3700,
    price_range: "$",
    what_to_order: [
      "Fresh tropical fruits — cheaper than the island",
      "Kuih (traditional Malay cakes)",
      "Nasi lemak from the breakfast stalls",
    ],
    pro_tips: [
      "Mainland wet market — genuinely local, zero tourists",
      "Prices are noticeably cheaper than Georgetown markets",
      "Go before 9am for the best selection",
      "Cash only — ATMs nearby",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "5:30am-12pm" },
  },

  // ============================================
  // PENANG ISLAND MARKETS (from batch script)
  // ============================================
  {
    name: "Chowrasta Market",
    city: "Penang",
    area: "Georgetown",
    category: "market",
    tier: 1,
    address: "Jalan Chowrasta, George Town, 10100 Penang",
    latitude: 5.4168,
    longitude: 100.3316,
    price_range: "$",
    what_to_order: [
      "Nutmeg products — nutmeg juice, nutmeg oil, candied nutmeg (Penang specialty)",
      "Dried goods — dried shrimp, salted fish, belacan (shrimp paste)",
      "Fresh tropical fruits — durian (seasonal Jun-Aug), mangosteen, rambutan",
      "Kuih from the ground floor stalls — kuih lapis, kuih talam, ondeh ondeh",
      "Penang laksa from the hawker stalls on the fringe",
    ],
    what_to_skip: ["Tourist-priced pre-packaged souvenirs near the main entrance — buy loose from the auntie stalls inside"],
    pro_tips: [
      "Penang's oldest and most iconic wet market — operating since the 1890s",
      "Ground floor is wet market (produce, meat, fish), upper floor is dry goods and clothes",
      "Go before 10am for the full experience — stalls start packing up by noon",
      "The nutmeg products are unique to Penang — great souvenirs and cheaper than shops",
      "Combine with a walk along Jalan Penang and Komtar area",
      "The upper floor has interesting old-school fabric and tailor shops",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
    opening_hours: { daily: "6am-1pm" },
  },
  {
    name: "Gurney Drive Hawker Centre",
    city: "Penang",
    area: "Gurney Drive",
    category: "market",
    tier: 1,
    address: "172, Solok Gurney 1, Gurney Drive, 10250 Penang",
    latitude: 5.4370,
    longitude: 100.3105,
    price_range: "$",
    what_to_order: [
      "Char kuey teow — the wok hei (charred breath) here is legendary",
      "Assam laksa — sour, spicy fish broth with thick noodles, quintessential Penang",
      "Hokkien mee (prawn noodle soup) — rich pork and prawn broth",
      "Pasembur (Indian rojak) — deep-fried fritters with sweet potato sauce",
      "Lok lok — pick your skewers, they boil or fry them",
      "Ais kacang (ABC) — shaved ice with beans, jelly, corn, and syrup",
    ],
    what_to_skip: ["Avoid peak dinner rush (7-8pm) on weekends — the queues are brutal"],
    pro_tips: [
      "Relocated to a covered hawker centre off the main road — not on the seafront anymore",
      "Each stall specializes in one dish — hop between 3-4 stalls for a proper Penang feast",
      "Cash only at all stalls — bring small bills",
      "The char kuey teow stall with the longest queue is usually the right one",
      "Also excellent for dinner — most stalls open from late afternoon through evening",
      "About 10 min Grab from Georgetown's heritage core",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
    opening_hours: { daily: "5pm-11pm", note: "Some stalls also open for lunch" },
  },
  {
    name: "Cecil Street Market (Lebuh Cecil)",
    city: "Penang",
    area: "Georgetown",
    category: "market",
    tier: 2,
    address: "Lebuh Cecil, George Town, 10300 Penang",
    latitude: 5.4142,
    longitude: 100.3390,
    price_range: "$",
    what_to_order: [
      "Koay teow th'ng (flat rice noodle soup) — clear broth, simple perfection",
      "Char koay kak (fried rice cake cubes) — crispy, savoury, with egg and bean sprouts",
      "Popiah (fresh spring rolls) — filled with jicama, egg, and sweet sauce",
      "Chee cheong fun — steamed rice rolls with shrimp paste and sweet sauce",
      "Fresh seafood from the wet market stalls",
    ],
    pro_tips: [
      "A proper old-school Georgetown morning market — mostly locals, zero tourists",
      "The hawker stalls around the market are the real draw — arrive by 7:30am",
      "Cash only, most dishes RM3-8 — absurdly cheap for how good it is",
      "In the heart of Georgetown but off the tourist trail — feels authentic",
      "Combine with a walk through Little India (Lebuh Pasar) nearby",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.65,
    source: "manual",
    opening_hours: { daily: "6am-12pm" },
  },
  {
    name: "Pulau Tikus Market",
    city: "Penang",
    area: "Pulau Tikus",
    category: "market",
    tier: 2,
    address: "Jalan Pasar, Pulau Tikus, 10350 Penang",
    latitude: 5.4330,
    longitude: 100.3090,
    price_range: "$",
    what_to_order: [
      "Apom (coconut milk pancakes) — the signature Pulau Tikus snack, crispy edges, soft center",
      "Char kuey teow — several excellent stalls compete here",
      "Nasi kandar from the nearby stalls",
      "Fresh produce — the wet market section has excellent vegetables and seafood",
      "Kuih Nyonya — beautiful Peranakan cakes in pastel colours",
    ],
    pro_tips: [
      "A neighbourhood market in one of Georgetown's quieter residential areas",
      "Wednesday and Saturday mornings are busiest — the morning market attracts the best vendors",
      "The apom stall is legendary — old uncle makes them on a charcoal griddle",
      "More relaxed pace than Chowrasta — good for a leisurely breakfast explore",
      "Pulau Tikus is Georgetown's old-money neighbourhood — nice architecture in the area",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.65,
    source: "manual",
    opening_hours: { daily: "6am-12pm", note: "Best on Wed & Sat mornings" },
  },
  {
    name: "Batu Ferringhi Night Market",
    city: "Penang",
    area: "Batu Ferringhi",
    category: "market",
    tier: 2,
    address: "Jalan Batu Ferringhi, 11100 Penang",
    latitude: 5.4695,
    longitude: 100.2460,
    price_range: "$",
    what_to_order: [
      "Souvenirs — fake brand goods, phone cases, sunglasses (negotiate hard!)",
      "Batik clothing and sarongs",
      "Local handicrafts and paintings",
      "Snack stalls — satay, murtabak, fresh fruit shakes",
      "Custom caricature portraits",
    ],
    what_to_skip: ["Don't pay the first price — always negotiate, start at 50% of asking price"],
    pro_tips: [
      "Penang's most tourist-oriented night market — along the beach hotel strip",
      "NEGOTIATE EVERYTHING — first price is always 2-3x what they'll accept",
      "More shopping than food — come here for souvenirs, not dinner",
      "Runs every night along the main road — busiest on weekends",
      "About 30 min from Georgetown — combine with a beach day at Batu Ferringhi",
      "If you want authentic night market food, Gurney Drive is better",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    source: "manual",
    opening_hours: { daily: "7pm-11pm" },
  },
  {
    name: "Jelutong Market",
    city: "Penang",
    area: "Jelutong",
    category: "market",
    tier: 3,
    address: "Jalan Jelutong, 11600 Penang",
    latitude: 5.3990,
    longitude: 100.3180,
    price_range: "$",
    what_to_order: [
      "Curry mee — rich coconut curry broth with blood cubes and cockles",
      "Char kuey teow — a contender for best in Penang at the hawker stalls",
      "Fried oyster omelette (oh chien)",
      "Fresh seafood from the wet market",
      "Rojak — fruit salad with dark shrimp paste dressing",
    ],
    pro_tips: [
      "One of the biggest local markets on the island — very much a locals' market",
      "The hawker food around Jelutong is seriously underrated",
      "Go morning for wet market, evening for the hawker stalls nearby",
      "Between Georgetown and the airport — easy stop if you're heading south",
      "Cash only everywhere",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "6am-1pm" },
  },
  {
    name: "Nasi Kandar Deen Maju (Butterworth)",
    city: "Penang",
    area: "Butterworth",
    category: "lunch",
    tier: 2,
    address: "Jalan Bagan Luar, Butterworth, 12000 Seberang Perai",
    latitude: 5.3990,
    longitude: 100.3640,
    price_range: "$",
    what_to_order: [
      "Nasi kandar with kuah campur — point at curries, they pile them on rice",
      "Ayam goreng berempah (fried spiced chicken) — crispy and aromatic",
      "Ikan goreng (fried fish) with sambal",
      "Roti canai with dhal and fish curry",
      "Teh tarik — pulled tea, frothy and sweet",
    ],
    pro_tips: [
      "Mainland institution — locals on the island side actually cross the bridge for this",
      "The kuah campur (mixed curry gravy) is the secret — ask for extra, it's free",
      "Cash only, RM8-15 per person — incredible value",
      "Gets packed at lunch — go before 12 or after 2pm",
      "Right in Butterworth town — easy to reach from the ferry terminal",
    ],
    vibe: "chaotic",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.65,
    source: "manual",
    opening_hours: { daily: "7am-10pm" },
  },
  {
    name: "Hai Beng Coffee Shop (Kopitiam Hai Beng)",
    city: "Penang",
    area: "Butterworth",
    category: "breakfast",
    tier: 2,
    address: "3883, Jalan Bagan Luar, 12000 Butterworth, Seberang Perai",
    latitude: 5.3988,
    longitude: 100.3635,
    price_range: "$",
    what_to_order: [
      "Kaya toast with butter — charcoal-toasted, warm and crispy",
      "Soft-boiled eggs with soy sauce and white pepper",
      "Hainanese coffee (kopi) — thick, dark, aromatic old-school brew",
      "Roti bakar (toasted bread) with peanut butter",
    ],
    pro_tips: [
      "Heritage kopitiam vibes — old marble tables, wooden chairs, ceiling fans",
      "The kopi is brewed the old-school way — with a sock filter and margarine-roasted beans",
      "Go before 9am for the full morning kopitiam experience",
      "A proper Butterworth local institution — this is how Malaysians start their day",
      "Cash only, breakfast for RM5-8 per person",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "6:30am-2pm" },
  },
  {
    name: "Restoran Melayu (Nasi Lemak Butterworth)",
    city: "Penang",
    area: "Butterworth",
    category: "breakfast",
    tier: 3,
    address: "Jalan Bagan Luar, Butterworth, 12000 Seberang Perai",
    latitude: 5.3985,
    longitude: 100.3638,
    price_range: "$",
    what_to_order: [
      "Nasi lemak with sambal sotong (spicy squid) — the mainland version hits different",
      "Nasi lemak with ayam rendang",
      "Mee goreng mamak — fried noodles with egg, tofu, and shrimp",
      "Roti canai with dhal",
    ],
    pro_tips: [
      "One of several excellent Malay breakfast spots clustered in central Butterworth",
      "The nasi lemak sambal here has a slightly sweeter Penang-style profile",
      "Very cheap — RM5-10 for a full breakfast",
      "Cash only, no frills — just honest food at honest prices",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "6am-1pm" },
  },
  {
    name: "Taiping Famous Cendol (Seberang Jaya branch)",
    city: "Penang",
    area: "Seberang Jaya",
    category: "lunch",
    tier: 2,
    address: "Jalan Todak 2, Pusat Bandar Seberang Jaya, 13700 Perai",
    latitude: 5.3860,
    longitude: 100.3980,
    price_range: "$",
    what_to_order: [
      "Cendol — green pandan jelly noodles, coconut milk, gula melaka (palm sugar), red beans, shaved ice",
      "Cendol pulut — upgraded version with glutinous rice, richer and more filling",
      "Rojak — fruit salad with dark prawn paste dressing (if available)",
    ],
    pro_tips: [
      "Taiping is famous for cendol — this branch brings the Taiping style to Seberang Perai",
      "The gula melaka (palm sugar) is the star — dark, caramelized, impossibly fragrant",
      "RM3-5 per bowl — one of the best desserts in Malaysia for almost nothing",
      "Perfect afternoon pick-me-up in the Penang heat",
      "Combine with other Seberang Jaya spots",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "10am-6pm" },
  },
  {
    name: "Ah Kow Kopitiam",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "breakfast",
    tier: 2,
    address: "Jalan Pasar, Bukit Mertajam, 14000 Seberang Perai",
    latitude: 5.3635,
    longitude: 100.4600,
    price_range: "$",
    what_to_order: [
      "Kaya toast set — charcoal-grilled bread, homemade kaya (coconut jam), butter, soft eggs",
      "White coffee — BM-style, lighter roast than typical kopitiam coffee",
      "Chee cheong fun (steamed rice rolls) — with shrimp paste and sweet sauce",
      "Wan tan mee (wonton noodles) — springy noodles with char siu",
    ],
    pro_tips: [
      "Bukit Mertajam (BM) has its own food culture distinct from Georgetown",
      "BM's kopitiams are famous across Penang — some say better than island side",
      "Heritage kopitiam atmosphere — marble-top tables, old-school tiled floors",
      "Cash only, breakfast runs RM5-8 per person",
      "Combine with Bukit Mertajam hiking if you're an early riser",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "6:30am-2pm" },
  },
  {
    name: "Hai Boey Seafood (Teluk Kumbar style, Butterworth)",
    city: "Penang",
    area: "Butterworth",
    category: "dinner",
    tier: 2,
    address: "Jalan Chain Ferry, Butterworth, 12100 Seberang Perai",
    latitude: 5.4065,
    longitude: 100.3580,
    price_range: "$$",
    what_to_order: [
      "Butter cream prawns — crispy deep-fried with curry leaves and chili",
      "Kam heong clams — stir-fried with dried shrimp, curry leaves, chili",
      "Steamed fish with soy sauce — whole fish, fresh from the strait",
      "Salted egg squid — crispy battered squid with rich salted egg yolk sauce",
      "Fried rice to mop up all the sauces",
    ],
    pro_tips: [
      "Mainland seafood restaurants are cheaper and often fresher than island-side equivalents",
      "Order 2-3 dishes to share for 2-4 people — Malaysian style",
      "RM60-100 for 2 people with seafood — much better value than Georgetown",
      "Ask what's fresh today — the catch changes daily",
      "Near the Butterworth ferry terminal area — good post-ferry dinner spot",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "5pm-11pm" },
  },
  {
    name: "Pasar Malam Butterworth (Butterworth Night Market)",
    city: "Penang",
    area: "Butterworth",
    category: "dinner",
    tier: 2,
    address: "Jalan Bagan Luar, Butterworth, 12000 Seberang Perai",
    latitude: 5.3992,
    longitude: 100.3645,
    price_range: "$",
    what_to_order: [
      "Murtabak — stuffed pan-fried flatbread with minced meat, egg, and onion",
      "Ayam percik — flame-grilled chicken with sweet coconut glaze",
      "Apam balik — crispy pancake with crushed peanuts, sugar, and sweet corn",
      "Satay — grilled chicken or beef skewers with peanut sauce",
      "Air tebu (fresh sugarcane juice) — essential in the heat",
    ],
    pro_tips: [
      "Butterworth's main night market — rotates through different locations on different days",
      "Much less touristy than island-side pasar malams — genuinely local crowd",
      "Cash only, budget RM15-25 for a feast",
      "The ayam percik stalls are worth seeking out — grilled over charcoal",
      "Check locally for which night the market is in the Bagan Luar area",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "5pm-11pm", note: "Rotating locations — check locally" },
  },
  {
    name: "Restaurant Sungai Dua Seafood",
    city: "Penang",
    area: "Seberang Jaya",
    category: "dinner",
    tier: 3,
    address: "Jalan Sungai Dua, 13800 Butterworth, Seberang Perai",
    latitude: 5.3750,
    longitude: 100.4050,
    price_range: "$$",
    what_to_order: [
      "Steamed siakap (barramundi) with soy — simple, showcases the fresh fish",
      "Butter prawns — crispy with egg floss and curry leaves",
      "Stir-fried kangkung belacan (morning glory with shrimp paste)",
      "Salt and pepper mantis prawns — when in season, a must-order",
    ],
    pro_tips: [
      "Large Chinese-style seafood restaurant — typical mainland dining experience",
      "Prices are 20-30% cheaper than equivalent places on the island",
      "Good for groups — order family-style and share everything",
      "RM80-120 for 3-4 people with seafood — very reasonable",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "11am-10pm" },
  },
  {
    name: "Penang Bird Park",
    city: "Penang",
    area: "Seberang Jaya",
    category: "activity",
    tier: 2,
    address: "Jalan Todak, Seberang Jaya, 13700 Perai, Seberang Perai",
    latitude: 5.3870,
    longitude: 100.3975,
    price_range: "$",
    what_to_order: [
      "Entry: RM25 adults / RM15 children",
      "Bird feeding sessions — schedule varies, ask at entrance",
      "Walk-through aviary with hornbills, flamingos, parrots",
      "Photo with the macaws — they're trained and friendly",
    ],
    pro_tips: [
      "Mainland's best family-friendly attraction — over 300 species of birds",
      "Not as large as KL Bird Park but much less crowded and more intimate",
      "Go in the morning (9-11am) when birds are most active",
      "About 2 hours to explore thoroughly",
      "Easy to reach — 10 min drive from Butterworth, near the Penang Bridge",
      "Bring insect repellent — it's tropical gardens, mosquitoes are real",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    source: "manual",
    opening_hours: { daily: "9am-5pm" },
  },
  {
    name: "Bukit Mertajam Recreational Forest",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "activity",
    tier: 2,
    address: "Hutan Lipur Bukit Mertajam, 14000 Bukit Mertajam, Seberang Perai",
    latitude: 5.3520,
    longitude: 100.4580,
    price_range: "$",
    what_to_order: [
      "Free entry to the recreational forest area",
      "Hiking trails — Summit Trail (challenging, 2-3 hrs) or Waterfall Trail (easy, 1 hr)",
      "Natural waterfall and swimming pools at the base",
      "Durian orchards on the lower slopes (seasonal Jun-Aug)",
    ],
    pro_tips: [
      "The mainland's best hiking destination — 445m peak with views of Penang Island",
      "Start early (7am) to avoid the midday heat — jungle is humid",
      "The summit trail is steep but rewarding — bring 2L water minimum",
      "The lower waterfall area is great for a casual dip — bring a towel",
      "Macaques (monkeys) are common — don't bring visible food",
      "About 30 min drive from Butterworth — Grab or drive",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    source: "manual",
    opening_hours: { daily: "7am-6pm" },
  },
  {
    name: "Kek Lok Si Temple (Mainland Approach)",
    city: "Penang",
    area: "Air Itam",
    category: "activity",
    tier: 1,
    address: "Kek Lok Si Temple, Air Itam, 11500 Penang",
    latitude: 5.4005,
    longitude: 100.2730,
    price_range: "$",
    what_to_order: [
      "Free entry to temple grounds (pagoda RM2, cable car to Kuan Yin statue RM4)",
      "Climb the Pagoda of Ten Thousand Buddhas — 7 storeys mixing Chinese, Thai, Burmese architecture",
      "Take the inclined lift to the massive Kuan Yin bronze statue",
      "Buy incense and prayer items at the base stalls",
    ],
    pro_tips: [
      "Southeast Asia's largest Buddhist temple — absolutely massive complex",
      "The pagoda blends Chinese, Thai, and Burmese architectural styles — unique in the world",
      "During Chinese New Year (Jan/Feb), the entire temple is lit with thousands of lanterns — spectacular",
      "Go early morning (8am) to beat the tour bus crowds",
      "Wear comfortable shoes — LOTS of steps to climb",
      "Combine with Air Itam laksa (famous stall right at the base of the hill)",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    source: "manual",
    opening_hours: { daily: "8:30am-5:30pm" },
  },
  {
    name: "Snake Temple (Temple of the Azure Cloud)",
    city: "Penang",
    area: "Bayan Lepas",
    category: "activity",
    tier: 3,
    address: "Jalan Tokong Ular, Bayan Lepas, 11900 Penang",
    latitude: 5.3165,
    longitude: 100.2720,
    price_range: "$",
    what_to_order: [
      "Free temple entry (photo with snake RM5 donation)",
      "View the pit vipers that live freely on the altars — yes, real snakes",
      "Incense and prayer offerings",
    ],
    pro_tips: [
      "Unique temple where pit vipers live on the altars — supposedly kept docile by incense smoke",
      "The snakes are real and venomous but sedated by the incense — still, be respectful and cautious",
      "Near the airport — good stop if you have time before a flight",
      "Quick visit — 30-45 minutes is enough",
      "More snakes visible in the early morning when it's cooler",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.65,
    source: "manual",
    opening_hours: { daily: "6am-7pm" },
  },
  {
    name: "Bukit Mertajam Chinese Temple (Dou Mu Gong)",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "activity",
    tier: 3,
    address: "Jalan Kulim, Bukit Mertajam, 14000 Seberang Perai",
    latitude: 5.3605,
    longitude: 100.4625,
    price_range: "$",
    what_to_order: [
      "Free entry",
      "Walk through the ornate temple complex — multi-tiered Chinese architecture",
      "Nine Emperor Gods Festival (late Sep/Oct) — spectacular processions if your timing aligns",
    ],
    pro_tips: [
      "One of the most important Nine Emperor Gods temples in Malaysia",
      "Beautiful traditional Chinese architecture — worth a quick visit if you're in BM",
      "The Nine Emperor Gods Festival (9th month lunar calendar, Sep/Oct) transforms this area",
      "Combine with Bukit Mertajam hiking and kopitiam breakfast",
      "Free to visit, about 20-30 minutes to explore",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "7am-5pm" },
  },
  {
    name: "Pasar Awam Butterworth (Butterworth Wet Market)",
    city: "Penang",
    area: "Butterworth",
    category: "market",
    tier: 2,
    address: "Jalan Bagan Luar, Butterworth, 12000 Seberang Perai",
    latitude: 5.3995,
    longitude: 100.3642,
    price_range: "$",
    what_to_order: [
      "Fresh seafood — prawns, fish, crabs straight from the Penang Strait",
      "Kuih Melayu — traditional Malay cakes and snacks from the morning vendors",
      "Fresh tropical fruits — mangosteen, rambutan, durian (seasonal)",
      "Nasi lemak breakfast packets from the stalls around the market",
      "Dried goods — belacan, dried shrimp, spices",
    ],
    pro_tips: [
      "The main wet market for Butterworth — busiest between 6-9am",
      "Seafood is notably cheaper than island-side markets",
      "The hawker stalls surrounding the market are excellent for breakfast",
      "Cash only, bring small bills",
      "Very local — minimal English, but pointing and smiling works fine",
      "Near the Butterworth ferry terminal — easy to combine with a ferry ride to Georgetown",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.65,
    source: "manual",
    opening_hours: { daily: "5am-12pm" },
  },
  {
    name: "Pasar Pagi Bukit Mertajam (BM Morning Market)",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "market",
    tier: 3,
    address: "Jalan Pasar, Bukit Mertajam, 14000 Seberang Perai",
    latitude: 5.3630,
    longitude: 100.4605,
    price_range: "$",
    what_to_order: [
      "BM-style kuih — local cakes that are slightly different from island versions",
      "Fresh fruits and vegetables — excellent quality, lower prices than Georgetown",
      "Nasi lemak and roti canai from the hawker stalls",
      "Dried seafood and spices",
      "Chee cheong fun from the market stalls",
    ],
    pro_tips: [
      "Bukit Mertajam's central morning market — the hub of mainland Penang food culture",
      "BM has its own distinct food identity — worth exploring if you're on the mainland",
      "Go before 9am for the full market experience",
      "Cash only, very affordable — RM5-8 for a full breakfast from hawker stalls",
      "Combine with BM kopitiam breakfast and a hike up Bukit Mertajam",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "5:30am-12pm" },
  },
  {
    name: "Perai Morning Market",
    city: "Penang",
    area: "Perai",
    category: "market",
    tier: 3,
    address: "Jalan Perai Jaya 2, Perai, 13600 Seberang Perai",
    latitude: 5.3830,
    longitude: 100.3950,
    price_range: "$",
    what_to_order: [
      "Fresh seafood — perai fishermen bring the morning catch directly here",
      "Indian Muslim food stalls — roti canai, nasi kandar, murtabak",
      "Fresh vegetables and herbs — lemongrass, pandan, galangal",
      "Malay kuih and snacks",
    ],
    pro_tips: [
      "Industrial-area morning market — absolutely zero tourists, pure local experience",
      "The Indian Muslim food stalls here are excellent — Perai has a significant Indian community",
      "Cash only, very cheap",
      "Near the Perai industrial zone — not pretty, but the food is honest",
      "Go between 6-9am for peak activity",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.6,
    source: "manual",
    opening_hours: { daily: "5am-11am" },
  },

  // ============================================
  // MAINLAND — BUKIT MERTAJAM (ADDITIONAL)
  // ============================================
  {
    name: "BM Cathay Pancake",
    city: "Penang",
    area: "Bukit Mertajam",
    category: "market",
    tier: 2,
    address: "8, Jalan Aston, 14000 Bukit Mertajam",
    latitude: 5.3636,
    longitude: 100.4648,
    price_range: "$",
    what_to_order: [
      "Classic peanut apam balik (RM1.20/piece)",
      "Chocolate and banana pancake",
    ],
    pro_tips: [
      "Michelin Guide recognized — charcoal-grilled pancakes since 1962",
      "Only one dish: apam balik (ban chang kuih) — crispy outside, chewy inside",
      "Charcoal-grilled on the spot by the cart outside Cathay Food Court",
      "Closed Thursday and Friday",
      "60+ years of history — a true Bukit Mertajam institution",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "noon-5pm", closed: "Thursday, Friday" },
  },
];
