// Petaling Jaya & Greater KL suburban spots (27)

export const spots = [
  // ============================================
  // BREAKFAST / BRUNCH
  // ============================================
  {
    name: "Village Park Restaurant",
    city: "Petaling Jaya",
    area: "Damansara Utama",
    category: "breakfast",
    tier: 1,
    address: "5, Jalan SS 21/37, Damansara Utama",
    latitude: 3.1340,
    longitude: 101.6235,
    price_range: "$",
    what_to_order: ["Nasi lemak with ayam goreng berempah", "Add sambal on the side"],
    what_to_skip: ["Western items — come here for the nasi lemak only"],
    pro_tips: [
      "Go before 9am on weekends or queue for 30+ minutes",
      "The ayam goreng is crispy outside, juicy inside — the benchmark",
      "Take away if the queue is crazy — same taste",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.95,
    opening_hours: { daily: "6:30am-1:30pm", closed: "Tuesday" },
  },

  // ============================================
  // SUBURBAN — PJ, Subang, Mont Kiara
  // ============================================
  {
    name: "SS2 Wai Sek Kai",
    city: "Petaling Jaya",
    area: "SS2",
    category: "dinner",
    tier: 2,
    address: "Jalan SS 2/10, Petaling Jaya",
    latitude: 3.1186,
    longitude: 101.6214,
    price_range: "$",
    what_to_order: ["Char kuey teow", "Fried oyster omelette", "Lok lok (skewer hotpot)"],
    pro_tips: [
      "PJ's most famous hawker street — local families eat here nightly",
      "Go for the char kuey teow stall and the lok lok (pick your skewers, they cook them)",
      "Cash only at all stalls",
      "Gets packed after 7pm — go slightly early for the best choice",
      "20 min Grab from KL city center",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "5pm-midnight" },
  },
  {
    name: "Damansara Uptown Hawker Stalls",
    city: "Petaling Jaya",
    area: "Damansara Utama",
    category: "dinner",
    tier: 2,
    address: "Jalan SS 21/56B, Damansara Utama",
    latitude: 3.1340,
    longitude: 101.6244,
    price_range: "$",
    what_to_order: ["Hokkien mee (dark version)", "Grilled fish", "Thai-style tom yum"],
    pro_tips: [
      "A cluster of open-air hawker stalls that comes alive at night",
      "The vibe is very local PJ — not a tourist in sight",
      "Pair with a visit to Village Park (breakfast) since they're in the same area",
      "Cash only for most stalls",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-midnight" },
  },
  {
    name: "Jaya One Food Court",
    city: "Petaling Jaya",
    area: "Section 13",
    category: "lunch",
    tier: 3,
    address: "72A, Jalan Universiti, Section 13, PJ",
    latitude: 3.1124,
    longitude: 101.6372,
    price_range: "$",
    what_to_order: ["Pan mee", "Claypot chicken rice", "Thai food stall"],
    pro_tips: [
      "Solid suburban food court if you're in the PJ area",
      "The pan mee stall is standout — thick, chewy noodles with anchovy broth",
      "Air-conditioned — good escape from the heat",
      "Near the university area, gets busy at lunch",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "8am-10pm" },
  },

  // ============================================
  // NEW BATCH — PJ OLD TOWN & SECTION 17
  // ============================================
  {
    name: "PJ Old Town Hawker Centre (Gerai Seong Kee)",
    city: "Petaling Jaya",
    area: "PJ Old Town",
    category: "lunch",
    tier: 2,
    address: "Stall 35, Taman Selera, Jalan Othman, 46000 Petaling Jaya",
    latitude: 3.1027,
    longitude: 101.6389,
    price_range: "$",
    what_to_order: ["Yong tau foo (refried style)", "Hakka abacus seeds", "Wonton mee"],
    pro_tips: [
      "Gerai Seong Kee is the standout — 30+ years of Hakka yong tau foo",
      "They refry the yong tau foo before serving, which is uncommon and delicious",
      "PJ's heritage hawker centre with 63-year history",
      "Cash only at all stalls",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "11:30am-7pm", closed: "Monday" },
  },
  {
    name: "Grub by Ahong & Friends",
    city: "Petaling Jaya",
    area: "Section 17",
    category: "dinner",
    tier: 2,
    address: "608, Jalan 17/10, Seksyen 17, 46400 Petaling Jaya",
    latitude: 3.1106,
    longitude: 101.6384,
    price_range: "$$",
    what_to_order: ["Steaks", "Western comfort food"],
    pro_tips: [
      "Self-service drinks and cutlery to keep prices low",
      "Reservations recommended — RM15/person no-show charge",
      "Order by pencil and paper at your table",
      "One of PJ Section 17's most popular dinner spots",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "11am-3pm, 5pm-10pm", closed: "Monday" },
  },
  {
    name: "Isan Kaya",
    city: "Petaling Jaya",
    area: "Section 17",
    category: "dinner",
    tier: 2,
    address: "22A, Jalan 17/54, Seksyen 17, 46400 Petaling Jaya",
    latitude: 3.1096,
    longitude: 101.6352,
    price_range: "$$$",
    what_to_order: [
      "Wagyu beef tartare with cili padi and lemongrass",
      "Sauna prawns (steamed with sake)",
      "Fried chicken karaage",
      "Asam boi sake cocktail",
    ],
    pro_tips: [
      "Tokyo meets Bangkok — fusion restobar from the creators of Bangsar's Last Project",
      "Great cocktail bar with sake-based drinks",
      "Spray-painted graffiti interior — Instagram-worthy",
      "Check their Instagram for current hours before visiting",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
  },

  // ============================================
  // NEW BATCH — DAMANSARA & UPTOWN
  // ============================================
  {
    name: "Say Yes Cafe",
    city: "Petaling Jaya",
    area: "Damansara Utama",
    category: "breakfast",
    tier: 3,
    address: "97, Jalan SS 21/37, Damansara Utama, 47400 Petaling Jaya",
    latitude: 3.1340,
    longitude: 101.6226,
    price_range: "$",
    what_to_order: ["Nasi lemak", "Chee cheong fun", "Pulut"],
    pro_tips: [
      "Budget-friendly kopitiam with traditional Malaysian breakfast",
      "Near Village Park but without the insane queue",
      "Good chee cheong fun — silky smooth rice rolls",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { monday: "7:30am-4:30pm", tuesday_to_sunday: "7:30am-10pm" },
  },
  {
    name: "Ah Keong Yong Tau Foo",
    city: "Petaling Jaya",
    area: "Damansara Utama",
    category: "dinner",
    tier: 2,
    address: "Stall 1097, Damansara Uptown Hawker Centre, Jalan SS 21/39, 47400 Petaling Jaya",
    latitude: 3.1342,
    longitude: 101.6251,
    price_range: "$",
    what_to_order: ["Fried yong tau too (refried for extra crunch)", "Cheese tofu", "Stuffed fuchuk"],
    pro_tips: [
      "Been here since 1990 — the OG of Damansara Uptown",
      "They refry the YTF before serving — crispy outside, soft inside",
      "Cheese tofu is their unique twist — not found at most YTF stalls",
      "Night market vibe — opens at 7pm, goes till 1am",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "7pm-1am" },
  },
  {
    name: "Common Feed",
    city: "Petaling Jaya",
    area: "Damansara Utama",
    category: "lunch",
    tier: 2,
    address: "115G, Jalan SS 21/37, Damansara Utama, 47400 Petaling Jaya",
    latitude: 3.1340,
    longitude: 101.6232,
    price_range: "$$",
    what_to_order: [
      "Focaccia sandwich set (RM23-29 with coffee)",
      "Neapolitan pizza",
      "Anchovy & Porcini Burro pasta",
    ],
    pro_tips: [
      "Italian-Spanish restaurant and deli — fresh-baked focaccia daily",
      "Lunch sets are great value — focaccia sandwich + iced tea or coffee",
      "Fresh pasta for dinner, dry pasta for lunch",
      "Also sells Italian charcuterie and Spanish canned seafood to take home",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "11am-3:30pm, 5:30pm-10pm", closed: "Monday" },
  },
  {
    name: "Curbside Cantina",
    city: "Petaling Jaya",
    area: "Damansara Kim",
    category: "lunch",
    tier: 2,
    address: "71, Jalan SS 20/11, Damansara Kim, 47400 Petaling Jaya",
    latitude: 3.1264,
    longitude: 101.6264,
    price_range: "$",
    what_to_order: ["Fish tacos", "Lamb tacos", "Melted nachos with cheese and bean dip"],
    pro_tips: [
      "Started as a food truck — now a permanent taqueria in Damansara Kim",
      "The OG of tacos in KL — been around for years",
      "Small shop, limited seats — takeaway is an option",
      "Closes at 8pm so plan accordingly",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "noon-8pm", closed: "Wednesday" },
  },

  // ============================================
  // NEW BATCH — MUTIARA DAMANSARA & ARA DAMANSARA
  // ============================================
  {
    name: "Ling's Focacceria",
    city: "Petaling Jaya",
    area: "Mutiara Damansara",
    category: "cafe",
    tier: 2,
    address: "25, Jalan PJU 7/16, Mutiara Damansara, 48100 Petaling Jaya",
    latitude: 3.1594,
    longitude: 101.6126,
    price_range: "$$",
    what_to_order: [
      "All-the-Meats sandwich (RM36)",
      "Kimchi grilled cheese focaccia",
      "Miso butter focaccia loaf",
      "Focaccia soldiers with onsen eggs",
    ],
    pro_tips: [
      "Dedicated focaccia bakery — everything is built around the bread",
      "Loaves come in wild flavours: miso butter, honey & sesame seeds",
      "Roman-style schiacciata flatbread 'pizzas' for lunch",
      "Small shophouse — gets packed at lunch",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
  },
  {
    name: "Inoha Cafe",
    city: "Petaling Jaya",
    area: "Ara Damansara",
    category: "cafe",
    tier: 3,
    address: "16, Block J, Taipan 2 Damansara, Jalan PJU 1a/1, Ara Damansara, 47301 Petaling Jaya",
    latitude: 3.1125,
    longitude: 101.5929,
    price_range: "$$",
    what_to_order: [
      "Zesty Yuzu Steak Bowl",
      "Citrus Harvest Salmon Bowl",
      "Single origin coffee",
      "Matcha Strawberry Latte",
    ],
    pro_tips: [
      "Japanese-inspired cafe — airy daytime vibes, cosy at night",
      "Good specialty coffee with Japanese-influenced food bowls",
      "Street parking available along the shophouse row",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
  },
  {
    name: "Xin Teochew Seafood Porridge & Noodle",
    city: "Petaling Jaya",
    area: "Sunway Mas",
    category: "lunch",
    tier: 2,
    address: "16-1, Jalan PJU 1/3a, Sunway Mas Commercial Centre, 47301 Petaling Jaya",
    latitude: 3.1436,
    longitude: 101.6127,
    price_range: "$",
    what_to_order: [
      "Fish head noodles in clear broth",
      "Poached baby octopus",
      "Fish offal noodles (adventurous but delicious)",
    ],
    pro_tips: [
      "Teochew-style seafood noodles — clean, light broth with super fresh fish",
      "The fish offal (maw, roe, intestine) is for the adventurous — but worth trying",
      "Get there early — popular items sell out by early afternoon",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "8:30am-9pm" },
  },

  // ============================================
  // NEW BATCH — AMAN SURIA & SECTION 19
  // ============================================
  {
    name: "Betty's Midwest Kitchen",
    city: "Petaling Jaya",
    area: "Aman Suria",
    category: "dinner",
    tier: 2,
    address: "A-G-40, Jalan PJU 1/43, Aman Suria, 47301 Petaling Jaya",
    latitude: 3.1402,
    longitude: 101.6094,
    price_range: "$$",
    what_to_order: ["Pork ribs", "Classic burger", "Chicken sandwich"],
    what_to_skip: ["Don't come for fine dining — it's hearty, no-frills American comfort food"],
    pro_tips: [
      "Run by a family who lived in America — authentic Midwest home cooking",
      "Cozy American-themed spot — feels like eating at someone's house",
      "Non-halal — pork ribs are the star",
      "Closed Mondays",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "11:30am-3pm, 5:30pm-10pm", closed: "Monday" },
  },
  {
    name: "THB Bistronome",
    city: "Petaling Jaya",
    area: "Section 19",
    category: "dinner",
    tier: 2,
    address: "Mezzanine Floor, Menara Access World 1, Jalan 19/13, Section 19, 46300 Petaling Jaya",
    latitude: 3.0968,
    longitude: 101.6517,
    price_range: "$$",
    what_to_order: [
      "Omelet Souffle (RM35) — crispy French soufflé meets Thai omelette",
      "Escargots (RM25)",
      "Lemongrass brioche",
      "Signature roast duck",
    ],
    pro_tips: [
      "Thai food through a French lens — unique fusion concept",
      "The omelet souffle is their signature — crispy golden bits on a cloud-like centre",
      "Weekend brunch from 11am is popular",
      "In a commercial building — easy to miss, look for the mezzanine floor",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { weekday: "9am-10pm", weekend: "11am-11pm" },
  },

  // ============================================
  // NEW BATCH — TAMAN MEGAH & SS2
  // ============================================
  {
    name: "Staple Dough",
    city: "Petaling Jaya",
    area: "Taman Megah",
    category: "dinner",
    tier: 2,
    address: "Lot G2, Megah Rise, 3 Jalan SS 24/9, Taman Megah, 47301 Petaling Jaya",
    latitude: 3.1132,
    longitude: 101.6157,
    price_range: "$$",
    what_to_order: [
      "Pici Carbonara (RM39)",
      "Prawn & Chorizo Tagliolini (RM49)",
      "Stuffed Seafood Capelletti",
    ],
    pro_tips: [
      "All pasta is handmade fresh — you can taste the difference",
      "Menu is split: low carbs, handmade pastas (high carbs), and desserts",
      "In the new Megah Rise Mall — easy parking",
      "Reservations recommended for dinner",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "noon-3pm, 6pm-10pm" },
  },
  {
    name: "Luckypot",
    city: "Petaling Jaya",
    area: "SS2",
    category: "dinner",
    tier: 2,
    address: "185, Jalan SS 2/24, SS 2, 47300 Petaling Jaya",
    latitude: 3.1178,
    longitude: 101.6188,
    price_range: "$$",
    what_to_order: [
      "La Zi Ji (spicy chicken)",
      "Cumin lamb",
      "Sichuan boiled fish",
      "BBQ skewers",
    ],
    pro_tips: [
      "Hunan and Sichuan cuisine — bring your spice tolerance",
      "The La Zi Ji is buried under a mountain of dried chillies — iconic",
      "Also has a branch in Kepong if SS2 is too far",
      "Reservations recommended for dinner — gets packed",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "noon-3pm, 5pm-10pm" },
  },

  // ============================================
  // NEW BATCH — SUBANG JAYA & BANDAR SUNWAY
  // ============================================
  {
    name: "Moon Fish Head Kitchen",
    city: "Petaling Jaya",
    area: "Subang Jaya",
    category: "breakfast",
    tier: 2,
    address: "11, Jalan USJ 1/1b, Taman Subang Mewah, 47620 Subang Jaya",
    latitude: 3.0452,
    longitude: 101.5866,
    price_range: "$",
    what_to_order: ["Milk-based fish head noodles", "Fish noodles in pork bone soup"],
    pro_tips: [
      "The milk-based fish head broth is rich, creamy, and unique",
      "Opens early, closes by 3pm — go for brunch",
      "Closed Mondays — don't show up on a Monday",
      "Cash only",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "8:30am-3pm", closed: "Monday" },
  },
  {
    name: "Fawwaz Roti Canai",
    city: "Petaling Jaya",
    area: "Subang Jaya",
    category: "breakfast",
    tier: 2,
    address: "No. 1, Block G, Jalan SS 13/1G, Subang Jaya",
    latitude: 3.0793,
    longitude: 101.5973,
    price_range: "$",
    what_to_order: [
      "Roti canai gebu (fluffy roti — RM1.50)",
      "Roti telur (RM3)",
      "Roti pisang (RM3)",
    ],
    pro_tips: [
      "The roti gebu nickname says it all — incredibly soft and fluffy",
      "Fawwaz has 20+ years of roti-making experience",
      "Morning only — closes by 12:30pm",
      "Dhal with onions is the perfect companion",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "7am-12:30pm" },
  },
  {
    name: "Nasi Lemak Shop",
    city: "Petaling Jaya",
    area: "Subang Jaya",
    category: "lunch",
    tier: 3,
    address: "G12, Courtyard, Jalan SS 15/4G, SS 15, 47500 Subang Jaya",
    latitude: 3.0781,
    longitude: 101.5886,
    price_range: "$",
    what_to_order: ["Nasi lemak ayam goreng (RM16.90)", "Curry chicken (RM9.90)"],
    pro_tips: [
      "Viral nasi lemak chain — this is the SS15 outlet",
      "Flagship is in Bandar Utama",
      "Open till 10pm — rare for a nasi lemak spot",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "10am-10pm" },
  },
  {
    name: "Maisen Tonkatsu",
    city: "Petaling Jaya",
    area: "Bandar Sunway",
    category: "lunch",
    tier: 2,
    address: "LG1.45, Sunway Pyramid Mall, 3 Jalan PJS 11/15, Bandar Sunway, 47500 Subang Jaya",
    latitude: 3.0713,
    longitude: 101.6073,
    price_range: "$$",
    what_to_order: [
      "Tenderloin tonkatsu set",
      "Hire katsu (pork fillet)",
    ],
    pro_tips: [
      "Japan's #1 tonkatsu chain — first Malaysia outlet",
      "Refillable rice, cabbage, and miso soup with every set",
      "Kids meal is great value at RM19",
      "Expect RM100+ for two sets with drinks",
    ],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "10:30am-10pm" },
  },
  {
    name: "Sot Bab",
    city: "Petaling Jaya",
    area: "Bandar Sunway",
    category: "dinner",
    tier: 2,
    address: "E-01-03A, Sunway Geo Avenue, Jalan Lagoon Selatan, Bandar Sunway, 47500 Subang Jaya",
    latitude: 3.0668,
    longitude: 101.6048,
    price_range: "$$",
    what_to_order: ["Korean pot rice meals", "Marinated crab (ganjang gejang)"],
    pro_tips: [
      "Run by an actual ajumma (Korean grandma) — everything is homemade",
      "The marinated crab is the star — sweet, briny, rich",
      "Korean pot rice (sotbap) is cooked to order — crispy bottom",
      "Non-halal",
    ],
    vibe: "casual",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "11:30am-10pm", closed: "Monday" },
  },

  // ============================================
  // NEW BATCH — KLANG
  // ============================================
  {
    name: "Boston Lala (Restoran Boston Baru)",
    city: "Petaling Jaya",
    area: "Klang",
    category: "dinner",
    tier: 1,
    address: "1E & 1F, Jalan Kapar, Kawasan 18, 41000 Klang",
    latitude: 3.0465,
    longitude: 101.4466,
    price_range: "$$",
    what_to_order: [
      "Steamed lala in superior soup — the signature",
      "Nestum prawns",
      "Nestum mantis prawns",
      "Hokkien mee",
      "Moonlight koay teow",
    ],
    pro_tips: [
      "Klang's single most famous restaurant — people drive from all over KL",
      "Arrive by 4:45pm for a chance at a table — it fills up FAST",
      "The lala in superior soup is life-changing — rich, garlicky, savoury",
      "Cash only — no card payment",
      "Closed on random days — call ahead to check",
      "40 min drive from KL city center",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.95,
    opening_hours: { daily: "4pm-12:30am" },
  },
  {
    name: "Blackstone Bakery Cafe",
    city: "Petaling Jaya",
    area: "Klang",
    category: "cafe",
    tier: 2,
    address: "No 28, Jalan Stesen 1, Kawasan 1, 41000 Klang",
    latitude: 3.0448,
    longitude: 101.4466,
    price_range: "$",
    what_to_order: [
      "Fresh croissants",
      "Danish pastries (weekends only)",
      "Focaccia and ciabatta bread",
    ],
    pro_tips: [
      "Heritage shophouse bakery in old Klang town — step back in time",
      "Everything baked fresh — croissants, rye bread, ciabatta",
      "Danish pastries only available on weekends",
      "Closed Wednesdays",
      "Worth the drive to Klang if you love artisan bread",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { weekday: "10:30am-7pm", weekend: "9:30am-6pm", closed: "Wednesday" },
  },
  {
    name: "Daigu Coffee",
    city: "Petaling Jaya",
    area: "Klang",
    category: "cafe",
    tier: 3,
    address: "1, Jalan Goh Hock Huat, Kawasan 18, 41400 Klang",
    latitude: 3.0462,
    longitude: 101.4427,
    price_range: "$",
    what_to_order: ["Specialty coffee", "Pour over single origin"],
    pro_tips: [
      "Klang-born specialty coffee brand — now has outlets all over KL",
      "This is the original Klang outlet",
      "Also has branches in Sri Hartamas, Setia Alam, Puchong, and KLCC area",
      "Good third-wave coffee in an area not known for it",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
  },

  // ============================================
  // NEW BATCH — SHAH ALAM & SETIA ALAM
  // ============================================
  {
    name: "Loba.png",
    city: "Petaling Jaya",
    area: "Shah Alam",
    category: "lunch",
    tier: 2,
    address: "F-1-40, Sunsuria Forum, Setia Alam, 40170 Shah Alam",
    latitude: 3.1091,
    longitude: 101.4545,
    price_range: "$",
    what_to_order: ["Braised pork rice (RM13) — it's the only item on the menu"],
    pro_tips: [
      "One dish, one cook, 7-8 seats per batch — the most focused restaurant in Malaysia",
      "First of its kind in Malaysia — Taiwanese lu rou fan done with obsessive precision",
      "Opens at noon, usually sold out by 1-2pm on weekends",
      "Location is tricky: take lift next to Maybank ATM, level 1, turn right, up small staircase",
      "Closed Wednesdays",
      "Non-halal",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "noon till sold out", closed: "Wednesday" },
  },
];
