// Seed script — populate the knowledge graph with real KL spots
// Run with: npm run seed

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_KEY!
);

const spots = [
  // ============================================
  // BREAKFAST / BRUNCH
  // ============================================
  {
    name: "Village Park Restaurant",
    city: "Petaling Jaya",
    neighborhood: "Damansara Utama",
    category: "breakfast",
    tier: 1,
    address: "5, Jalan SS 21/37, Damansara Utama",
    latitude: 3.1340,
    longitude: 101.6235,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Nasi lemak with ayam goreng berempah", "Add sambal on the side"],
    what_to_skip: ["Western items — come here for the nasi lemak only"],
    pro_tips: [
      "Go before 9am on weekends or queue for 30+ minutes",
      "The ayam goreng is crispy outside, juicy inside — the benchmark",
      "Take away if the queue is crazy — same taste",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.95,
    opening_hours: { daily: "6:30am-1:30pm", closed: "Tuesday" },
  },
  {
    name: "Nasi Lemak Tanglin",
    city: "Kuala Lumpur",
    neighborhood: "Tanglin",
    category: "breakfast",
    tier: 1,
    address: "Jalan Tanglin, opposite Tanglin Tennis Centre",
    latitude: 3.1456,
    longitude: 101.6862,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi lemak biasa with extra sambal", "Add fried chicken (ayam goreng)"],
    pro_tips: [
      "Cash only — no exceptions",
      "This is a roadside stall, not a restaurant. That's the charm.",
      "Opens at 5:30am, sells out by 10am on weekends",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.9,
    opening_hours: { daily: "5:30am-11am" },
  },
  {
    name: "Yut Kee",
    city: "Kuala Lumpur",
    neighborhood: "Dang Wangi",
    category: "breakfast",
    tier: 2,
    address: "1, Jalan Kamunting",
    latitude: 3.1535,
    longitude: 101.6968,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Roti babi (pork bread)", "Hainanese chicken chop", "Kaya toast"],
    what_to_skip: ["Anything too adventurous — stick to the classics"],
    pro_tips: [
      "Heritage kopitiam since 1928 — the real deal",
      "Cash only, no card",
      "Go early on weekends, fills up by 9:30am",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { "tue-sun": "7:30am-4:30pm", closed: "Monday" },
  },

  // ============================================
  // LUNCH
  // ============================================
  {
    name: "Soong Kee Beef Noodles",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "lunch",
    tier: 1,
    address: "86, Jalan Tun H.S. Lee",
    latitude: 3.1441,
    longitude: 101.6960,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dry beef noodles (kon lo)", "Add tendon and tripe"],
    pro_tips: [
      "Absolutely legendary — been here for decades",
      "Cash only. RM10-15 per bowl.",
      "Lunch only — arrive by 11:30am, sells out by 1pm",
      "No AC, just fans. Part of the experience.",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.95,
    opening_hours: { daily: "8:30am-1:30pm" },
  },
  {
    name: "Restoran Rebung Chef Ismail",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "lunch",
    tier: 2,
    address: "6, Jalan Bangkung, Bangsar",
    latitude: 3.1295,
    longitude: 101.6721,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Buffet — try everything, especially rendang, ulam, and kuih"],
    pro_tips: [
      "Best Malay buffet in KL — run by celebrity chef Ismail",
      "Go for lunch, not dinner",
      "Dress modestly — it's near a mosque",
      "About RM50-60 per person for the buffet",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "11:30am-3pm, 6:30pm-10pm" },
  },
  {
    name: "Samy's Curry House",
    city: "Kuala Lumpur",
    neighborhood: "Brickfields",
    category: "lunch",
    tier: 2,
    address: "25, Jalan Dewan Sultan Sulaiman",
    latitude: 3.1335,
    longitude: 101.6873,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Fish head curry", "Banana leaf rice", "Mutton varuval"],
    pro_tips: [
      "Eating on banana leaf is the move — mix everything with your hands",
      "Ask for extra rasam (the soup) — it's free refills",
      "Near KL Sentral, easy to get to",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "11am-10pm" },
  },

  // ============================================
  // DINNER
  // ============================================
  {
    name: "Wong Ah Wah",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "dinner",
    tier: 2,
    address: "1-9, Jalan Alor, Bukit Bintang",
    latitude: 3.1459,
    longitude: 101.7082,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Chicken wings (legendary)", "Satay", "Kangkung belacan"],
    what_to_skip: ["Don't eat at the first stall that calls out to you on Jalan Alor"],
    pro_tips: [
      "Jalan Alor is touristy BUT Wong Ah Wah is the one locals actually go to",
      "Cash only",
      "Go after 7pm for the full atmosphere",
      "Sit outside for the street food vibe",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "5pm-4am" },
  },
  {
    name: "Bijan Bar & Restaurant",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Ceylon",
    category: "dinner",
    tier: 2,
    address: "3, Jalan Ceylon, Bukit Ceylon",
    latitude: 3.1495,
    longitude: 101.7108,
    payment_methods: ["card", "cash"],
    price_range: "$$$",
    what_to_order: ["Satay", "Rendang", "Nasi kerabu", "Any curry"],
    pro_tips: [
      "Fine dining Malay food — if you want to splurge on one nice dinner, this is it",
      "Make a reservation, especially weekends",
      "The garden terrace is beautiful",
      "About RM150-200 per person with drinks",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "6pm-11pm" },
  },
  {
    name: "Mansion Tea Stall",
    city: "Kuala Lumpur",
    neighborhood: "Masjid India",
    category: "dinner",
    tier: 1,
    address: "Selangor Mansion, Jalan Masjid India",
    latitude: 3.1610,
    longitude: 101.7020,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi campur", "Ayam percik", "Teh tarik"],
    pro_tips: [
      "THE spot to experience Kampung Baru at night",
      "Cash only, super cheap — RM10-15 fills you up",
      "Walk through the kampung after — it's magical at night",
      "The area is safe but bring minimal valuables",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "6pm-midnight" },
  },

  // ============================================
  // CAFES
  // ============================================
  {
    name: "VCR",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "cafe",
    tier: 2,
    address: "2, Jalan Galloway, off Jalan Pudu",
    latitude: 3.1419,
    longitude: 101.7071,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Flat white", "Avocado toast", "Any pastry"],
    pro_tips: [
      "KL's OG specialty coffee spot — been around since the third wave started here",
      "Great for a quiet afternoon work session",
      "The brunch menu is solid but comes at cafe prices",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "8am-6pm" },
  },
  {
    name: "Merchant's Lane",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "cafe",
    tier: 2,
    address: "150, Jalan Petaling (above a traditional Chinese medicine shop)",
    latitude: 3.1441,
    longitude: 101.6972,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Pandan waffle", "Nasi lemak burger", "Any coffee"],
    pro_tips: [
      "The entrance is through a narrow staircase above a Chinese medicine shop — that's the charm",
      "Beautiful interior in a restored pre-war building",
      "Great for Instagram but also genuinely good food",
      "Combine with a Chinatown walk",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "wed-mon": "11am-8pm", closed: "Tuesday" },
  },
  {
    name: "PPP Coffee",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "cafe",
    tier: 2,
    address: "19, Lorong Panggung, Chinatown",
    latitude: 3.1453,
    longitude: 101.6964,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Filter coffee (ask what's on rotation)", "Flat white"],
    pro_tips: [
      "Serious specialty coffee in a beautifully restored shophouse",
      "They roast their own beans — ask about single origins",
      "Great combo with Merchant's Lane and Chinatown exploring",
      "Small space, limited seating — go off-peak",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { "tue-sun": "9am-6pm", closed: "Monday" },
  },
  {
    name: "Feeka Coffee Roasters",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "cafe",
    tier: 2,
    address: "19, Jalan Mesui, Bukit Bintang",
    latitude: 3.1490,
    longitude: 101.7060,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Latte", "Big breakfast", "Banana bread"],
    pro_tips: [
      "Tucked in a quiet lane off the Bukit Bintang chaos — a nice escape",
      "Good brunch spot, decent portions for cafe food",
      "Popular on weekends — get there before 11am for a table",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "8am-10pm" },
  },
  {
    name: "Kenny Hills Bakers",
    city: "Kuala Lumpur",
    neighborhood: "TTDI",
    category: "cafe",
    tier: 2,
    address: "Lot G-2, The Greens Terrace, Jalan Wan Kadir 3, TTDI",
    latitude: 3.1359,
    longitude: 101.6302,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Sourdough loaf (best in KL)", "Croissant", "Any pastry with coffee"],
    pro_tips: [
      "The sourdough bread is genuinely world-class — locals queue for it",
      "Arrive early on weekends — the good stuff sells out by noon",
      "Also has a spot in Bukit Tunku if TTDI is too far",
    ],
    vibe: "chill",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "7:30am-6pm" },
  },

  // ============================================
  // MAMAK (Late Night)
  // ============================================
  {
    name: "Nasi Kandar Pelita",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "dinner",
    tier: 2,
    address: "149, Jalan Ampang",
    latitude: 3.1577,
    longitude: 101.7175,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Nasi kandar", "Roti canai", "Teh tarik"],
    pro_tips: [
      "Open 24 hours — THE late-night mamak spot",
      "Point at the curries you want — they'll pile them on rice",
      "The roti canai at 2am hits different",
      "Always packed but turnover is fast",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "Mamak Mansion",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "dinner",
    tier: 2,
    address: "1, Jalan Raja Muda Abdul Aziz, Kampung Baru",
    latitude: 3.1620,
    longitude: 101.7001,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Mee goreng mamak", "Roti cheese", "Maggi goreng"],
    pro_tips: [
      "A slightly more polished mamak experience — still authentic flavors",
      "The maggi goreng is addictive and only RM8",
      "Good late-night option near Kampung Baru",
      "Air-conditioned section available if you want to escape the heat",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "Ali Muthu Ah Hock",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "dinner",
    tier: 3,
    address: "10, Jalan Telawi 2, Bangsar",
    latitude: 3.1297,
    longitude: 101.6708,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Roti canai", "Nasi lemak", "Teh tarik"],
    pro_tips: [
      "Named after Malaysia's three main ethnicities — the perfect late-night mamak",
      "Right in the heart of Bangsar nightlife strip",
      "Great pit stop between bars or after a night out",
    ],
    vibe: "chaotic",
    best_time_of_day: "late-night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "24 hours" },
  },

  // ============================================
  // MARKETS
  // ============================================
  {
    name: "Chow Kit Wet Market",
    city: "Kuala Lumpur",
    neighborhood: "Chow Kit",
    category: "market",
    tier: 1,
    address: "Jalan TAR, Chow Kit",
    latitude: 3.1660,
    longitude: 101.6987,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Browse and snack — fresh tropical fruits, kuih, fried snacks"],
    pro_tips: [
      "Go before 10am for the full experience — it's a REAL wet market, not tourist market",
      "Wear shoes you don't mind getting wet",
      "The fruit section is incredible — ask uncle to pick you a ripe mangosteen",
      "Combine with breakfast at one of the stalls inside",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { daily: "6am-2pm" },
  },
  {
    name: "Pasar Seni (Central Market)",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "market",
    tier: 3,
    address: "Jalan Hang Kasturi",
    latitude: 3.1456,
    longitude: 101.6953,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Batik souvenirs", "Local handicrafts"],
    what_to_skip: ["Overpriced 'antiques'", "Don't buy the first price — negotiate"],
    pro_tips: [
      "Tourist-oriented but a decent one-stop for souvenirs",
      "The food court upstairs (Annexe) has decent options",
      "Not the most authentic market — Chow Kit or Pudu are realer",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    opening_hours: { daily: "10am-9:30pm" },
  },

  // ============================================
  // ACTIVITIES
  // ============================================
  {
    name: "Batu Caves",
    city: "Batu Caves",
    neighborhood: "Batu Caves",
    category: "activity",
    tier: 1,
    address: "Sri Subramaniar Swamy Temple, Batu Caves",
    latitude: 3.2379,
    longitude: 101.6840,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Free entry to main cave", "Dark Cave tour RM35 (worth it)"],
    pro_tips: [
      "Go at 7am to beat the crowds and heat — 272 steps in KL humidity is no joke",
      "Watch your belongings — the monkeys WILL steal your water bottle",
      "Wear covered shoulders and knees (temple)",
      "Take KTM train from KL Sentral — cheaper and easier than Grab",
      "The Dark Cave tour is genuinely fascinating if you're into nature",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.95,
    opening_hours: { daily: "6am-9pm" },
  },
  {
    name: "Islamic Arts Museum",
    city: "Kuala Lumpur",
    neighborhood: "Lake Gardens",
    category: "activity",
    tier: 2,
    address: "Jalan Lembah Perdana",
    latitude: 3.1424,
    longitude: 101.6878,
    payment_methods: ["card", "cash"],
    price_range: "$",
    what_to_order: ["Entry RM14 (worth it)", "The Architecture Gallery is the highlight"],
    pro_tips: [
      "Underrated gem — most tourists skip this for Petronas. Their loss.",
      "Beautiful building, world-class collection",
      "Great rainy day activity — fully indoor, AC",
      "The gift shop has genuinely nice souvenirs (calligraphy, tiles)",
      "Combine with a walk through the Lake Gardens next door",
    ],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "10am-6pm" },
  },
  {
    name: "Petronas Twin Towers + KLCC Park",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "activity",
    tier: 2,
    address: "KLCC, Kuala Lumpur City Centre",
    latitude: 3.1578,
    longitude: 101.7117,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Skybridge tickets RM80 (book online 2 days ahead)", "KLCC Park is free"],
    what_to_skip: ["Don't eat at Suria KLCC food court — overpriced tourist food"],
    pro_tips: [
      "The park at the base is honestly better than going up the towers",
      "Free water fountain show every night at 8pm, 9pm, 10pm",
      "Book Skybridge tickets online — same-day walk-ins sell out by 9am",
      "Best photo spot: across the road at Trader's Hotel rooftop",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "tue-sun": "9am-9pm", closed: "Monday" },
  },
  {
    name: "Thean Hou Temple",
    city: "Kuala Lumpur",
    neighborhood: "Robson Heights",
    category: "activity",
    tier: 2,
    address: "65, Persiaran Endah, Taman Persiaran Desa",
    latitude: 3.1183,
    longitude: 101.6862,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Free entry", "Light incense (donation-based)"],
    pro_tips: [
      "Most beautiful Chinese temple in KL — and way less crowded than you'd expect",
      "Go at sunset for incredible views of the KL skyline",
      "Free entry, just donate what you feel",
      "Grab there, it's on a hill with no public transport nearby",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "8am-10pm" },
  },
  {
    name: "Merdeka Square",
    city: "Kuala Lumpur",
    neighborhood: "Dataran Merdeka",
    category: "activity",
    tier: 2,
    address: "Jalan Raja, Dataran Merdeka",
    latitude: 3.1488,
    longitude: 101.6935,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Free to visit", "Photo with the flagpole and Sultan Abdul Samad Building"],
    pro_tips: [
      "Where Malaysian independence was declared in 1957 — historically significant",
      "The Sultan Abdul Samad Building (Moorish architecture) is gorgeous at golden hour",
      "Combine with Chinatown walk, it's a 10-minute stroll south",
      "Visit early morning or evening to avoid the heat — it's an open field",
      "KL City Gallery is right here if you want AC and a quick history lesson",
    ],
    vibe: "touristy",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "24 hours" },
  },
  {
    name: "KL Tower (Menara KL)",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Nanas",
    category: "activity",
    tier: 2,
    address: "2, Jalan Puncak, Off Jalan P. Ramlee",
    latitude: 3.1528,
    longitude: 101.7038,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Observation deck RM52", "Sky Deck (open air) RM105 for the real thrill"],
    what_to_skip: ["The XD Theatre — skip it, not worth the extra"],
    pro_tips: [
      "Better panoramic views than Petronas — you can actually see Petronas from here",
      "The Sky Deck (open-air glass floor) is genuinely thrilling",
      "Way less crowded than Petronas, no need to book days ahead",
      "Walk through Bukit Nanas Forest Reserve on the way — oldest protected jungle in Malaysia, right in the city",
    ],
    vibe: "touristy",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "9am-10pm" },
  },
  {
    name: "Aquaria KLCC",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "activity",
    tier: 3,
    address: "Kuala Lumpur Convention Centre, KLCC",
    latitude: 3.1534,
    longitude: 101.7132,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Entry RM69 (online cheaper)", "90m underwater tunnel is the highlight"],
    pro_tips: [
      "Good rainy day activity, especially if traveling with kids",
      "The underwater tunnel with sharks and rays overhead is legit impressive",
      "Book online for 10-15% discount",
      "Combine with KLCC Park — it's in the convention centre basement",
      "Takes about 1-1.5 hours to walk through",
    ],
    vibe: "touristy",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "10am-8pm" },
  },
  {
    name: "Kampung Baru Walking Tour",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "activity",
    tier: 2,
    address: "Start at Masjid Jamek LRT station, walk north",
    latitude: 3.1590,
    longitude: 101.6998,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Self-guided walk is free", "Snack on kuih and keropok from street vendors"],
    pro_tips: [
      "The last traditional Malay village in central KL — wooden stilt houses next to skyscrapers",
      "Go late afternoon for golden hour light + less heat",
      "The Saturday night market (Pasar Malam) is incredible — food stalls everywhere",
      "Very safe area, locals are friendly — just be respectful and dress modestly",
      "End at Mansion Tea Stall for dinner — perfect bookend",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "anytime (market: Saturday evening)" },
  },

  // ============================================
  // NIGHTLIFE
  // ============================================
  {
    name: "PS150",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "nightlife",
    tier: 1,
    address: "150, Jalan Petaling (hidden entrance in Chinatown)",
    latitude: 3.1441,
    longitude: 101.6970,
    payment_methods: ["card"],
    price_range: "$$$",
    what_to_order: ["Ask the bartender for their recommendation based on your taste", "Any cocktail with local ingredients"],
    pro_tips: [
      "Best cocktail bar in KL — consistently on Asia's 50 Best Bars",
      "Hidden entrance: look for the red door on Petaling Street",
      "No reservations needed on weekdays, book weekends",
      "Cocktails RM45-65 — not cheap but worth it",
      "Try something with local Malaysian ingredients",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Heli Lounge Bar",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "nightlife",
    tier: 2,
    address: "Menara KH, Jalan Sultan Ismail",
    latitude: 3.1505,
    longitude: 101.7018,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Any beer or basic cocktail — you're here for the view"],
    what_to_skip: ["Food — eat before you come"],
    pro_tips: [
      "It's literally a helipad on top of a building. You drink ON the helipad.",
      "Best view of KL skyline, especially at sunset",
      "Drinks are surprisingly affordable (RM25-40)",
      "Go before 7pm to grab a spot for sunset",
      "Dress code: no slippers (flip flops)",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Coley Cocktail Bar",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "nightlife",
    tier: 1,
    address: "6-G, Jalan Abdullah, Bangsar",
    latitude: 3.1292,
    longitude: 101.6696,
    payment_methods: ["card"],
    price_range: "$$$",
    what_to_order: ["The seasonal cocktail menu", "Ask CK (the owner-bartender) what he recommends"],
    pro_tips: [
      "One of Asia's best bars — CK the bartender is a legend, a true craftsman",
      "Small space, only 20-ish seats — go early (before 9pm) or prepare to wait",
      "Cocktails RM42-58 — they use local Malaysian ingredients beautifully",
      "The vibe is intimate and personal — like drinking at a friend's place",
      "No loud music, no pretension — just exceptional cocktails",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "tue-sat": "5pm-midnight", closed: "Sunday, Monday" },
  },
  {
    name: "JungleBird",
    city: "Kuala Lumpur",
    neighborhood: "Damansara Heights",
    category: "nightlife",
    tier: 2,
    address: "61M, Jalan Medan Setia 1, Bukit Damansara",
    latitude: 3.1503,
    longitude: 101.6535,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["The JungleBird cocktail (named after the bar)", "Any tiki cocktail"],
    pro_tips: [
      "Tiki bar vibes in a tropical city — makes total sense",
      "Named after the classic Malaysian cocktail — order the namesake, it's their signature",
      "More relaxed than PS150, good for groups",
      "Happy hour 5-7pm is solid value",
    ],
    vibe: "chill",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-1am" },
  },
  {
    name: "Changkat Bukit Bintang",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "nightlife",
    tier: 3,
    address: "Changkat Bukit Bintang (whole street)",
    latitude: 3.1472,
    longitude: 101.7090,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Bar hop — try Pisco Bar, Whisky Bar, or El Cerdo"],
    what_to_skip: ["Avoid the aggressive club promoters"],
    pro_tips: [
      "KL's main nightlife strip — wall-to-wall bars and clubs",
      "Touristy but fun for a night out, especially if you want variety",
      "Pisco Bar for cocktails, El Cerdo for roast pork + wine",
      "Gets loud and rowdy after 11pm — that's the point",
      "Grab home — don't try to drive or find parking here",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.75,
    opening_hours: { daily: "5pm-3am" },
  },

  // ============================================
  // MORE FOOD SPOTS
  // ============================================
  {
    name: "ICC Pudu",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "lunch",
    tier: 1,
    address: "Jalan 1/77C, Imbi",
    latitude: 3.1388,
    longitude: 101.7097,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Hokkien mee", "Curry mee", "Chee cheong fun", "Roast duck"],
    pro_tips: [
      "This is where KL locals actually eat — a massive hawker complex",
      "Every stall specializes in one thing. Pick 3-4 stalls and share.",
      "Cash only everywhere. ATM outside.",
      "Go for lunch, arrive by 11:30am — some stalls sell out by 1pm",
      "The hokkien mee stall (dark soy version) is legendary",
    ],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.95,
    opening_hours: { daily: "7am-3pm" },
  },
  {
    name: "Lot 10 Hutong",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "lunch",
    tier: 2,
    address: "Lot 10 Shopping Centre, Basement, 50, Jalan Bukit Bintang",
    latitude: 3.1483,
    longitude: 101.7109,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Ho Weng Kee wonton mee", "Kim Lian Kee hokkien mee", "Soong Kee beef noodles"],
    pro_tips: [
      "Best hawker stalls gathered under one AC roof — great if you can't handle the heat",
      "More expensive than the actual stalls but much more comfortable",
      "Good first-day introduction to Malaysian hawker food",
      "Air conditioned — perfect rainy day option",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { daily: "10am-10pm" },
  },
  {
    name: "Jalan Alor Hawker Street",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "dinner",
    tier: 2,
    address: "Jalan Alor, off Jalan Bukit Bintang",
    latitude: 3.1457,
    longitude: 101.7083,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Grilled chicken wings", "Satay", "Fried carrot cake"],
    what_to_skip: ["Restaurants that aggressively try to seat you — find your own spot"],
    pro_tips: [
      "Yes it's touristy. But it's still an experience worth having once.",
      "Wong Ah Wah (at the end) is the best stall on the whole street",
      "Go after 7pm when all stalls are open and the atmosphere is alive",
      "Cash only at most stalls",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-3am" },
  },
  {
    name: "Aunty Christina's Sarawak Laksa",
    city: "Kuala Lumpur",
    neighborhood: "TTDI",
    category: "lunch",
    tier: 2,
    address: "TTDI Market, Lorong Datuk Sulaiman 1",
    latitude: 3.1336,
    longitude: 101.6296,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Sarawak laksa (the ONLY thing on the menu)"],
    pro_tips: [
      "She serves one thing and one thing only — Sarawak laksa. And it's incredible.",
      "Cash only, RM12 per bowl",
      "Inside TTDI wet market — go in the morning, she sells out by noon",
      "Combine with exploring TTDI market for breakfast",
    ],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.85,
    opening_hours: { "tue-sun": "7am-12pm", closed: "Monday" },
  },
  {
    name: "Dewakan",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "dinner",
    tier: 1,
    address: "Level 48, Naza Tower, Platinum Park, Persiaran KLCC",
    latitude: 3.1553,
    longitude: 101.7137,
    payment_methods: ["card"],
    price_range: "$$$",
    what_to_order: ["The tasting menu (there's only one option)", "Wine pairing if you drink"],
    pro_tips: [
      "Only restaurant in Malaysia on Asia's 50 Best — legit world-class",
      "Book 2-3 weeks in advance minimum",
      "Tasting menu RM550 per person, wine pairing RM350",
      "It's in Shah Alam (30-40 min from city center) — Grab there",
      "Worth the trip if food is your thing and you want to splurge once",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.9,
    opening_hours: { "wed-sat": "6pm-11pm" },
  },

  // ============================================
  // SUBURBAN — PJ, Subang, Mont Kiara
  // ============================================
  {
    name: "SS2 Wai Sek Kai",
    city: "Petaling Jaya",
    neighborhood: "SS2",
    category: "dinner",
    tier: 2,
    address: "Jalan SS 2/10, Petaling Jaya",
    latitude: 3.1186,
    longitude: 101.6214,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Char kuey teow", "Fried oyster omelette", "Lok lok (skewer hotpot)"],
    pro_tips: [
      "PJ's most famous hawker street — local families eat here nightly",
      "Go for the char kuey teow stall and the lok lok (pick your skewers, they cook them)",
      "Cash only at all stalls",
      "Gets packed after 7pm — go slightly early for the best choice",
      "20 min Grab from KL city center",
    ],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "5pm-midnight" },
  },
  {
    name: "Damansara Uptown Hawker Stalls",
    city: "Petaling Jaya",
    neighborhood: "Damansara Utama",
    category: "dinner",
    tier: 2,
    address: "Jalan SS 21/56B, Damansara Utama",
    latitude: 3.1340,
    longitude: 101.6244,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Hokkien mee (dark version)", "Grilled fish", "Thai-style tom yum"],
    pro_tips: [
      "A cluster of open-air hawker stalls that comes alive at night",
      "The vibe is very local PJ — not a tourist in sight",
      "Pair with a visit to Village Park (breakfast) since they're in the same area",
      "Cash only for most stalls",
    ],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.8,
    opening_hours: { daily: "5pm-midnight" },
  },
  {
    name: "Devi's Corner",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "dinner",
    tier: 2,
    address: "Jalan Telawi 3, Bangsar",
    latitude: 3.1301,
    longitude: 101.6713,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Tandoori chicken", "Roti canai", "Banana leaf rice"],
    pro_tips: [
      "Bangsar institution — been here forever, open late",
      "The tandoori chicken is the star — crispy, smoky, perfect",
      "Great late-night option after Bangsar bar hopping",
      "Outdoor seating on the street — buzzy atmosphere at night",
    ],
    vibe: "local",
    best_time_of_day: "late-night",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.85,
    opening_hours: { daily: "7am-2am" },
  },
  {
    name: "Jaya One Food Court",
    city: "Petaling Jaya",
    neighborhood: "Section 13",
    category: "lunch",
    tier: 3,
    address: "72A, Jalan Universiti, Section 13, PJ",
    latitude: 3.1124,
    longitude: 101.6372,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Pan mee", "Claypot chicken rice", "Thai food stall"],
    pro_tips: [
      "Solid suburban food court if you're in the PJ area",
      "The pan mee stall is standout — thick, chewy noodles with anchovy broth",
      "Air-conditioned — good escape from the heat",
      "Near the university area, gets busy at lunch",
    ],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.75,
    opening_hours: { daily: "8am-10pm" },
  },
  {
    name: "Marini's on 57",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "nightlife",
    tier: 2,
    address: "Level 57, Menara 3 Petronas, KLCC",
    latitude: 3.1577,
    longitude: 101.7137,
    payment_methods: ["card"],
    price_range: "$$$",
    what_to_order: ["Any cocktail — you're paying for the view", "The sunset aperitivo"],
    what_to_skip: ["Full dinner menu — overpriced for what you get"],
    pro_tips: [
      "Level 57 with floor-to-ceiling windows — jaw-dropping view of the Twin Towers",
      "Smart casual dress code (no shorts/slippers)",
      "Go at sunset for the best experience",
      "Cocktails RM55-80 — expensive but this is THE view",
      "Book a window table in advance for special occasions",
    ],
    vibe: "upscale",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.8,
    opening_hours: { daily: "4pm-1am" },
  },
];

async function seed() {
  const city = process.argv[2] || "Kuala Lumpur";
  const citySpots = spots.filter((s) => s.city === city);

  if (citySpots.length === 0) {
    console.log(`No seed data for "${city}". Available cities: ${[...new Set(spots.map((s) => s.city))].join(", ")}`);
    return;
  }

  console.log(`Seeding ${citySpots.length} ${city} spots...`);

  for (const spot of citySpots) {
    // Try with source column first; fall back without if column doesn't exist yet
    let { error } = await supabase.from("spots").insert({ ...spot, source: "seed" });
    if (error?.message?.includes("source")) {
      ({ error } = await supabase.from("spots").insert(spot));
    }
    if (error) {
      console.error(`Failed to insert ${spot.name}:`, error.message);
    } else {
      console.log(`  ✓ ${spot.name} (${spot.neighborhood})`);
    }
  }

  console.log("\nDone! Run some test queries to verify.");
}

seed().catch(console.error);
