// Batch insert script — run with: npx tsx --env-file .env.local scripts/batch-insert.ts
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_KEY!);

const BATCH: Record<string, any[]> = {};

// ============================================
// BATCH 1: BREAKFAST (16 spots)
// ============================================
BATCH["breakfast"] = [
  {
    name: "Ah Weng Koh Hainan Tea",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "breakfast",
    tier: 1,
    address: "Imbi Market, Jalan 1/77C, Pudu",
    latitude: 3.1390,
    longitude: 101.7098,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Hainan tea (the GOAT — thick, creamy, aromatic)", "Kaya toast"],
    pro_tips: ["Queue is always long but moves fast", "Cash only, RM2.50 per cup", "Inside Imbi Market — combine with other stalls"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nasi Lemak Antarabangsa",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "breakfast",
    tier: 1,
    address: "Jalan Raja Muda Musa, Kampung Baru",
    latitude: 3.1635,
    longitude: 101.7005,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi lemak with ayam goreng", "Add extra sambal", "Rendang if available"],
    pro_tips: ["Open 24 hours but best at breakfast", "Cash only", "The sambal is fiery — you've been warned"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Kin Kin Chilli Pan Mee",
    city: "Kuala Lumpur",
    neighborhood: "Chow Kit",
    category: "breakfast",
    tier: 1,
    address: "40, Jalan Dewan Sultan Sulaiman 1, Chow Kit",
    latitude: 3.1670,
    longitude: 101.6940,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dry chilli pan mee — the original", "Add extra chilli flakes and a poached egg"],
    pro_tips: ["The OG chilli pan mee spot — everyone else is copying them", "Arrive before 10am to avoid the worst queue", "Cash only, RM8-10 per bowl"],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Kim Lian Kee Hokkien Mee",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "breakfast",
    tier: 2,
    address: "49, Jalan Petaling, Chinatown",
    latitude: 3.1445,
    longitude: 101.6965,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dark hokkien mee (KL-style with thick dark soy)", "Add pork lard croutons"],
    pro_tips: ["Since 1927 — one of the oldest hawker stalls in KL", "The dark soy noodles are KL's signature dish", "Cash only"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Ali Maju Nasi Kandar",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "breakfast",
    tier: 2,
    address: "32, Jalan Telawi 2, Bangsar Baru",
    latitude: 3.1300,
    longitude: 101.6710,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Roti canai with dhal", "Nasi kandar with mixed curries", "Teh tarik"],
    pro_tips: ["Open 24/7 — the 3am roti canai is a Bangsar institution", "Popular with post-bar crowds", "Fast service even when packed"],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nam Chuan Coffee Shop",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "breakfast",
    tier: 2,
    address: "Jalan Sayur, off Jalan Pudu",
    latitude: 3.1385,
    longitude: 101.7080,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Char kuey teow (wok hei is incredible)", "Hokkien mee", "Iced coffee"],
    pro_tips: ["Old-school kopitiam vibes — marble tables, ceiling fans", "Multiple stalls inside, each with a specialty", "Morning only — most stalls done by 1pm"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Hong Kee Wan Tan Mee",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "breakfast",
    tier: 2,
    address: "Restoran Win Heng Seng, Jalan Sayur, Pudu",
    latitude: 3.1382,
    longitude: 101.7076,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dry wan tan mee with char siu", "Add extra wan tans (dumplings)"],
    pro_tips: ["The springy egg noodles tossed in dark soy and lard — perfection", "Stall inside Restoran Win Heng Seng", "Cash only, RM7-9 per plate"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Yusoof Dan Zakhir",
    city: "Kuala Lumpur",
    neighborhood: "Masjid India",
    category: "breakfast",
    tier: 2,
    address: "Lorong Tuanku Abdul Rahman, Masjid India",
    latitude: 3.1605,
    longitude: 101.6980,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Roti canai (paper thin and crispy)", "Murtabak", "Teh tarik"],
    pro_tips: ["One of KL's best roti canai — the dough is incredibly thin and flaky", "Morning only, sells out by noon", "Pure Masjid India atmosphere"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Restoran Syed Ali",
    city: "Petaling Jaya",
    neighborhood: "SS15",
    category: "breakfast",
    tier: 2,
    address: "Jalan SS15/4D, SS15, Subang Jaya",
    latitude: 3.0775,
    longitude: 101.5875,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Roti canai special", "Nasi lemak", "Mee goreng mamak"],
    pro_tips: ["Local PJ mamak legend, been here decades", "The roti canai is crispy perfection", "Gets packed on weekend mornings"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Kaya & Toast by OldTown",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "breakfast",
    tier: 3,
    address: "Lot 10 Shopping Centre, Bukit Bintang",
    latitude: 3.1483,
    longitude: 101.7110,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Kaya toast set with soft-boiled eggs", "White coffee", "Nasi lemak"],
    pro_tips: ["Good introduction to Malaysian kopitiam breakfast", "Air-conditioned, tourist-friendly", "Not the most authentic but reliable and comfortable"],
    vibe: "casual",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Sing Kee Beef Noodles",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "breakfast",
    tier: 2,
    address: "Jalan Brunei, off Jalan Pudu",
    latitude: 3.1400,
    longitude: 101.7060,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dry beef noodles with tendon", "Beef ball soup on the side"],
    pro_tips: ["Rival to Soong Kee — locals argue about which is better", "Slightly less queue than Soong Kee", "Cash only, RM10-12 per bowl"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Tg's Nasi Kandar",
    city: "Kuala Lumpur",
    neighborhood: "Dang Wangi",
    category: "breakfast",
    tier: 2,
    address: "Jalan Dang Wangi, near Dang Wangi LRT",
    latitude: 3.1530,
    longitude: 101.6960,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Nasi kandar with ayam goreng", "Fish curry", "Teh tarik ais"],
    pro_tips: ["Solid nasi kandar option near the city center", "Open early — good pre-exploration fuel", "The curries rotate so ask what's fresh"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Restoran Yong Tau Foo",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "breakfast",
    tier: 3,
    address: "Jalan 1/77C, Imbi",
    latitude: 3.1392,
    longitude: 101.7095,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Hakka yong tau foo — pick your stuffed items", "Add bitter gourd, eggplant, and tofu puffs"],
    pro_tips: ["Pick your own items from the display, they cook them for you", "Great vegetarian-friendly option", "Inside ICC Pudu complex"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Lucky Boh Kopitiam",
    city: "Petaling Jaya",
    neighborhood: "SS2",
    category: "breakfast",
    tier: 3,
    address: "1, Jalan SS 2/55, SS2, Petaling Jaya",
    latitude: 3.1175,
    longitude: 101.6205,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi lemak", "Toast with kaya and butter", "Kopi-O"],
    pro_tips: ["Classic PJ kopitiam — no frills, just good food", "The kaya toast is made fresh", "Popular with the SS2 morning crowd"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nasi Lemak Bumbung",
    city: "Kuala Lumpur",
    neighborhood: "TTDI",
    category: "breakfast",
    tier: 2,
    address: "Jalan Tun Mohd Fuad, TTDI",
    latitude: 3.1345,
    longitude: 101.6310,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi lemak with sambal sotong", "Add fried chicken quarter", "Telur goreng (fried egg)"],
    pro_tips: ["Famous late-night/early-morning nasi lemak stall", "The sotong sambal is the star — sweet, spicy, sticky", "Roadside stall under a zinc roof (bumbung)", "Queue can be 20+ min on weekends"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "outdoor",
    weather_dependent: true,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Thong Kee Cafe",
    city: "Kuala Lumpur",
    neighborhood: "Desa ParkCity",
    category: "breakfast",
    tier: 3,
    address: "The Waterfront, Desa ParkCity, Kepong",
    latitude: 3.1878,
    longitude: 101.6310,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Nasi lemak set", "Hainanese chicken chop", "White coffee"],
    pro_tips: ["Modern kopitiam chain with consistently good food", "In Desa ParkCity — combine with a lakeside walk", "Air-conditioned, family-friendly"],
    vibe: "casual",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
];

// ============================================
// BATCH 2: LUNCH A (13 spots)
// ============================================
BATCH["lunch_a"] = [
  {
    name: "Lai Foong Beef Noodles",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "lunch",
    tier: 1,
    address: "138, Jalan Tun H.S. Lee, Chinatown",
    latitude: 3.1448,
    longitude: 101.6955,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Dry beef noodles", "Curry laksa", "Hainanese chicken rice"],
    pro_tips: ["Multiple legendary stalls under one roof", "The beef noodle stall always has a queue — that's how you know", "Cash only, most dishes RM8-12", "Go before noon for the best selection"],
    vibe: "chaotic",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Old China Cafe",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "lunch",
    tier: 2,
    address: "11, Jalan Balai Polis, Chinatown",
    latitude: 3.1460,
    longitude: 101.6950,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Nyonya laksa", "Kapitan chicken", "Assam fish", "Cendol"],
    pro_tips: ["Beautiful heritage building — former laundry workers' guild", "Nyonya food in a gorgeous setting", "Good for a slightly upscale Chinatown lunch", "Reservations recommended on weekends"],
    vibe: "chill",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Madam Kwan's",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "lunch",
    tier: 2,
    address: "Suria KLCC, Lot 420, Level 4",
    latitude: 3.1578,
    longitude: 101.7117,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Nasi bojari (signature rice)", "Mee rebus", "Satay", "Hetty's curry laksa"],
    pro_tips: ["Tourist-friendly intro to Malaysian food — reliable and comfortable", "In Suria KLCC mall, easy access", "Not the most authentic but consistently good", "Good for groups with mixed adventurousness levels"],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Peter's Pork Noodles",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "lunch",
    tier: 1,
    address: "Opposite ICC Pudu, Jalan 1/77C",
    latitude: 3.1390,
    longitude: 101.7100,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Pork noodle soup — clear broth version", "Add intestine and liver if you're adventurous"],
    pro_tips: ["The broth is slow-simmered pork bone — deeply savory", "Cash only, RM10-12", "Morning to early afternoon only", "Non-halal — pork-based"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nasi Lemak Wanjo",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "lunch",
    tier: 2,
    address: "1, Jalan Raja Muda Musa, Kampung Baru",
    latitude: 3.1628,
    longitude: 101.7000,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi lemak with rendang tok", "Sambal sotong", "Ayam goreng berempah"],
    pro_tips: ["Kampung Baru institution — been feeding KL for decades", "Lunch crowd is intense — go slightly before noon", "The rendang tok is dry-fried until caramelized — incredible", "Cash only"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Yap Hup Kee",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "lunch",
    tier: 2,
    address: "25, Jalan Tun Tan Siew Sin, Chinatown",
    latitude: 3.1438,
    longitude: 101.6972,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Steamed chicken with rice — Hainanese style", "Roast duck", "Char siu (BBQ pork)"],
    pro_tips: ["Old-school roast meat shop — the chicken is perfectly silky", "Lunch only, sells out by 2pm", "Point at what you want in the glass display", "Cash only, RM10-15"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Sri Nirwana Maju",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "lunch",
    tier: 1,
    address: "43, Jalan Telawi 3, Bangsar Baru",
    latitude: 3.1298,
    longitude: 101.6715,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Banana leaf rice — the full spread", "Fish head curry", "Mutton varuval", "Rasam (free refills)"],
    pro_tips: ["Best banana leaf rice in KL — locals will fight you on this", "Eat with your right hand for the full experience", "Always packed at lunch — go before 12 or after 1:30", "The fish head curry is legendary"],
    vibe: "chaotic",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Devi Annapoorna",
    city: "Kuala Lumpur",
    neighborhood: "Brickfields",
    category: "lunch",
    tier: 2,
    address: "88, Jalan Tun Sambanthan, Brickfields",
    latitude: 3.1330,
    longitude: 101.6870,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Thosai set (various types)", "Masala dosa", "Idli with sambar and chutney"],
    pro_tips: ["Pure vegetarian South Indian — excellent dosas and thali", "Near KL Sentral, easy access", "Good vegetarian/vegan option", "The sambar is freshly made and incredible"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Passage Thru India",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "lunch",
    tier: 2,
    address: "9, Jalan Delima, Bukit Bintang",
    latitude: 3.1470,
    longitude: 101.7100,
    payment_methods: ["card", "cash"],
    price_range: "$$",
    what_to_order: ["Butter chicken", "Garlic naan", "Lamb rogan josh", "Tandoori platter"],
    pro_tips: ["North Indian fine dining — one of KL's best", "Great for when you want Indian food in a nice setting", "Reservations recommended for dinner", "Lunch set is good value — RM25-35"],
    vibe: "upscale",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Huen Kee Claypot Chicken Rice",
    city: "Kuala Lumpur",
    neighborhood: "Pudu",
    category: "lunch",
    tier: 2,
    address: "Jalan 1/77C, inside ICC Pudu",
    latitude: 3.1388,
    longitude: 101.7098,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Claypot chicken rice — charcoal-cooked", "Order medium size for 2 people"],
    pro_tips: ["Cooked over charcoal — the burnt rice crust at the bottom is the best part", "30-40 min wait per pot — worth it", "Inside ICC Pudu food court", "Cash only, RM15-20 per pot"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Fatty Crab",
    city: "Petaling Jaya",
    neighborhood: "Taman Megah",
    category: "lunch",
    tier: 1,
    address: "2, Jalan SS 24/13, Taman Megah, PJ",
    latitude: 3.1120,
    longitude: 101.6180,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Chilli crab — the signature", "Butter prawns", "Fried mantou buns to soak up the sauce"],
    pro_tips: ["THE chilli crab spot in KL/PJ — been here since the 70s", "Come in a group — crab is best shared", "Weekend dinner is packed — lunch or weekday is better", "About RM60-80 per person with crab"],
    vibe: "local",
    best_time_of_day: "evening",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Warung Kak Sah",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "lunch",
    tier: 2,
    address: "Jalan Raja Abdullah, Kampung Baru",
    latitude: 3.1622,
    longitude: 101.6990,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi campur — point at the lauk you want", "Gulai kawah (big pot curry)", "Sambal tempoyak (fermented durian sambal)"],
    pro_tips: ["Authentic kampung-style cooking — like eating at someone's home", "The tempoyak is polarizing but adventurous eaters will love it", "Cash only, RM8-12 per meal", "Lunch only, sells out by 2pm"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Chua Lam Mee",
    city: "Kuala Lumpur",
    neighborhood: "Cheras",
    category: "lunch",
    tier: 3,
    address: "Taman Yulek, Cheras",
    latitude: 3.0980,
    longitude: 101.7400,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Wan tan mee dry — springy noodles with dark soy and char siu", "Sui kow (dumpling soup)"],
    pro_tips: ["Cheras locals swear by this place", "Cash only", "Suburban — not tourist-central but worth the Grab ride if you love noodles", "Morning to early afternoon"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
];

// ============================================
// BATCH 3: LUNCH B (12 spots)
// ============================================
BATCH["lunch_b"] = [
  {
    name: "Restoran Kudu bin Abdul",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "lunch",
    tier: 2,
    address: "180, Jalan Ampang, KLCC",
    latitude: 3.1580,
    longitude: 101.7180,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Roti canai telur", "Nasi goreng USA (named before the controversy)", "Mee goreng"],
    pro_tips: ["Legendary mamak near KLCC — been here forever", "Open 24 hours", "The atmosphere is pure KL mamak culture", "Great late-night option after Petronas viewing"],
    vibe: "chaotic",
    best_time_of_day: "afternoon",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nasi Kandar Deen Maju",
    city: "Kuala Lumpur",
    neighborhood: "KLCC",
    category: "lunch",
    tier: 2,
    address: "31, Jalan Raja Alang, Kampung Baru",
    latitude: 3.1615,
    longitude: 101.7010,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi kandar with mixed curries — ikan bakar, ayam goreng, dalca", "Roti canai"],
    pro_tips: ["Always packed — probably the most popular nasi kandar in KL right now", "The queue is part of the experience", "Cash only", "Go off-peak to avoid 30+ min waits"],
    vibe: "chaotic",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Restoran Oversea",
    city: "Kuala Lumpur",
    neighborhood: "Chinatown",
    category: "lunch",
    tier: 2,
    address: "4A, Jalan Balai Polis, Chinatown",
    latitude: 3.1458,
    longitude: 101.6948,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Dim sum — har gao, siu mai, char siu bao", "Roast duck", "Salted egg crab (dinner)"],
    pro_tips: ["Classic Cantonese dim sum restaurant", "Go for dim sum at lunch — the trolley service is the experience", "Weekend dim sum is packed — book or go early", "About RM30-50 per person for dim sum"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Wan Chai Dim Sum",
    city: "Petaling Jaya",
    neighborhood: "SS2",
    category: "lunch",
    tier: 2,
    address: "3, Jalan SS 2/67, SS2, Petaling Jaya",
    latitude: 3.1178,
    longitude: 101.6210,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Har gao", "Siu mai", "Custard bun (liu sha bao)", "Lo mai gai (sticky rice)"],
    pro_tips: ["Best value dim sum in PJ — incredibly cheap for the quality", "Gets packed on weekend mornings", "Cash only", "Portions are slightly smaller than usual but the price makes up for it"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Restoran Soo Kee",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "lunch",
    tier: 2,
    address: "447-449, Jalan Changkat Thambi Dollah",
    latitude: 3.1430,
    longitude: 101.7060,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Son yeam fish head noodles (the signature)", "The sour and spicy broth is intense"],
    pro_tips: ["Famous for one thing — son yeam (tomyam-like) fish head noodles", "The broth is rich, sour, and deeply flavorful", "Can be spicy — ask for medium if unsure", "Also available dry-fried version"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Chili Pan Mee Kepong",
    city: "Kuala Lumpur",
    neighborhood: "Kepong",
    category: "lunch",
    tier: 3,
    address: "Jalan Kepong Baru, Kepong",
    latitude: 3.2100,
    longitude: 101.6380,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Pan mee with chilli flakes and poached egg", "Dry version is better than soup"],
    pro_tips: ["Kepong is KL's Chinatown suburb — tons of great Chinese food", "Very local area, rarely see tourists", "Cash only", "Good side trip if you're heading to Batu Caves"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Lucky Gardens Pork Noodles",
    city: "Kuala Lumpur",
    neighborhood: "Bangsar",
    category: "lunch",
    tier: 2,
    address: "Lucky Gardens, Bangsar",
    latitude: 3.1262,
    longitude: 101.6722,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Pork noodles in clear broth", "Add liver and intestine for the full experience"],
    pro_tips: ["Lucky Gardens is Bangsar's hawker food enclave", "The pork noodle stall is the star — queue is normal", "Cash only", "Combine with a wander through Lucky Gardens food row"],
    vibe: "local",
    best_time_of_day: "morning",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Murni Discovery",
    city: "Petaling Jaya",
    neighborhood: "SS2",
    category: "lunch",
    tier: 2,
    address: "Jalan SS 2/75, SS2, Petaling Jaya",
    latitude: 3.1190,
    longitude: 101.6220,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Nasi lemak with paru (beef lung)", "Maggi goreng", "Cheese naan"],
    pro_tips: ["PJ institution — massive menu with 200+ items", "Open till late, great for supper", "The menu is overwhelming — ask the waiter for recommendations", "Portions are generous"],
    vibe: "chaotic",
    best_time_of_day: "evening",
    indoor_outdoor: "both",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Wong Kee Chicken Rice",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "lunch",
    tier: 2,
    address: "Jalan 1/77C, near ICC Pudu",
    latitude: 3.1395,
    longitude: 101.7092,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Roasted chicken rice", "Bean sprout chicken — the Ipoh style"],
    pro_tips: ["Classic chicken rice — the roast version has beautiful caramelized skin", "Cash only, RM8-12", "Morning to early afternoon", "Near ICC Pudu area"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Nasi Dagang Ulik Mayang",
    city: "Kuala Lumpur",
    neighborhood: "Kampung Baru",
    category: "lunch",
    tier: 3,
    address: "Jalan Raja Muda Abdul Aziz, Kampung Baru",
    latitude: 3.1618,
    longitude: 101.6995,
    payment_methods: ["cash"],
    price_range: "$",
    what_to_order: ["Nasi dagang — East Coast style steamed rice with fish curry", "Nasi kerabu — blue rice with herbs and keropok"],
    pro_tips: ["East Coast Malay food in KL — rare find", "Nasi dagang is Terengganu's signature dish", "The blue rice (nasi kerabu) is naturally colored with butterfly pea flower", "Cash only, RM8-12"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Restoran Tang City",
    city: "Kuala Lumpur",
    neighborhood: "Bukit Bintang",
    category: "lunch",
    tier: 3,
    address: "Jalan Alor, Bukit Bintang",
    latitude: 3.1460,
    longitude: 101.7085,
    payment_methods: ["cash", "card"],
    price_range: "$$",
    what_to_order: ["Cantonese roast duck", "Char siu rice", "Wonton noodle soup"],
    pro_tips: ["Good sit-down Cantonese option on Jalan Alor", "Better food quality than most Jalan Alor street stalls", "Air-conditioned — good for a midday escape"],
    vibe: "casual",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
  {
    name: "Kanna Curry House",
    city: "Petaling Jaya",
    neighborhood: "Section 17",
    category: "lunch",
    tier: 2,
    address: "Jalan 17/45, Section 17, Petaling Jaya",
    latitude: 3.1100,
    longitude: 101.6350,
    payment_methods: ["cash", "card"],
    price_range: "$",
    what_to_order: ["Banana leaf rice", "Mutton curry", "Fried chicken", "Rasam"],
    pro_tips: ["PJ's beloved banana leaf rice spot", "Always packed at lunch — turnover is fast though", "The curry is rich and coconutty", "Good vegetarian options too"],
    vibe: "local",
    best_time_of_day: "afternoon",
    indoor_outdoor: "indoor",
    weather_dependent: false,
    confidence_score: 0.7,
    source: "manual",
  },
];

async function insertBatch(batchName: string, spots: any[]) {
  console.log(`\nInserting ${batchName} (${spots.length} spots)...`);
  let success = 0;
  let failed = 0;
  for (const spot of spots) {
    const { error } = await supabase.from("spots").insert(spot);
    if (error) {
      // Check if it's a duplicate
      if (error.message?.includes("duplicate") || error.code === "23505") {
        console.log(`  ~ ${spot.name} (already exists, skipping)`);
      } else {
        console.error(`  ✗ ${spot.name}: ${error.message}`);
        failed++;
      }
    } else {
      console.log(`  ✓ ${spot.name}`);
      success++;
    }
  }
  console.log(`  ${batchName}: ${success} inserted, ${failed} failed`);
}

async function main() {
  const batchArg = process.argv[2]; // optional: only run specific batch
  for (const [name, spots] of Object.entries(BATCH)) {
    if (batchArg && name !== batchArg) continue;
    await insertBatch(name, spots);
  }
  console.log("\nDone!");
}

main().catch(console.error);
