// Generate seed files from discovered spots — minimal data, no enrichment
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const p = JSON.parse(readFileSync(join(__dirname, "research-progress.json"), "utf-8"));

interface Spot {
  name: string;
  city: string;
  area: string;
  category: string;
}

const allSpots: Spot[] = Object.values(p.discovered).flat() as Spot[];
const klSpots = allSpots.filter((s: Spot) => s.city === "Kuala Lumpur");
const pjSpots = allSpots.filter((s: Spot) => s.city === "Petaling Jaya");

function generateSeedFile(spots: Spot[], comment: string): string {
  const CATEGORIES = ["breakfast", "lunch", "dinner", "cafe", "activity", "nightlife", "market"];
  const byCategory: Record<string, Spot[]> = {};
  for (const s of spots) {
    if (!byCategory[s.category]) byCategory[s.category] = [];
    byCategory[s.category].push(s);
  }

  let out = `// ${comment}\n// Auto-generated by batch-research.ts — enrich via /review UI\n\nexport const spots = [\n`;

  for (const cat of CATEGORIES) {
    const catSpots = byCategory[cat];
    if (!catSpots?.length) continue;
    catSpots.sort((a, b) => a.area.localeCompare(b.area) || a.name.localeCompare(b.name));

    out += `\n  // ============================================\n`;
    out += `  // ${cat.toUpperCase()}\n`;
    out += `  // ============================================\n`;

    for (const s of catSpots) {
      out += `  {\n`;
      out += `    name: ${JSON.stringify(s.name)},\n`;
      out += `    city: ${JSON.stringify(s.city)},\n`;
      out += `    area: ${JSON.stringify(s.area)},\n`;
      out += `    category: ${JSON.stringify(s.category)},\n`;
      out += `    tier: 2,\n`;
      out += `    confidence_score: 0.5,\n`;
      out += `    source: "llm_research",\n`;
      out += `  },\n`;
    }
  }

  out += `];\n`;
  return out;
}

const seedsDir = join(__dirname, "..", "packages", "bot", "src", "seeds");

if (klSpots.length > 0) {
  writeFileSync(join(seedsDir, "kl-research.ts"), generateSeedFile(klSpots, `KL research spots (${klSpots.length})`));
  console.log(`Wrote ${klSpots.length} KL spots`);
}
if (pjSpots.length > 0) {
  writeFileSync(join(seedsDir, "pj-research.ts"), generateSeedFile(pjSpots, `PJ/Selangor research spots (${pjSpots.length})`));
  console.log(`Wrote ${pjSpots.length} PJ spots`);
}
console.log(`Total: ${allSpots.length} spots`);
